### ISSUE TITLE
Blurry zoom-in in web-kit

### ISSUE THREAD

**Issue by gornypiotr** [timmywil/panzoom#100]
Hiya guys
I've been using panzoom for a while and am still checking with our designer if SVG is the way to handle our current task. I'd like to use panzoom to zoom on different parts of the SVG image, but in Chrome it becomes blurry, as you guys discuss here: https://github.com/timmywil/jquery.panzoom/issues/84. Can I do anything about it? @timmywil you write that "setting transforms on a group element in SVG" should help, but how do I do it? Any help would be appreciated, especially that I like your library but my customer is against the whole solution, only because it doesn't work in webkit...
Here's the piece of code I use:

``` javascript
var $map = $('.customers-map');
if ($map.length > 0)
{
    var $panzoom = $map.find('.panzoom').panzoom();
    $panzoom.parent().on('mousewheel.focal', function (e)
    {
        e.preventDefault();
        var delta = e.delta || e.originalEvent.wheelDelta;
        var zoomOut = delta ? delta < 0 : e.originalEvent.deltaY > 0;
        $panzoom.panzoom('zoom', zoomOut, {
            increment: 0.1,
            animate: false,
            focal: e
        });
    });
}
```

and my html is:

``` html
<div class="customers-map">
    <div class="panzoom">
        <img src="images/customers/customers-map.svg">
    </div>
</div>
```

**Comment by Kescay** [comment]
I had the issue with chrome that if you zoom out and back in or pan into specific locations, the svg becomes blurry.

I noticed that it happens always when the mySvg.style.transform matrix numbers had in decimals in them. So I added rounding to the pan and zoom functions

Pan:
matrix[4] = Math.round(x);
matrix[5] = Math.round(y);

Zoom:
matrix[4] = Math.round(+matrix[4] + (clientX - clientV.e(0)));
matrix[5] = Math.round(+matrix[5] + (clientY - clientV.e(1)));

And the blurryness (when zoomed to 100%) went away.

**Comment by leoimpett** [comment]
Hi, 
A few notes on the above discussion:
- Rounding the matrixes didn't work for me (Chrome 43 on Ubuntu 15); everything was still blurry, but touchscreen events (understandably) messed up!
-  The bit that's been added to the main code:
`'backface-visibility': 'hidden',
'transform-origin': this.isSVG ? '0 0' : '50% 50%' `
actually messed things up for me - I had to remove this from the source code to get things (I'm using images and a CSS background pattern) to zoom properly without blurring. 

So it might be of use to try commenting out those lines from jquery.panzoom.js if you find it's a problem!
