### ISSUE TITLE
SVG in OBJECT not suported?

### ISSUE THREAD

**Issue by ansorg** [timmywil/panzoom#18]
Hello, I'd like to use this script in an upcoming project. There we have SVG embedded in HTML with the <object> element instead of <img> (Because SVG-IMG cannot be interactive the way we need it).

I tried your script with the two methods

```
        < object data="Maps/mun-orig-ai.svg" id="floorplan-svg" ></ object>
        < img src="Maps/mun-orig-ai.svg" id="floorplan-svg" />
```

but only the img would respond to calls like $('#floorplan-svg').panzoom('zoom').

Could this be extended to work with OBJECT?

**Comment by jrameriz** [comment]
it does not fix it on one aspect. The object does not respond to movement/pan with mouse. it does however zoom.

**Comment by penfold42** [comment]
I'm seeing this too - did you find a workaround ?

**Comment by jrameriz** [comment]
@penfold42 I completely changed my project to be images instead of svg's. Did not have time to try any type of workaround at that moment. sorry...
