### ISSUE TITLE
Momentum Panning

### ISSUE THREAD

**Issue by darylteo** [timmywil/panzoom#225]
Hi @timmywil.

Firstly, thank you for saving my life with this library.

Unfortunately, it's not "there" yet. On mobile, users are used to "overscroll bounce" and "momentum scrolling" effects. Wondering if we can figure out a way to implement this in this library?

Thanks so much again.
Daryl

**Comment by timmywil** [comment]
Second request for this. I'll look into it.

**Comment by APlusDesign** [comment]
The way I implemented it was to use another library called PEP which gives you a nice elastic option with drag easing then just disable panning

[Pep homepage](http://pep.briangonzalez.org/)
`
img.panzoom({
	disablePan: true
});
`

Example here [DEMO](photos.simonilett.com/galleries/fishies/)

**Comment by timmywil** [comment]
Thanks, but that's not quite what we're after. There's no overscroll bounce.
