### ISSUE TITLE
No animation at first step with panOnlyWhenZoomed

### ISSUE THREAD

**Issue by casalaina** [timmywil/panzoom#274]
### Subject of the issue

With the minScale set at 1 and panOnlyWhenZoomed set to true, the animation seems to break between any step and the first step.
### Your environment
- version of jquery.panzoom
  3.2.2
- version of jquery
  3.1.0
- which browser and its version
  Chrome, Safari, Firefox
### Steps to reproduce

Set options with:
`minScale: 1,
        panOnlyWhenZoomed: true,`
### Expected behaviour

Steps should be consistently animated
### Actual behaviour

No animation between natural size and 1st level of zoom (or between reset back to natural size)
![panonlywhenzoomed](https://cloud.githubusercontent.com/assets/458536/18246370/84216dbc-736b-11e6-8f78-0178b12fe8c2.gif)

**Comment by BramVanroy** [comment]
This might be related to https://github.com/timmywil/jquery.panzoom/issues/297 where the focal point is ignored in the first step.

**Comment by caitecoll** [comment]
I'm seeing this same issue. Any thoughts on a temporary fix?

**Comment by pagegwood** [comment]
I was able to fix this by adding the following CSS to my pan-zoom element:

`transition: transform 200ms ease-in-out;`

For whatever reason, pan-zoom isn't adding this as an inline style to the element on the first zoom event when using these settings.
