### ISSUE TITLE
Click events on SVG elements

### ISSUE THREAD

**Issue by ezpzlmnsqz1337** [timmywil/panzoom#281]
### Subject of the issue

If I want an element to respond to click events, I have to stop propagation of mousedown/touchdown event as you say in the FAQ. But it removes the possibility to pan while mousedown/touchdown these elements.

In the example provided below you can select S5 element, but it is not possible to move the image by clicking into the elements or the road. I need the road to respond to click events, but it takes a big portion of the screen when zoomed, and user cannot move away unless he performs unzoom or knows that he has to peform mousedown/touchdown outside of the road or any other clickable element.
### Your environment
- tested 2.2.x through 3.x.x
- tested 2.2.0 and 3.1.0
- I'm only interested into Chrome, but it is not browser specific I guess
### Steps to reproduce

In the Jsbin you can zoom or move the svg. But you cannot move if you start the move on the road or any other clickable element.
Here is jsbin: http://jsbin.com/kepovedolu/edit?html,js,console,output
### Expected behaviour

You should be able to pan even when starting to pan from element that responds to click events.
### Actual behaviour

You cannot move if you start pannig from element that responds to click events.

**Comment by timmywil** [comment]
Thanks for opening an issue. This is intended behavior to allow for panzoom elements within panzoom elements, but I suppose it could be an option.
