### ISSUE TITLE
How do I make it so that I never see the background behind the Panzoom element? 

### ISSUE THREAD

**Issue by diego06884** [timmywil/panzoom#282]
Hi,
I'm having an issue where you fully zoom in your element and pan it completely top left and then you zoom out once and you are able to see the background behind the Panzoom element.
It is very similar to your FAQ question .1 and I was able to replicate the issue in the example codepen provided (http://codepen.io/timmywil/pen/qjvBF) in the FAQ's answer.
### Your environment

Chrome 53.0.2785.143 m
and the scripts used in your Codepen example
### Steps to reproduce

Go to http://codepen.io/timmywil/pen/qjvBF.
Fully zoom in the image.
Pan to the top left until the tiger is barely visible to the bottom right.
Click zoom out once.
### Expected behaviour

Zooming out should re position the tiger image so that no red background is seen.
### Actual behaviour

The red background is visible and the tiger image is off screen.
Screenshot attached.
### Notes

I noticed that if you try to pan (drag) the tiger image after the red bg is visible, the image re positions itself correctly.

Any help very much appreciated.
Thanks!

![image](https://cloud.githubusercontent.com/assets/472724/19331882/eb325742-90ac-11e6-9814-0c46eebbcbe4.png)

**Comment by znalbert** [comment]
Just came here to open this issue, and yeah, also noticing that it immediately snaps to the correct position when one tries to pan.
