### ISSUE TITLE
contain seems to be buggy since version 1.3.4

### ISSUE THREAD

**Issue by velum** [timmywil/panzoom#283]
I was having problems with contain: invert and with contain: automatic, so I decided to simply experiment with contain: true, and it was not working as expected either. I created a JS fiddle to demonstrate the problem:

[https://jsfiddle.net/velum/kdL93vpw/38/](https://jsfiddle.net/velum/kdL93vpw/38/)

On the above example, you will see that the left and right containment works fine, but not the top and bottom containment when you pan the image.

A similar bug was there all the way back to version 1.3.4:

[https://jsfiddle.net/velum/733yra1k/5/](https://jsfiddle.net/velum/733yra1k/5/)

But in the above case, event the left and right containment does not work well.

With jquery.panzoom v1.3.3 everything was working fine however:

[https://jsfiddle.net/velum/yk5y2jfg/6/](https://jsfiddle.net/velum/yk5y2jfg/6/)
### Your environment
- version of jquery.panzoom: v3.2.2 (but also tried multiple versions all the way back to 1.3.4)
- version of jquery: v3.1.1 (Also tried with v2.1.3 and v2.2.4 in some cases)
- which browser and its version: Version 53.0.2785.143 m (64-bit)
### Steps to reproduce

If your perfer jsbin: [http://jsbin.com/qaqumi/edit?html,css,js,output](http://jsbin.com/qaqumi/edit?html,css,js,output)
### Expected behaviour

It should be possible to move the "Ingredients" image all the way to the boundaries of the panzoom-parent container, but not further than that.
### Actual behaviour

In some directions, it is not event possible to go all the way to the black border, and in other directions, it is possible to go pass it.

**Comment by hunterSThompson** [comment]
Hello, I know this was just opened yesterday... but are there any updates on getting these fixed?

I am experiencing the same issues as @velum .

I'd love to use jquery panzoom in our product, but not being able bound the panning is kind of a deal breaker.

Is there anyway from the pan event I could do this manually myself until these get fixed?

Thanks!
Hunt

**Comment by timmywil** [comment]
Sorry I'm not able to spend a lot of time on this right now. I'm not sure of the underlying problem, or the difference between the test case and the [working demo page](http://timmywil.github.io/jquery.panzoom/demo/#contain). Still, if 1.3.3 works for you, I'd stick with that until this issue gets fixed.

**Comment by ash-f** [comment]
I'm having similar problem.
Once drag  the element down. I can't drag it up to top edge of the parent.
Look like target element is offset.

**Comment by hunterSThompson** [comment]
Thanks for your response @timmywil.

For future reference, you can break the demo page by just giving the parent and child set widths & heights (event after calling resetDemensions() ).

As a work around, I ended up coding a "nudge back" function that moves the canvas back to where it should be when the user drags to far.  It sort of resembles momentum panning on mobile devices.

What do you think about allowing the user to inject a contain function?

**Comment by pietrov8** [comment]
When I set the height wrapper to have such an effect when moving and distancing.

http://piotr-m.pl/projekty/stawy/panzoom.html

**Comment by ash-f** [comment]
pietrov8,
You see kobieta-left.jpg has no margin on the top originally but there is large margin on the top in the wrapper.
Same problem with me.

**Comment by pietrov8** [comment]
@timmywil 
I updated the file, where I gave two versions, one with the height of the wrapper and the other without. And where there is no set height is working properly, but it's a large area, so I want to reduce it.
http://piotr-m.pl/projekty/stawy/panzoom.html

**Comment by tuomot** [comment]
Can confirm. Ended up setting _'contain'_ to _false_ and checking the location of the panned element relative to its parent on _panzoomend_ and then utilizing _setMatrix_ to animate the element back inside the parent, if needed.

**Comment by travisje** [comment]
[Pull Request#279](https://github.com/timmywil/jquery.panzoom/pull/279/files) fixed my issue.

**Comment by Zanzavar** [comment]
Same here
