### ISSUE TITLE
First zoom step does not respect focal point

### ISSUE THREAD

**Issue by OmniCHI** [timmywil/panzoom#297]
I want to zoom in my image from the top of the thing, rather than the center, however the first zoom step zooms in on the center, not the top. subsequent zoom in and zoom out actions work fine, but if for example I want to zoom 100% in a single click it always goes to the center, not to the specified focal point.

To reproduce: set a focal point override (eg focal: {clientX:0, clientY:0} ), set zoom increment to a large value, zoom in.

**Comment by fqboy** [comment]
Same issue here, with a
`element.panzoom("zoom", {focal : e, animate: true})`

trying to execute the zoom after a double tap.

**Comment by fqboy** [comment]
@omnitographer : is panOnlyWhenZoomed set to true in your options ? When i remove it, the focal is ok...

JsFiddle : https://jsfiddle.net/dvdb4xdb/7/

You can uncomment the panOnlyWhenZoomed option line to test.

**Comment by fqboy** [comment]
Sorry to update this thread but are we the only ones with this issue ?

**Comment by BramVanroy** [comment]
I can confirm this issue. In the first zoom step (with mouse wheel, one step) the matrix seems to 'zoom' on the center top, and only after that the focal point is taken into account.

`panOnlyWhenZoomed ` did not make a difference for me, set to true or false.
