### ISSUE TITLE
Panning beyond limits loses the panned object

### ISSUE THREAD

**Issue by lokeb** [timmywil/panzoom#302]
### Panning beyond the view loses the panned object
When the user grabs the object and drags it beyond the limits of the viewport, the object is lost forever and there is no way to get it back.

### Your environment
* Latest
* Latest
* Chrome

### Steps to reproduce
Drag the object beyond the limits of the viewport

### Expected behaviour
It should stop when the limits of the object matches that of the viewport, at least there should be a configuration option for it.

### Actual behaviour
As mentioned above

**Comment by lokeb** [comment]
Can be fixed with the contain option.

**Comment by lokeb** [comment]
But it's not working well. When dragging from top to bottom, it still fails to save the element from disappearing underneath. From all the other directions, it is functional and capable.

**Comment by sumitk91** [comment]
use contain : 'automatic' in option. I also faced the same problem. This will fix the issue.
