### ISSUE TITLE
Zooming on SVG element is not working

### ISSUE THREAD

**Issue by andregauthier** [timmywil/panzoom#304]
### Subject of the issue
SVGElement.offsetWidth/offsetHeight has been deprecated on Chrome and returns "undefined". Panzoom still makes use of it, see https://github.com/timmywil/jquery.panzoom/blob/master/src/panzoom.js#L555.

### Your environment
* jquery.panzoom.min.js 3.2.2
* jquery.min.js 3.1.1
* Chrome 55

### Expected behaviour
SVG should zoom

### Actual behaviour
SVG is not zooming

**Comment by shamego** [comment]
+1

**Comment by BramVanroy** [comment]
+1

I think [my issue](http://stackoverflow.com/questions/42810842/zoom-on-svg-while-contained-in-parent) is related.

**Comment by shamego** [comment]
@BramVanroy 
https://github.com/timmywil/jquery.panzoom/issues/310#issuecomment-282638161
helped me
