### ISSUE TITLE
Container with Height Creates Offset. Previous Version Does Not

### ISSUE THREAD

**Issue by HowdyMcGee** [timmywil/panzoom#306]
### Panzoom containers with set height create an offset top in the TranslateY Matrix.
There's 2 versions, the latest version ( of this plugin and 3.x jquery ) which **does not** work with a static height on the container and there's the 2.0.5 version which does work. Check out these two examples:

### Your environment
Panzoom:
Broken Version: 3.2.2
Working Version: 2.0.5

JQuery
Broken Version: 3.x
Working Version: 1.x, 2.x

Browser:
Up to date Google Chrome

### Steps to reproduce
Add a CSS static height to the panzoom container and pan upwards. The default looks fine, it happens once you start to pan up or down.

Broken: https://jsfiddle.net/wjwcz7fv/
Fiexed: https://jsfiddle.net/9crjbkt3/1/

### Expected behaviour
The latest version of panzoom should work like the old version of panzoom :)

### Actual behaviour
There's a top off-set in the matrix on the latest version, I'm assuming trying to center the image.

**Comment by mikebabb-gc** [comment]
Just to lend another voice to this issue, I encountered it too and had raised a duplicate at https://github.com/timmywil/jquery.panzoom/issues/313. Thanks for your suggestion to revert to version 2.0.5 of the plugin, @HowdyMcGee.

**Comment by nich008** [comment]
@HowdyMcGee and @mikebabb-gc
Beware #310 if you are targeting Android.  I'm stuck with an otherwise working solution that just broke.
I'd donate to help get 2.0.5 fixed.

**Comment by mikebabb-gc** [comment]
Thanks for the heads up, @nich008!

**Comment by JamesCatt** [comment]
I've encountered the same issue.

FYI you should be OK up to v3.0.0 -- The issue seems to come from something in commit 20aa64a. Will update once I find out more.

**Comment by chris-huffman** [comment]
I've ran into this same issue. I did a little bit of digging and it looks like the top and/or bottom height calculations in the setMatrix function have changed. Some of the difference (container height vs image height) calculations got dropped in versions after v3.0.0. However, I'm not really sure why or what the implications of these changes are.
