### ISSUE TITLE
Pinch to zoom only works the first time.

### ISSUE THREAD

**Issue by aruizgallego** [timmywil/panzoom#307]
### Subject of the issue
When I pinch to zoom the first time works correctly but when i try second time doesn't works. Onlye allow move the image, not pinch to zoom.

### Your environment (MOBILE)
Panzoom 3.2.2
Jquery 3.1.0
Chrome Mobile 55.0

### Steps to reproduce
https://jsfiddle.net/7rw009ay/4/

### Expected behaviour
Should works allways not only the first time

### Actual behaviour
Only works pinch to zoom the first time.

**Comment by pravid** [comment]
Have you find any solution?
Fiddle is not working btw.

**Comment by omnitographer** [comment]
There are some solutions you can try here, none worked for me yet though: https://github.com/timmywil/jquery.panzoom/issues/303

**Comment by saberrayed** [comment]
Hi, I solved this by adding a touchstart event after the end event.
Find this part of the code: // Bind the handlers
and then put this code 
   e.type = 'touchstart';
   self._trigger(e, matrix, !matrixEquals(matrix, original));
before this code: 
   e.type = 'panzoomend';
  self._trigger(e, matrix, !matrixEquals(matrix, original));

It should look like this:
// Bind the handlers
$(document)
   .off(ns)
   .on(moveEvent, move)
   .on(endEvent, function(e) {
         e.preventDefault();
         // Unbind all document events
	$(this).off(ns);
	self.panning = false;
	// Trigger our end event
	// Simply set the type to "panzoomend" to pass through all end properties
	// jQuery's `not` is used here to compare Array equality
        e.type = 'touchstart';
        self._trigger(e, matrix, !matrixEquals(matrix, original));

        e.type = 'panzoomend';
        self._trigger(e, matrix, !matrixEquals(matrix, original));
});

**Comment by saberrayed** [comment]
Hi, I solved this by adding a touchstart event after the end event.
Find this part of the code: // Bind the handlers
and then put this code 
   e.type = 'touchstart';
   self._trigger(e, matrix, !matrixEquals(matrix, original));
before this code: 
   e.type = 'panzoomend';
  self._trigger(e, matrix, !matrixEquals(matrix, original));

It should look like this:
// Bind the handlers
$(document)
   .off(ns)
   .on(moveEvent, move)
   .on(endEvent, function(e) {
         e.preventDefault();
         // Unbind all document events
	$(this).off(ns);
	self.panning = false;
	// Trigger our end event
	// Simply set the type to "panzoomend" to pass through all end properties
	// jQuery's `not` is used here to compare Array equality
        
        e.type = 'touchstart';
        self._trigger(e, matrix, !matrixEquals(matrix, original));

        e.type = 'panzoomend';
        self._trigger(e, matrix, !matrixEquals(matrix, original));
});
