### ISSUE TITLE
Positioning not correct when panned and then zoomed out

### ISSUE THREAD

**Issue by ilijaveselica** [timmywil/panzoom#314]
### Subject of the issue
I am not able to make viewport (wrapper) filled only with image all cases. When image is zoomed, then panned all the way to any corner and then when zoomed out it is being positioned "incorrectly". I would expect it to stick to the borders of the wrapper. When clicked, it suddenly repositions itself correctly.
![ss](https://cloud.githubusercontent.com/assets/6145788/22482413/27d5512e-e7f9-11e6-8c44-72f6dfb04153.png)

EDIT: I have just seen first question under FAQ section:

> How do I make it so that I never see the background behind the Panzoom element? [Example link](http://codepen.io/timmywil/pen/qjvBF)

In this example I can also see red bacground being displayed if you follow the steps I described.

### Your environment
* version of jquery.panzoom: v3.2.2
* version of jquery: v3.1.1`
* which browser and its version: Chrome 54.0.2840.100 (64-bit)

### Steps to reproduce
1) Open index.html inside demo folder and navigate to "Inverted containment within the parent element (to hide what's behind)"
2) Zoom out completely
3) Zoom in (one step only)
4) Pan image to any corner (just don't let it be in the center)
5) Zoom out (one step) - you will notice that image is not positioned correctly. If you zoom out again (or try to pan the image) it will position itself correctly

### Expected behaviour
Image should be positioned fully inside the wrapper when zoomed out completely

### Actual behaviour
Image is not 100% visible. This is what transform values look like `transform: matrix(1, 0, 0, 1, -127.8, -36.8)`

**Comment by Laz75** [comment]
I've stumbled into this case too.

I don't think my solution is the most elegant, but it appears to work.

`onZoom: function() {
    var element = $('.panzoom').panzoom("instance");
	if (element.scale == 1) {
		$('.panzoom').panzoom("reset");
	}
}`

HTH

**Comment by BramVanroy** [comment]
The reset as proposed by @Laz75 did not work for me, but remove the transform does. It doesn't look all too pretty, but at least it provides the desired functionality in the end.

        onZoom: function() {
            var element = s_map.find(".svg-wrapper").panzoom("instance");
            if (element.scale == 1) {
                s_map.find(".svg-wrapper").css("transform", "none");
            }
        }

**Comment by ilijaveselica** [comment]
For me non of these two solutions work. Can you provide a link with working example

**Comment by BramVanroy** [comment]
@ilijaveselica I had a typo in there that I know fixed. Does it help?

**Comment by drafiko** [comment]
I need help to fix this. Anyone fixed?

**Comment by shrutijsh15** [comment]
Zoom + Panning fails if we rotate the image.  Any solution for this?

**Comment by geofile** [comment]
I can't get this working either. Zoom in, pan to an area, zoom out, I am hoping to have the image centered on the area that was panned to. Is this possible?
