### ISSUE TITLE
Not able to zoom out in Firefox

### ISSUE THREAD

**Issue by matiaward** [timmywil/panzoom#315]
I am importing jquery.panzoom and jquery.mousewheel before that. In Firefox I can zoom in with the mouse but not out. If I try to zoom out, it just zooms in as well.

jquery version 3.1.1
jquery.panzoom version 3.2.2
jquery.mousewheel version 3.1.13
browser: Firefox version 50.1.0

I'm just importing those two files, should I be including others? The instructions I found made it seem like I don't need to.

Let me know if you need the site URL, it's currently just a staging site under password protection. Thank you!

**Comment by BramVanroy** [comment]
That's some very strange behaviour. I tested with the same versions and I cannot reproduce your issue unfortunately.
