### ISSUE TITLE
Unable to pan full picture when using contain: invert

### ISSUE THREAD

**Issue by cane92** [timmywil/panzoom#324]
https://jsfiddle.net/u0rjbsds/

Trying to get contain to work with a div that is smaller than the picture. Picture width is set to 100% so you can see the whole picture left to right with the bottom cut off until you pan or zoom. This is my desired behavior as the pictures I'm really using are similar to pages of a book. (I uploaded a calibration picture instead because it's easier to see that the image is clipped.)

Notice that panning vertically works but only a little bit. You can not see the whole image. (Remove style="height: 300px;" in the first line of html to see the whole image. There are 2 white circles on the bottom of the image mirroring the top.)

Now put the 300px height back in and notice that you can not pan all the way to the bottom of the image.

Desired behavior: Should be able to pan the whole image regardless of div size. I can pan the whole image if I change contain to false but then I lose the desired behavior of containing the image. I should be able to pan around the whole image without seeing any blank background.

Not sure if this is a bug or a configuration issue on my part. Any help would be appreciated!

Thanks,

Trent

**Comment by st3ph** [comment]
Would also love an option to automatically zoom so the image fit entierely in his parent.

Thank you
