### ISSUE TITLE
page not zoom in iphone6 or iphone6s

### ISSUE THREAD

**Issue by akverma080** [timmywil/panzoom#339]
### Subject of the issue
page not zoom in iphone6 or iphone6s

### Your environment
* jquery.panzoom.js v2.0.5
* version of jquery jquery 1.7
* safari and chrome iphone6

### Steps to reproduce
When click on zoom in icon or zoom range slide page not zoom

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by jcnventura** [comment]
Panzoom 2.0.5? Can you try with 3.2.2, please?
