### ISSUE TITLE
Pan what is inside the element not the element itself.

### ISSUE THREAD

**Issue by adeel3612** [timmywil/panzoom#345]
Hello i have used your awesome plugin and it is really an amazing thing. I have a question that is it possible to move the things inside of the element. Like i have a canvas in which there are different elements. So is it possible to not to move whole canvas but move what is inside the canvas? I have also a chart in canvas and when i pan it moved whole canvas div not the chart only. waiting for your response.

**Comment by jtara** [comment]
The canvas doesn't contain "different elements". It's just a bitmap surface. There are no "elements" to move.

Options:

- Multiple, overlaid canvases
- Use some graphics libraries that maintains a list of objects - either bitmap or vector - offscreen and then renders when the object list changes. They usually have some means of appearing to manipulate "objects" on the canvas. (But they are just re-rendering from off-screen list in response to mouse/touch input.) Example: fabric.js
