### ISSUE TITLE
Zoom with scale given doesn't work (broken by #263)

### ISSUE THREAD

**Issue by jtara** [timmywil/panzoom#347]
### Subject of the issue
Zoom with scale given doesn't work. Tested on iOS uiWebView, iOS wkWebView iOS 10.3.2, Android WebView Android 7.

### Your environment
* version of jquery.panzoom @c00283c162fe7da20e095ec4161bdc9dd6337745
* version of jquery 3.2.1 
* iOS UIWebView, WKWebView, 10.3.2
* Chrome WebView, Android 7.0, 59.0.3071.125 

### Steps to reproduce
.panzoom('zoom', 2.0)
.panzoom('zoom', 1.5)
etc.

### Expected behaviour
Node should zoom

### Actual behaviour
Node does not zoom.

.panzoom('zoom') zooms in by increment
.panzoom('zoom', true) zooms out by increment
pinch gesture zooms out to 1.0 if zoomed
pinch gesture otherwise seemingly ignored (but seems likely underlying non-zooming is real issue)
pan works, both with gesture and .panzoom('pan', x, y)

Observing the node in DOM using Safari Web Inspector (remote USB connection) I can see that the style on the element does NOT change when I call .panzoom('zoom', value). It DOES change when I call .panzoom('zoom') or .panzoom('zoom', true).

Update: also tried zoom with scale after first zooming in without scale given. It zooms out to 1.0 and seemingly ignores the numeric argument.

In all cases so far, I find that the numeric argument is just ignored.

Kludgy workaround: .panzoom('zoom', {increment: 2.0}) works. Full workaround would have to use desired zoom scale and current increment to calculate new increment. And might require an external gesture recognizer e.g. hammer.js. Though I suspect panzoom gesture recognition is working, so perhaps listen for zoom events, prevent default (is that possible) and issue my own zoom call.

Note: works correctly with 3.2.2. I was using current master @c00283c162fe7da20e095ec4161bdc9dd6337745

**Comment by jtara** [comment]
I think commit 8e752a7b519f169ed8bbb6784a58b9f7aa8d0532 broke it.

**Comment by jtara** [comment]
Confirmed this bug was introduced in 8e752a7b519f169ed8bbb6784a58b9f7aa8d0532 ref #263 ref#336.

Confirmed it was *not* introduced in f86ac04faa7a6262ff3a74ce8cade9b073f2bef3.

**Comment by eth5881** [comment]
Is this issue fixed? It's still not working for me

**Comment by evilc0des** [comment]
still doesn't work. Is there a known fix?
