### ISSUE TITLE
Touch pinch zoom doesn't work on Windows touch screens

### ISSUE THREAD

**Issue by augustography** [timmywil/panzoom#349]
### Subject of the issue
Your live demo doesn't work on all modern touch screen devices. Has this been tested with touch screens powered by Windows 10? I'm willing to bet the same might happen for Dell P2314T touch screens.

### Your environment
Software environment is your live demo.
../dist/jquery.panzoom.js
../test/libs/jquery.js
jQuery v3.1.0
Local environment:
Latest Chrome 59.0.3071.115 (Official Build) (64-bit)
Windows 10 Pro
Microsoft Surface Pro 3 i5

### Steps to reproduce
Go to http://timmywil.github.io/jquery.panzoom/demo/ in Chrome v59 on a Microsoft Surface Pro. The only demo that touch pinch zoom partially works is the second demo ('Pan only when zoomed area').

### Expected behaviour
Touch pinch (two fingers touch screen and move apart / together) should result in the image zoom level being adjusted. In the second Demo, this should happen even if the fingers have stopped touching the screen, perform a pan (touch move), then a second touch pinch to zoom is done.

### Actual behaviour
Only the second demo works, and then only zooms for the first touch. After zoom then pan, zooming with touching only pans.

**Comment by leafyfresh** [comment]
Can confirm.  I am experiencing this same issue.

**Comment by maartendemandt** [comment]
me2

**Comment by tom10271** [comment]
This issue has been there since Chrome 56 I think as they introduced PointEvent.

**Comment by leafyfresh** [comment]
Is there a hacky fix to work around that?

**Comment by julmot** [comment]
I can't zoom using touch pinch on Android 7/Chrome 62 too. I've tested all demos on the website.

Ping @timmywil

**Comment by julmot** [comment]
See also #360

**Comment by bitfabrikken** [comment]
Can comfirm, am experiencing this on Android 5.0.2 and 8.1.0 - Chrome version 63 0.3239.111
