### ISSUE TITLE
Pinch Zoom Not Working

### ISSUE THREAD

**Issue by PrinceDhankhar** [timmywil/panzoom#351]
### First Let Me Thanks Timmy Willison
Hi Timmy, First of all on behalf of all the users of your plugin let me please thank you for putting all your efforts into making (And Continue Updating) this productive plugin.

### Subject of the issue
Issues About Pinch Zoom On Touch Enabled Devices (Android, Win10, iOS). Please Try To Give Some Time And Give Us v3.2.3

### Your environment
jquery.panzoom v3.2.2
jquery v3.2.1
Chrome v59

**Comment by agordiichuk** [comment]
The same for me :(

**Comment by jacquescrocker** [comment]
same here

**Comment by PrinceDhankhar** [comment]
@agordiichuk @jacquescrocker Hopefully Timmy Will Understand Our Problem & Give Us Update...

**Comment by PrinceDhankhar** [comment]
Hi @timmywil 
Shall We Expect A Update Which Resolve This Problem Many of Us Experiencing?

**Comment by chris-huffman** [comment]
I found the pinch-to-zoom was not working on Android devices only. [This pull request](https://github.com/timmywil/jquery.panzoom/pull/341/commits/f3cafa21fa15db0451d30dc39849662f0b371160) seems to fix it.

**Comment by odai-alali** [comment]
@chris-huffman 
tested it and unfortunately is not working, android Chrome 55

**Comment by PrinceDhankhar** [comment]
@timmywil  We know you are busy but please resolve this issue with pinch & zoom on touch enabled devices.

**Comment by DKastani** [comment]
The issue lies in the zoom function (lines 692 - 769). The scaling matrix (m) is initialized always with the default matrix [1 0 0 , 1 0 0] so it always zooms to 1.

For a quick fix I replaced the whole function with the previous version and got zooming and panning working in mobiles once again.

**Comment by PrinceDhankhar** [comment]
Can you provide that working code.

**Comment by oliversierrab** [comment]
Having a similar issue but when pinching to Zoom Out after zooming in with a separated CTA. It pans instead on zoom out.

@DKastani can you share the working code you fixed ? Thanks

**Comment by maartendemandt** [comment]
see: https://github.com/Woela/jquery.panzoom

I reverted the commit that breaks zooming, and added a fix for double events (touch/pointer) on chrome.

I also requested pull requests for the issues (including this one), but that may take some time.

**Comment by tanthammar** [comment]
@maartendemandt THANK YOU
This fixed multiple issues for me, including pinch on iOS

**Comment by lorkel** [comment]
@maartendemandt THANK YOU!!

**Comment by daverodal** [comment]
@maartendemandt THANK YOU!! TOO, that fixed everything even my Lenovo windows 10 touch screen now works and that never did before. So thank you thank you thank you.

Is there an npm install for this?

**Comment by vbunjes** [comment]
@maartendemandt thanks! works again

**Comment by Prem-thinkdesign** [comment]
Pinching is not working in iPad and mobile devices

Version:
Panzoom js - jquery.panzoom.js v3.2.2
jQuery - 3.3.1

Check the link:
https://prem-thinkdesign.github.io/medical-mdm/medical_codes_er.html

In iPad (ios devices) Dragging and pinch to zoom in and zoom out is not working.
In mobile devices (android devices) dragging is working but pinch to zoom in and zoom out is not working.
Even I tried what you have updated also, still not working...
