### ISSUE TITLE
Plugin code differences: git -> demo page

### ISSUE THREAD

**Issue by NePheus** [timmywil/panzoom#352]
### Subject of the issue
In your git, the 3.2.2 plugin has code difference to the 3.2.2 in your demo page.

### Your environment
* panzoom 3.2.2
* jquery 3.1.1
* ipad safari

### Steps to reproduce
In your git, the 3.2.2 plugin has code difference to the 3.2.2 in your demo page.

### Expected behaviour
Compare
http://timmywil.github.io/jquery.panzoom/dist/jquery.panzoom.js
(Header: v3.2.2 * Updated: Sat Aug 27 2016)
and
https://rawgit.com/timmywil/jquery.panzoom/master/dist/jquery.panzoom.js
(Header: v3.2.2 * Updated: Wed Jun 21 2017)

### Actual behaviour
If I go with the iPad to the demo page, zoom is working. If I rebuild an own example with the git version, zoom is not working

**Comment by Conrekatsu** [comment]
Same problem here. I wasted so many hours just by trying to fix this, I thought there was an error in my code.
Please fix the git files as the downloadable js here does not work with range zoom and button zoom.

**Comment by jbest** [comment]
I have the same problem. Using the live demo version at http://timmywil.github.io/jquery.panzoom/dist/jquery.panzoom.js Updated: Sat Aug 27 2016 fixes the problem.
