### ISSUE TITLE
Using focal point with button zoom?

### ISSUE THREAD

**Issue by geofile** [timmywil/panzoom#362]
### Subject of the issue
When I zoom in with buttons, then pan, say to the bottom right corner of an image, and zoom out - the image starts to push off the screen. Is there a way to zoom out with the area that was panned to remaining centered? I know there is a demo for using the mouse wheel, but am hoping to do this with the Zoom in and Out buttons.

### Your environment
* version of jquery.panzoom
latest
* version of jquery
3.1.0
* which browser and its version
Chrome

### Steps to reproduce
Go to the first demo on this page. http://timmywil.github.io/jquery.panzoom/demo/ Zoom all of the way in, pan to the bottom right-hand corner, zoom out. (using the zoom in and zoom out buttons)

### Expected behavior
The image should zoom out and keep the place where you had panned to centered

### Actual behavior
The image goes off screen.

**Comment by geofile** [comment]
Figured this out. This was the solution for me 

`  $(document).on('click','.zoom-in',function(){
		$elem.panzoom("zoom", {
			focal: {
				clientX: centerw,
        		       clientY: centerh
			}
		});
		
	
	});`

With centerw and centerh being the center of the screen.

**Comment by jeremyjohn** [comment]
I solve mine by using
```
focal: { clientX: (window.innerWidth / 2), clientY: (window.innerHeight / 2) }
```
