### ISSUE TITLE
Using the plugin in Ionic

### ISSUE THREAD

**Issue by pdring** [timmywil/panzoom#363]
**I would like to use this plugin in an Ionic 3 application**
The plugin does not seem to load correctly. I have used an _npm_ import and confirm that the node module _jquery.panzoom_ is present. In order to import the function into my typescript file, I have tried:

```
import * as panzoom from 'jquery.panzoom';
import panzoom from 'jquery.panzoom';
import Panzoom from 'jquery.panzoom';
import { panzoom } from 'jquery.panzoom';
import { Panzoom } from 'jquery.panzoom';
```

However lint says that the imports are unused and when the script tries to call .panzoom, Safari's console indicates that the function is undefined.

I load jQuery also as a node module in the following way without a problem:

`import * as $ from 'jquery';`

Ionic 3, Angular 4
Version 3.2.2 of jquery.panzoom
Version 3.2.1 of jquery
Tested in mobile Safari

Thanks!

**Comment by rafaeldcastro** [comment]
I solved the problem using the import like this: 

**import from 'jquery.panzoom';**
