### ISSUE TITLE
contain: invert -> zoom out moves image inside, then jumps on drag

### ISSUE THREAD

**Issue by retani** [timmywil/panzoom#364]
### Subject of the issue
When using contain:invert, zooming out moves the image away from the border of the container. Then, when starting to drag the zoomed out image, it suddenly jumps into the correct position, aligning itself inside of the container.

![panzoom_inverted_zoomout_problem](https://user-images.githubusercontent.com/3465427/33279611-6fe260be-d39f-11e7-9b1a-67c2e06c65db.gif)

### Your environment
* version of jquery.panzoom: 3.2.2
* version of jquery: 1.12.4 or 3.1.0 (same problem)
* which browser and its version: chrome 61, Safari 11

### Steps to reproduce
Can be reproduced using the original demo. Example 4 for contain:invert
http://timmywil.github.io/jquery.panzoom/demo/

1. Click Zoom In
2. Pan image to a corner
3. Click Zoom Out -> Image moves away from the border
4. Try to pan the image -> jumps into corner

### Expected behaviour
While zooming out, the image should stay aligned with the border. It should not move inside. In other words, the background should not become visible. It should end in the position in which it currently jumps when trying to drag.

BTW, @timmywil, is this repository still under active maintainance?

**Comment by mohdsameer** [comment]
Same issue
