### ISSUE TITLE
Cannot stop panzoom eating events in Chrome

### ISSUE THREAD

**Issue by petehamling** [timmywil/panzoom#365]
e.stopImmediatePropagation(); isn't working in Chrome (62.0.3202.94).  I have a textbox and range slider in a panzoom and they are not receiving any events.

```
panz.on('click mousedown touchstart', 'textarea', function(e) {
        e.stopImmediatePropagation();
});

panz.on('click mousedown touchstart', 'input', function(e) {
        e.stopImmediatePropagation();
});
```

### Environment
* jquery.panzoom v3.2.2
* jquery 3.2.1
* Chrome 62.0.3202.94 and Edge 38.14393.1066.0

### Steps to reproduce
Here's the [JSFiddle](https://jsfiddle.net/2056x4bb/13/) to show the issue in Chrome and Edge.

(Safari Version 11.0.1 (13604.3.5) and Firefox Quantum 57.0.1 work as expected)

### Expected behaviour
textarea and range slider should receive mouse and touch events

Thanks!

**Comment by rafpaf** [comment]
I have the same problem. Does anyone have a solution?

**Comment by rafpaf** [comment]
Maybe this will work:
$('textarea').on('mousewheel', function (e) {
        if (this.clientHeight < this.scrollHeight) {
            // There's a scrollbar so do the normal thing: don't zoom.
            e.stopImmediatePropagation();
        } else {
            // No scrollbar, so zoom.
            e.preventDefault();
        }
    });
