### ISSUE TITLE
Panzoom 3.2 doesn't work with jquery 1.11

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [timmywil/panzoom#372]
### Subject of the issue
panzoom 3.2.2 is not compatible with jquery 1.11.0 anymore

### Your environment
* version of jquery.panzoom 3.2.2.
* version of jquery 1.11.0
* which browser and its version Chrome 64

### Steps to reproduce
This doesn't work  (3.2.2) : https://codepen.io/Melmoth-the-Wanderer/pen/MQxBjd
While this works (3.1.0 - also 3rd major release!) : https://codepen.io/Melmoth-the-Wanderer/pen/OQqwpZ

### Expected behaviour
panzoom is backwards compatible with jquery releases, at least within major update (v3)

### Actual behaviour
Panzoom doesn't work.

**Comment by anthuanvasquez** [comment]
Same issue here.
