### ISSUE TITLE
exclude?

### ISSUE THREAD

**Issue by Dj-jom2x** [timmywil/panzoom#411]
well if i put button there it also pan xD

**Comment by Dj-jom2x** [comment]
the old panzoom ignores it .. so if i havave  another dragabble inside it doesnt trigger the panning.. only if i click ouside the another draggable

**Comment by timmywil** [comment]
Thanks for opening an issue. Unfortunately, I don't understand the question. It would help if you provided a test case from https://jsfiddle.net or https://codebin.io.

**Comment by Dj-jom2x** [comment]
https://stackblitz.com/edit/old-panzoom-vs-newone

here

**Comment by Dj-jom2x** [comment]
above is the source code and preview

but here's the preview only https://old-panzoom-vs-newone.stackblitz.io/

please add rotation input... so I can just pass variable there to rotate the div

**Comment by timmywil** [comment]
It seems you confused this library with another library also called panzoom. This library used to be called `jquery.panzoom` and will later be published under `@panzoom/panzoom` on npm, not `panzoom` (the new version will be released soon). `jquery.panzoom` was a jQuery plugin and has only recently removed the jQuery dependency and become a universal library.

While I'm not vary familiar with how the first example is working, all you'd need to do to get the draggable inside to pan is call Panzoom on that element as well. Have a look at the new [exclude demo](https://timmywil.com/panzoom/demo/#Exclude%20elements%20within%20the%20Panzoom%20element%20from%20event%20handling) I just added. In your case, you probably don't even need the `exclude` option.

To add a rotation, use the [`setTransform` option](https://github.com/timmywil/panzoom#settransform) and set the rotation using CSS.

**Comment by Dj-jom2x** [comment]
sorry :( what I mean is it should drag only if you hover its real body not it's content as default.. sorry for my English xD I thought this is v2. .because they had the same implementation and name sorry..

its just custom directives will be broke if everything is draggable unless you force them to pan zoom to handle it.  It's like it will be not framework friendly. because we already had directives that create dynamic elements.. like adding divs on the fly and resize-drag them out.
