### ISSUE TITLE
Optional call stopPropagation() in handleDown 

### ISSUE THREAD

**Issue by andrey-hohlov** [timmywil/panzoom#414]
### Subject of the issue

I have a fullscreen carousel with panzoom inside slides.
And I cannot handle swipe while panzoom force call ```event.preventDefault()```.

For now, while I'm using the version from the master branch I added this code to the handleDown() method:

```javascript
if (!options.onTouch || typeof options.onTouch !== 'function') {
  event.preventDefault();
  event.stopPropagation();
} else {
  options.onTouch(event, { x: x, y: y, scale: scale });
}
```

And in the function passed with onTouch option, I make decision about calling stopPropagation based on panzoom state (don't call if scale <= 1).

### Your environment

- panzoom 4.0.0-pre
- iOS 12 Safari, Android Chrome 77

### Expected behaviour

Option to manage event.stopPropagation() calling.

Example in another panzoom library https://github.com/anvaka/panzoom#handling-touch-events

_Example of behavior I want to achieve: 
https://m.lamoda.ru/p/mp002xc001fb/clothes-supermamket-konvert/ (open it in a mobile browser and click on the product image)._

I hope my explanation is clear 🙏

**Comment by timmywil** [comment]
I'm mostly sold on adding an option to handle this, but I'm not so sure I like `onTouch` as the solution. I was thinking something more specific. `preventDefault` is important, especially for mobile browsers, but I think your case will work fine with `preventDefault` still getting called. Panzoom calls `stopPropagation` to allow for Panzoom elements within Panzoom elements, but is not necessary if you don't need that.

So, perhaps `propagateEvent: true`?

**Comment by andrey-hohlov** [comment]
@timmywil ```propagateEvent``` is good. But in some cases, we need to make decision depends on the state.

> If %something% propagateEvent else don't

That's why I suppose callback will be more flexible.

**Comment by timmywil** [comment]
You're right. A callback is more flexible. I was a little more specific with the naming and purpose of this callback as we already have the `panzoomstart` event. https://github.com/timmywil/panzoom/pull/416
