### ISSUE TITLE
Is it possible to add Compiled JS to Git?

### ISSUE THREAD

**Issue by djakabubu** [timmywil/panzoom#415]
Sorry for requesting,
I would like to use this in my small project, but I'm not able to compile TS.

Is it possible to add compiled JS to the repository?

Tx

**Comment by timmywil** [comment]
Thanks for opening an issue. The compiled JS will be included in releases (the first release is very close), but not on the master branch. For now, everything needed to build it is included in the dev dependencies.

1. Clone repo
2. `yarn install`
3. `yarn build`

This will create a `dist` folder with what you need.
