### ISSUE TITLE
panzoom not available on npm

### ISSUE THREAD

**Issue by ronvillalon** [timmywil/panzoom#417]
404 Not Found: @panzoom/panzoom@latest

**Comment by timmywil** [comment]
Thanks for the issue. The first release under the new name has not gone out yet, but I'll release as soon as I get time to check a few more things. For now, the master branch is in good shape.

I'll leave this issue open as this is a common question right now.

**Comment by ronvillalon** [comment]
@timmywil While we all wait for a released version, do you have instructions on how to compile panzoom for those not familiar with TypeScript?

**Comment by timmywil** [comment]
Sure, clone the repo then run

```bash
$ yarn # or npm install
$ yarn build # or npm run build
```

That will put compiled files in the `dist/` folder.

**Comment by darkowic** [comment]
Btw since there is no clear information about the state of the library I will ask here: is it an alpha/beta/rc stage? It would be great if it is available on npm ;)

**Comment by timmywil** [comment]
Not trying to be unclear. It is close to release. You can call it rc if you want.

**Comment by timmywil** [comment]
I want to accompany this first release with a blog post, which I still need to write. Other than that, I think it's ready to go.

**Comment by ronvillalon** [comment]
Looking forward to the blog post and release!

**Comment by timmywil** [comment]
Released! Available at `@panzoom/panzoom`.
