### ISSUE TITLE
Panzoom breaks on Jquery 3.4.1

### ISSUE THREAD

**Issue by shreesalunke** [timmywil/panzoom#425]
Hi Timmy
When i use panzoom with jquery 3.1.0 its works perfectly fine but when i tried with jquery 3.4.1 then I am getting below issue 
"Cannot read property 'replace' of undefined"
I think its something related with $_.cssProps

**Comment by timmywil** [comment]
Thanks for opening an issue. Panzoom has recently been rewritten to remove its jQuery dependency. The old version that is a jQuery plugin is no longer being maintained. I plan on making a jQuery wrapper so the new Panzoom is still easy to use as a jQuery plugin, but I think it's safe to say it won't have this particular issue as it won't be using `$.cssProps`.
