### ISSUE TITLE
Support overflow: visible on the parent of the panzoom div

### ISSUE THREAD

**Issue by mattnathan** [timmywil/panzoom#427]
### Subject of the issue

I'd like to be able to change the `overflow` so that I can present the panzoom element behind surrounding elements. While I could use css and `!important` it'd be nice to avoid that with a configuration option to change the behaviour of panzoom.

I don't need this to be fully configurable, but I do need it to be `visible` (or `initial` as that's the default).

### Your environment

- Version of panzoom: `7c9d819`
- Browser and browser version: Google Chrome | 78.0.3904.97

### Expected behaviour

```javascript
const parent = document.createElement('div')
const div = document.createElement('div')
parent.appendChild(div)
document.body.appendChild(parent)
const panzoom = Panzoom(div, {overflow: 'visible'})
assert.equal(parent.style.overflow, 'visible', 'Overflow option is set on the parent')
```

### Actual behaviour

Overflow is always `hidden`

**Comment by timmywil** [comment]
Thanks for the issue. I'm okay with adding this.

**Comment by mattnathan** [comment]
Thank you for accepting the change and for the quick turn around
