### ISSUE TITLE
'panzoomend' event doesn't fire when moving zoomed element with one finger

### ISSUE THREAD

**Issue by andrey-hohlov** [timmywil/panzoom#428]
### Subject of the issue

Event 'panzoomend' doesn't fire when moving zoomed element with one finger.
if happens there: https://github.com/timmywil/panzoom/blob/master/src/panzoom.ts#L446

If I change condition to ```if (pointers.length === 0)``` - it works.
But I'm not sure this change doesn't break something else, so...

### Your environment

- Panzoom 4.0.0-pre, latest build for issue date
- Android 9, Xiaomi Mi A1, Google Chrome  78
- iOS 12, iPhone 5s, Safari
- iOS 13, iPhone 7+, Safari

### Expected behaviour

'panzoomend' fires

### Actual behaviour

'panzoomend' event doesn't fire

### Steps to reproduce
Init panzoom, zoom element, move (pan) it with only one finger.
I can provide a demo a bit later if it will be needed.

**Comment by timmywil** [comment]
Thanks for finding this! I added that as effort to only trigger `panzoomend` once when panning with 2 fingers, but it seems I broke `panzoomend` for the majority of use cases. I instead moved that conditional to before the `removePointer` call. I think that should fix all the cases.
