### ISSUE TITLE
Is the example page using rewrite version?

### ISSUE THREAD

**Issue by frnhr** [timmywil/panzoom#430]
https://timmywil.com/panzoom/  this page, is it using pre-rewrite version of panzoom or the work-in-progress one?

**Comment by timmywil** [comment]
The site is using the new version. Did you see an issue?

**Comment by timmywil** [comment]
If you do, we'll reopen.

**Comment by frnhr** [comment]
No issue, I was just wondering because I see a behaviour there that I couldn't achieve with the version I'm using. I thought I must be going crazy, but then I noticed that the example page doesn't state explicitly which version is used, so there was hope for me yet 😁
In any case, thanks for the clarification! Oh, and also thanks for panzoom!!
