### ISSUE TITLE
Add deep check for excluded classes/element for all element under pointer

### ISSUE THREAD

**Issue by CZ-DannyK** [timmywil/panzoom#431]
Hi,

i have recently found your lib and i am quite happy with it. During work on my p-o-c project i have encountered problem with excluding of element via class.

Main problem is, library only checks for top target of pointer event. If you have some complex element with other elements that covers whole parent area, then this check fails.

As quick fix i have added to panzoom.ts in my cloned repo this piece of code in handleDown function:

```
    // skip panning if any element under pointer has exluded class
    for (const target of event.composedPath()) {
        const targetElement = <HTMLElement>target

        if (targetElement.classList && targetElement.classList.contains(options.excludeClass)) {
            return
        }
    }
```

Its really hotfix for my current problem, but maybe it could be used together with some option for deep check?

Cheers and i hope this will help someone :)

**Comment by timmywil** [comment]
Thanks for pointing this out. It's just semantics, but I consider this a bug.
