### ISSUE TITLE
Auto center and scale

### ISSUE THREAD

**Issue by 4KDA** [timmywil/panzoom#432]
Great performance!
It would be very cool to make it possible to automatically center and scale, relative to the parent, as it is done at https://github.com/ariutta/svg-pan-zoom

Are you planning to create such functionality?

**Comment by timmywil** [comment]
I don't currently have plans to do this, but I'm not opposed given enough interest (https://github.com/timmywil/panzoom/blob/master/.github/CONTRIBUTING.md#feature-requests). It can be done now with the `pan` and `zoom` methods after programmatically determining the center point. One potential issue I foresee would be that the center of the parent element may not necessarily be the center of the screen. In the first [demo](https://timmywil.com/panzoom/demo/), I start with the element in the center and pressing the reset button essentially returns the element to the center. I personally haven't had a need for more than that.
