### ISSUE TITLE
reset only the zoom when panOnlyWhenZoomed is true

### ISSUE THREAD

**Issue by Glandos** [timmywil/panzoom#434]
### Subject of the issue
When `panOnlyWhenZoomed` is set to true, if the user first zoom, and then pan, the `reset()` call do not reset the pan, it only reset the zoom.

If `reset` is called with `{force: true}`, the pan is also reset as mentionned in #413.

### Your environment

- Version of panzoom : 4.0.0
- Browser and browser version : Firefox 71.0

### Expected behaviour

Calling `reset()` when `panOnlyWhenZoomed` is set to `true` should reset the pan anyway.

### Actual behaviour

`reset()` reset zoom only, and `reset({force: true})` reset both.

**Comment by timmywil** [comment]
You're right. It should reset the pan anyway.
