### ISSUE TITLE
Focal point zooming running like the origin is top left when the panzoom element is large than the parent

### ISSUE THREAD

**Issue by timmywil** [timmywil/panzoom#44]
http://codepen.io/adrianosmond/pen/KjJCH

From [comment](https://github.com/timmywil/jquery.panzoom/issues/35#issuecomment-28472563)

**Comment by RedBraceWeb** [comment]
@timmywil 
I am using the contain:invert option and running into a similar problem. I tried translating the x,y coordinates based on the scale of the image but had no success. Can you look at this sample page and tell me the best method for setting the focal point? The goal is to fire the events and pan zoom to the specific coordinates. http://redbrace.com/campusmap/map.html
