### ISSUE TITLE
Feature: Add option to specify rotation

### ISSUE THREAD

**Issue by MPIIIMan** [timmywil/panzoom#442]
Hello,
Great library you have written.
I was wondering if you could easily add an option in the future to make it so you can also rotate when specifying a zoom. I have an SVG with objects that are rotated and when a user clicks on them I would like to zoom in and properly orientate the view so those objects are squared up.

There is a library called ZooMooz that has a feature to zoom an SVG and it rotates the view so the element is properly orientated. This is kind of what I'm after. See here: https://jaukia.github.io/zoomooz/examples/svgtree/index.html
That library has been abandoned and it's pretty processor intensive.
Your methods of using CSS transitions is a better approach.

**Comment by timmywil** [comment]
Thanks for opening an issue. Panzoom only deals with `translate` and `scale` internally, so while it wouldn't necessarily be difficult to add functions to work with `rotate`, there'd be no internal code using it. And with so many other possible matrix functions to pass to the transform, I see this as out of scope for the library.

That said, I think you can accomplish what you're after with the [`setTransform` option](https://github.com/timmywil/panzoom#settransform). In that SVG tree example, you could bind separate click events to each block of text on which the user would zoom in and set the rotation manually to whatever it should be.

For example, this is untested, but I'd try something like this first...

```js
const panzoom = Panzoom(panzoomElement)

appleText.addEventListener('click', (e) => {
  // Calculate center point of the text
  const rect = appleText.getBoundingClientRect()
  const point = {
    clientX: rect.left + rect.width / 2,
    clientY: rect.top + rect.height / 2
  }
  panzoom.zoomToPoint(7, point, {
    animate: true,
    setTransform: (elem, { scale, x, y }) => {
      // -20deg will reverse the rotation
      panzoom.setStyle('transform', `rotate(-20deg) scale(${scale}) translate(${x}px, ${y}px)`)
    }
  })
})
```

That might need some adjustments, but hopefully you get the idea. Zoom in on the center of the text. The rotation will get set at the same time when Panzoom uses `setTransform` to set the zoom and translation.

When you start binding more clicks, I'm sure you could dry this up and reuse the point calculation. Or  perhaps if you added more text on the left side of the tree with the same rotation, it could use the exact same click event.

I'm writing a patch now that will allow you to pass the `animate` option to `zoomToPoint`, something I had disabled for the `zoomWithWheel` case (which uses `zoomToPoint` internally).

**Comment by timmywil** [comment]
Just release 4.0.2! You should be able to animate a `zoomToPoint` now and set the transform.

By the way, another option would be to add a parent element to the mix and animate a rotation on the child at the same time you call `zoomToPoint`. That way, you wouldn't need to override the `setTransform` method.

I've added a couple [demos](https://timmywil.com/panzoom/demo/#Adding%20on%20matrix%20functions%20to%20the%20transform) in relation to this. One is an example of overriding the `setTransform` option. The other demonstrates the alternative I just mentioned. Hope that helps!
