### ISSUE TITLE
Could not find a declaration file for module '@panzoom/panzoom'. 

### ISSUE THREAD

**Issue by moltar** [timmywil/panzoom#449]
### Describe the bug

TypeScript is unable to find declarations.

```
Could not find a declaration file for module '@panzoom/panzoom'. '~/node_modules/@panzoom/panzoom/dist/panzoom.js' implicitly has an 'any' type.
  Try `npm install @types/panzoom__panzoom` if it exists or add a new declaration (.d.ts) file containing `declare module '@panzoom/panzoom';`ts(7016)
```

### Your environment

```
    "@panzoom/panzoom": "4.0.2",
```

### Expected behavior

TypeScript declarations are available.

### Actual behavior

TypeScript declarations seem to be bundled with the package, but cannot be found.

Perhaps an entry in `package.json` is needed to point to the declarations?

```
    "types": "./lib/main.d.ts"
```

From: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

### Steps to reproduce

```
npm i @panzoom/panzoom
```

Then create a new file:

```ts
import Panzoom from '@panzoom/panzoom'

const foo = Panzoom()
```

Then open it in VS Code, hover over the error:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/491247/73253894-f4e72680-41ef-11ea-92de-58b6ec10b871.png">

**Comment by moltar** [comment]
This seems to do it:

```ts
import Panzoom from '@panzoom/panzoom/src/panzoom'
```

**Comment by timmywil** [comment]
Panzoom is generating the types file, but I guess it's not picking it up. I'll go ahead and add the types property.

**Comment by moltar** [comment]
Awesome, thanks! :)
