### ISSUE TITLE
isAttached: contains only supported for HTML elements in IE11

### ISSUE THREAD

**Issue by xolir** [timmywil/panzoom#450]
### Describe the bug

IE11 does not support `node.ownerDocument.contains()` method
Thus crashes in isAttached 
https://github.com/timmywil/panzoom/blob/master/src/isAttached.ts

If I understand correctly changing that method to use `node.ownerDocument.body.contains(parent);` will suffice.

### Your environment

- Version of panzoom: ^4.0.0 
- Browser and browser version: IE11

### Expected behavior

IE11 does not crash

### Actual behavior

IE11 does crash on that call

**Comment by timmywil** [comment]
Thanks for the issue. I'll fix this.

**Comment by timmywil** [comment]
Fixed by d4f132cb822be7b22129438a5f2b6b7d405135f4

**Comment by xolir** [comment]
Thanks for rapid response, appreciate it :)
