### ISSUE TITLE
Missing Examples

### ISSUE THREAD

**Issue by DavidBoehme** [timmywil/panzoom#453]
I would really like to have a few simple examples that someone with limited java script skills can easily follow. The demo page has great examples but really no instructions on how to actually implement the library and apply to functionality to my own projects. Thank you.

**Comment by timmywil** [comment]
Thanks for opening an issue. I'm not sure what information to add to the demos. Example code for each demo can be found on the demo page, which shows how to accomplish the functionality corresponding to each demo. The README has the API docs.
