### ISSUE TITLE
IE browser compatibility?

### ISSUE THREAD

**Issue by adamjones013** [timmywil/panzoom#459]
### Describe the bug

Working on a project that requires IE compatibility but the demo doesnt seem to load in IE. On the broswer support page on GitHub it says that IE 11 is supported. Can you confirm if it is supported or not, or if it is just an issue with the demo page please.

- Latest version of panzoom
- IE 11

Fixture div is empty in IE and nothing loads onto page

https://timmywil.com/panzoom/demo/

**Comment by timmywil** [comment]
Thanks for opening an issue. Yes, IE11 is supported. I had already fixed the demo in IE, but forgot to rebuild the demo and push it to the gh-pages branch. I've just done that and it seems okay now.

**Comment by timmywil** [comment]
This is the commit btw https://github.com/timmywil/panzoom/commit/d4f132cb822be7b22129438a5f2b6b7d405135f4
