### ISSUE TITLE
Scroll bars?

### ISSUE THREAD

**Issue by strarsis** [timmywil/panzoom#468]
Is it possible to add scrollbars to the viewer area so the user can also use the scrollbars to scroll/pan around?

**Comment by timmywil** [comment]
Thanks for opening an issue. Yes, this should be possible, but I don't think any code need be added to the Panzoom library itself. There are some libraries out there to create custom scrollbars. They can be placed on top of the Panzoom element so the pointer events are not handled by Panzoom (e.g. `event.stopPropagation()`).
