### ISSUE TITLE
Click actions not working on elements that are inside Panzoom ( in webkit mobile browsers only) 

### ISSUE THREAD

**Issue by tlboon** [timmywil/panzoom#469]
Hi guys,

I'm using this plugin to pan and zoom few boxes and each box has a span as button which triggers a popup but it's not clickable in webkit mobile browsers. I'm stuck very badly so any help would be much appreciated.

I have also read thru of the FAQ in the README: https://github.com/timmywil/jquery.panzoom#faq
It doesn't help much on this issues. Any ideas?

Is the following correct?

$(document).ready(function() {

          var $section = $('div').first();
          $section.find('.panzoom').panzoom({
          	increment: 0.5,
          	duration: 200,
          	maxScale: 4,
            $zoomIn: $section.find(".zoom-in"),
            $zoomOut: $section.find(".zoom-out"),
            $reset: $section.find(".reset"),
            exclude: [document.getElementById('testa')],
            excludeClass: 'tooltip tooltip-left fade'
          });
        });

Thanks,
Boon

**Comment by timmywil** [comment]
Thanks for opening an issue. It looks like you're using the old jQuery plugin with the new options.

You have 2 paths you can take.

1. Upgrade to the new Panzoom that no longer uses jQuery and use the `exclude` and `excludeClass` options.
2. Keep using the "jquery.panzoom" jQuery plugin and instead bind an event handler to stop the event from reaching the panzoom handler. Like so...

```js
// $spans would be a jQuery collection of the clickable elements
$spans.on('mousedown touchstart', function( e ) {
  e.stopImmediatePropagation();
});
```

Let me know if that fixes it for you.
