### ISSUE TITLE
Unable to "import { PanzoomObject } from '@panzoom/panzoom';"

### ISSUE THREAD

**Issue by LewisRostron** [timmywil/panzoom#470]
### Describe the bug

Trying to:
```
import { PanzoomObject } from '@panzoom/panzoom';
```
results in typescript error:
```
Module "../node_modules/@panzoom/panzoom/src/panzoom" has no exported member 'PanzoomObject'".
```

### Your environment

- @panzoom/panzoom: 4.0.3
- Chrome Version 80.0.3987.149 (Official Build) (64-bit)

### Expected behavior

PanzoomObject should be available for import

### Actual behavior

PanzoomObject is unavailable for import from @panzoom/panzoom and must be imported via full path:
```
'../node_modules/@panzoom/panzoom/dist/src/types.d'
```

**Comment by timmywil** [comment]
Thanks for the issue. I didn't actually export those. I can go ahead and do that.
