### ISSUE TITLE
Event panzoom.zoomWithWheel doesnt work after setting contain

### ISSUE THREAD

**Issue by opdich** [timmywil/panzoom#471]
### Describe the bug

After setting the option to contain (both 'inside' and 'outside'), the wheel zoom event doesn't work. It works when contain is not set.

### Your environment

- Version of panzoom: 4.0.4
- Browser and browser version: Chrome, 80.0.3987.149

### Expected behavior

The mouse wheel should control zoom in the window

### Actual behavior

Zoom is locked. If the panzoom instance is destroyed, then set again, zoom works as intended. From checking the events, "scale" is set to NaN at first, then currently for subsequent instantiations. However, panzoom.getScale() always returns the correct value.

### Steps to reproduce

```javascript
let elPanzoom = $('#galleryMain').find('[data-indGallery=' + indGalleryFull + ']')[0];
    panzoom = new Panzoom(elPanzoom, {
        contain: 'outside'
    }); 
    elPanzoomContainer = elPanzoom.parentElement
    elPanzoomContainer.addEventListener('wheel', panzoom.zoomWithWheel);
```

**Comment by timmywil** [comment]
Thanks for opening an issue. I just added `zoomWithWheel` to the `contain: outside` demo locally and it seemed to work fine. I think I need more detail to triage this issue because there's something different about your case that I'm not seeing. Getting NaN at all is very strange. Could you reproduce in jsbin? Here is a template I started where it seems to work for me in Firefox and Chrome 80: https://jsbin.com/bajoreyatu/1/edit?html,js,output

**Comment by timmywil** [comment]
If other things are rendering around your parent element and causing the element to move after Panzoom has initialized, I could theoretically see a case where the dimensions are not accurate on load. In which case, you could fix it by waiting until everything has finished rendering somehow to initialize Panzoom.

**Comment by opdich** [comment]
Really appreciate the quick response. You were spot on with the rendering issue. The event coincided with the first time that Owl rendered. I moved that to an event and it works perfectly now.

Thanks again for the great plugin.

**Comment by luckyexpert** [comment]
I was having this issue as well, and you were correct in my case too. I had a hidden tab page I was iniating panzoom on, and the solution was to not initiate panzoom until I clicked on the tab. Initiating panzoom with the tab page hidden caused this same lockup to happen when using the contain option.
