### ISSUE TITLE
Can't cleanly pass touch/click events to panzoom children

### ISSUE THREAD

**Issue by mherodev** [timmywil/panzoom#473]
### Describe the bug

On latest devices, e.g. desktop Chrome or iOS Safari on iPhone X, click events to the panzoom element are still passed down to children, and we can add "isZooming" detection code using the panzoom events to determine if we want to handle the click events or not, and everything's great.

Unfortuantely, in older devices, e.g.  iPhone SE iOS v12.4 on Safari, I'm seeing the click events are eaten by `event.preventDefault()`. This can be avoided using the `excludeClass`, however we have so many clickable children that it breaks the pinch/zoom behavior more often than not.

I'm not quite sure what pattern to use when handling many clickable children, or if there's a different library that makes more sense for our use-case.

### Your environment

- Version of panzoom
4.1.x
- Browser and browser version
Various

### Expected behavior

Pinching to zoom doesn't click child elements and doesn't behave differently if child elements are under part of the gesture.

Clicking on child elements should trigger their click events.

### Actual behavior

Pinching to zoom behaves erratically with `excludeChildren` on since there are so many clickable elements.

Child elements are unfortunately only clickable with this enabled on older devices.

**Comment by mherodev** [comment]
Interesting, digging into `panzoom` a little, I can see you're managing three different sets of events:

```

    var events;
    if (typeof window.PointerEvent === 'function') {
        events = {
            down: 'pointerdown',
            move: 'pointermove',
            up: 'pointerup pointerleave pointercancel'
        };
    }
    else if (typeof window.TouchEvent === 'function') {
        events = {
            down: 'touchstart',
            move: 'touchmove',
            up: 'touchend touchcancel'
        };
    }
    else {
        events = {
            down: 'mousedown',
            move: 'mousemove',
            up: 'mouseup mouseleave'
        };
    }
```

And my guess is that `event.preventDefault()` for `pointerdown` doesn't effect `click`, whereas `touchstart` on an older device would, and that's why we're seeing different behavior. 

My temptation is to use this same block to change what type of event we're listening for see the propagation is the same, but that seems a little fragile.

I'd prefer that `panzoom` would optionally pass click-like events down as clicks to its children, perhaps? I could try creating a PR around that, if that makes sense.

**Comment by timmywil** [comment]
Thanks for opening an issue. I don't think it's possible to pass the events back down to children in any clean way. The event has already propagated from the children as events bubble up by nature. However, your first instinct of binding to the same event as panzoom is probably the right way to go. But instead of copying that block, I could expose that events variable and then you can use `event.stopImmediatePropagation`.

**Comment by timmywil** [comment]
However, I would try just binding to the `up` event only first. All of those affect click.

**Comment by timmywil** [comment]
The events have been exposed on master so you don't need to copy the block.

I realized that if you want to allow dragging without calling `preventDefault`, you can use the [handleStartEvent](https://github.com/timmywil/panzoom#handlestartevent) option as well. The event is passed to that function and the type is available at `event.type`.

**Comment by mherodev** [comment]
Wow, thanks for the quick turn-around @timmywil! I'll experiment with using the same events.

My biggest concern is that I'm going to have to couple how clicks are handled by elements within the panzoom element to the panzoom library itself, and I'm already contextually destroying panzoom when a user zooms in entirely on a panzoom element (since they then can't zoom back out).

So I'll need to create that coupling with the ability to decouple if panzoom is destroyed. Getting a little complex.

**Comment by mherodev** [comment]
It is clear to me after a little testing that I don't want to be calling `event.stopImmediatePropagation` as I want panzoom to pan and zoom correctly, irrespective of elements that I also want to be clickable.

Any element within the panzoom canvas that stops propagation (e.g. excludeClass) results in unwanted behaviors when a user pinches partially or entirely within those elements, either stopping or snapping the pan. 

And if they start swiping on top of those elements to pan, they won't pan at all—it's not a good user experience.

Rather than "exclude" elements from being panzoomed, I'd rather have panzoom optionally trigger click events on child elements when it's certain that it's handling an event that isn't a pan or a zoom. These events would hypothetically carry some metadata that keeps panzoom from calling `event.preventDefault()` on them, and otherwise ignores them.

**Comment by mherodev** [comment]
I clearly don't/didn't understand how click events in children are being prevented, the more I look into how events bubble up. 

Is it just the CSS style on the parent—`touch-action: none;`—that's blocking the `click` event in older Safari? And that style doesn't affect "pointer" events in latest Safari, I gather.

Perhaps we just only use panzoom on devices that support pointer events and call it a day. 🐨

**Comment by mherodev** [comment]
Ah, I finally figured it out! Sorry for all the rubber ducking in the comments. 

Parent calls to `event.preventDefault()` affecting child events was really confusing me, until it occurred to me that `touchstart` is an event before `click` and can therefore prevent it. And that's why lining up my events with `panzoom` will work, since I'll be using the supported events and won't run into side-effects by way of using `click` everywhere.

Thanks again for the help.

**Comment by timmywil** [comment]
Glad you figured it out!
