### ISSUE TITLE
panzoomend event not always called after zoom action completes

### ISSUE THREAD

**Issue by mherodev** [timmywil/panzoom#474]
### Describe the bug

On latest devices, we're seeing `panzoomend` reliable called after a series of `panzoomzoom` events, but on older devices, e.g. iPhone SE Safari, the `panzoomend` event is not dispatched after zooming. It is dispatched after panning however. 

We're relying on that event to determine we're no longer "zooming" so we handle click events without side effect.

Can this event be made more reliable?

**Comment by timmywil** [comment]
Thanks for opening an issue. The event system uses the [CustomEvent API](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent), which is not available in older versions of Safari. Currently, Safari 11.3 is the oldest version of iOS Safari supported by this library (I just look at browsers with greater than 0.25% market share).

In other words, it should be 100% reliable on browsers that can handle custom events properly. That said, if you can create a test case from https://jsbin.com so I can replicate the behavior and see it for myself, I can look into it further.

**Comment by mherodev** [comment]
Huh, looking at the user agent, it seems like this phone is using iOS Safari version 12.1.2. So, should it be working?

`Mozilla/5.0 (iPhone; CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1`

Here's a bin you can use on an older device to reproduce the missing `panzoomend` event:

https://jsbin.com/rovanuk (not sure if there is a better way to include panzoom in a jsbin)

![image](https://user-images.githubusercontent.com/1099139/78826456-5ec14080-7996-11ea-83db-fe99f095d788.png)
