### ISSUE TITLE
If the page is zoomed in on the panzoom element, the user cannot zoom back out

### ISSUE THREAD

**Issue by mherodev** [timmywil/panzoom#475]
Basically, if the user is ever able to get the entire viewport to be contained by the panzoom element, they'll be stuck there since panzoom will consume further un-zoom events.

The way we're handling this now is by destroying panzoom when we get a panzoom event and can detect that the user is zoomed in (which is highly unreliable due to how various browsers handle zoom).

Is there a better approach to take here? Or is this just the state of things with browser zoom?

### Expected behavior

Zooming out of panzoom while zoomed in zooms out the browser viewport first.

**Comment by mherodev** [comment]
And totally unrelated, but thanks for developing and open sourcing this library! 💃

**Comment by timmywil** [comment]
Thanks for opening an issue. And it's always nice to hear that someone appreciates the library. 🎉 

Unfortunately, I don't see an easy way around this issue other than to [disable browser zoom](https://stackoverflow.com/questions/27116221/prevent-zoom-cross-browser). You can pan and zoom a panzoom element or you can zoom a browser viewport, but I don't think you can do both at the same time.
