### ISSUE TITLE
Feature: Please add zoomOut option from the center

### ISSUE THREAD

**Issue by theishbiz** [timmywil/panzoom#479]
Hi, 
I've set the transform-origin as Left top through CSS, and while zoomIn it starts from Top Left, but even at zoomOut it goes same. But I actually want it to zoomOut from center. So could you please add this feature and update me. 
And Thank you for this easy JS.

**Comment by timmywil** [comment]
This library relies on the transform-origin in the simple cases. Things get more complicated when the default transform-origin is changed. As I [say in the docs](https://github.com/timmywil/panzoom#origin), change the default origin at your own risk. Is there any way you can unset or restore the transform-origin and go from there?
