### ISSUE TITLE
Feature: consider making Panzoom export a global

### ISSUE THREAD

**Issue by timmywil** [timmywil/panzoom#480]
**What problem does this feature solve?**

Panzoom is expected to be used as a module. The idea was to avoid infecting the global namespace. However, there could be cases where a global (i.e. at `window.Panzoom`) could be convenient. Please add your upvote if you would use the global instead of the import.

**Describe the solution you'd like**

`window.Panzoom` or `global.Panzoom` would become available.

**Comment by csandreas1** [comment]
how can i vote?

**Comment by JakobG-dev** [comment]
Please, that would be very useful

**Comment by timmywil** [comment]
The built version of Panzoom uses UMD, which exposes a global in non-module environments. Panzoom is added to the window when added via a script tag.
