### ISSUE TITLE
DisablePan with checkbox like the demo

### ISSUE THREAD

**Issue by Fjora24** [timmywil/panzoom#481]
I am trying to disable the pan like you have done in the demo (via the checkbox), but it does not work for me. Can you give me an orientation what should i do?
Thank you for your time!

**Comment by timmywil** [comment]
I noticed you closed this. Did you figure it out?

**Comment by Fjora24** [comment]
> I noticed you closed this. Did you figure it out?

Yes, after a lot of tests I did :) Thanx

**Comment by southernexpresso** [comment]
Hi I am interested to make this work as well, but I am stuck.
Basically, I have a toggle to enter/exit "PanZoom" mode. The moment I put the lines within a if-else, it ceases to work.
May I ask if you can kindly guide me here? Thank you and pardon.

################ Code Segment ###########################
toggleZoomMode() {
                const elem = document.getElementById('panzoom-container');
                const panzoom = Panzoom(elem, { canvas: true});
                const parent = elem.parentElement;

                if(this.isZoomMode) {
                    console.log(this.isZoomMode);
                    console.log("Supposed to disable Pan and Zoom!")
                    panzoom.setOptions({disablePan: true});
                } else {
                    panzoom.setOptions({disablePan: false, disableZoom: false});
                    parent.addEventListener('wheel', function(event) {
                    if (!event.shiftKey) return;
                    panzoom.zoomWithWheel(event);
                    })
                }
                this.isZoomMode = !this.isZoomMode;
            },
################ End of Code Segment ###########################
