### ISSUE TITLE
Typescript/babel import causing “panzoom_1.default is not a function”

### ISSUE THREAD

**Issue by duncanawoods** [timmywil/panzoom#483]
I am having trouble importing the library from typescript/babel which has be a bit lost. Given this may be my cluelessness I have created a [stackoverflow question](https://stackoverflow.com/questions/61524130/typescript-babel-import-causing-1-default-is-not-a-function) but raising here in case there is an issue with how things are exported or you know what the issue might be.

I import and use the library like this:

``` typescript
import panzoom from '@panzoom/panzoom';
panzoom(document.querySelector("#pic"));
```
which is transpiled to:
```javascript
panzoom_1.default(document.querySelector("#pic"));
```
which generates the runtime error:
```
Uncaught TypeError: panzoom_1.default is not a function
```

If I debug the javascript then `panzoom_1` has the expected function signature and it has no `default` member. This is some type of issue between the myriad different types of module, default exports and differences in how babel and typescript import them but I don't know the magic incantation.

I have found a work-around to import in a different way. It doesn't import the correct types so I am forced to cast it to `any` so this clearly isn't right is it?:

``` typescript
import * as panzoom from '@panzoom/panzoom';
(<any>panzoom)(document.querySelector("#pic"));
```

Here is the project configuration:

## tsconfig.json

``` json
{
    "compilerOptions": {
      "outDir": ".",
      "sourceMap": false,
      "noImplicitAny": true,
      "suppressImplicitAnyIndexErrors": true,
      "module": "commonjs",
      "target": "es6",
      "jsx": "react",
      "allowSyntheticDefaultImports": true,
      "traceResolution": true,
      "experimentalDecorators": true,
      "baseUrl": ".",
    }
  }
```

## package.json

``` json
{
  "name": "grr",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@babel/polyfill": "^7.8.7",
    "@panzoom/panzoom": "^4.1.0",
    "npm-update-all": "^1.0.1",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-object-rest-spread": "^7.9.6",
    "@babel/plugin-transform-async-to-generator": "^7.8.3",
    "@babel/preset-env": "^7.9.6",
    "@babel/preset-react": "^7.9.4",
    "@babel/preset-typescript": "^7.9.0",
    "awesome-typescript-loader": "^5.2.1",
    "babel-loader": "^8.1.0",
    "typescript": "^3.8.3"
  }
}
```

## webpack.config.js

``` javascript
var webpack = require("webpack");
var path = require('path');

module.exports = (env, options) => {

    var PROD = (options.mode === 'production');

    return {

        entry: [
            "@babel/polyfill",
            path.resolve(__dirname, "test.ts")
        ],

        output: {
            filename: "bundle.js",
            libraryTarget: "var"
        },

        resolve: {
            modules: [
                'node_modules'
            ],
            extensions: [".ts", ".tsx", ".js", ".json"]
        },

        module: {
            rules: [
                {
                    test: /\.tsx?$/, 
                    loaders: [
                        {
                            loader: 'babel-loader',
                            options:
                                {
                                    compact: false,
                                    presets: [
                                        [
                                            "@babel/preset-env",
                                            {
                                                targets: "> 0.25%, not dead"
                                            }
                                        ]
                                    ]
                                }
                        },
                        'awesome-typescript-loader'
                    ]
                }
            ]
        },
        devtool : false,
        optimization: {
            minimize: PROD
        }
    }
};

```

**Comment by timmywil** [comment]
Thanks for opening an issue. This does look like some sort of config issue with babel or typescript. Nothing pops out immediately at me, except to say that I'm not sure `"es6"` is a proper target (tsconfig.json). You might try setting that to `es2015`.

Also, I wonder if you need the babel-loader at all. I think `awesome-typescript-loader` has a setting for using babel under the covers.

Closing, but we can continue discussion here.

**Comment by duncanawoods** [comment]
Hi @timmywil  thanks for the reply! I have managed to fix it by adding `"esModuleInterop": true` to `tsconfig.json`.

https://www.typescriptlang.org/docs/handbook/compiler-options.html

> Emit __importStar and __importDefault helpers for runtime babel ecosystem compatibility and enable --allowSyntheticDefaultImports for typesystem compatibility.

Which means nothing to me, but a bit more information here:

https://stackoverflow.com/questions/56238356/understanding-esmoduleinterop-in-tsconfig-file

Which still doesn't mean anything to me :sob: lol. I hadn't needed this flag to import react, jquery, react, axios, moment etc. so there might be something a little unusual in panzoom's export.

**Comment by timmywil** [comment]
I think the modules you mentioned use `module.exports` instead of using an es6 default export.

**Comment by timmywil** [comment]
I looked into this more. I was thinking about this backwards. The built file only uses `module.exports`, but the typescript source would import fine. So, you could do `import Panzoom from '@panzoom/panzoom/src/panzoom'`.

I'm not sure how jQuery or react works for you. Neither of those set a `default` property on the export either in the built file.

**Comment by duncanawoods** [comment]
> So, you could do `import Panzoom from '@panzoom/panzoom/src/panzoom'.`

Yep that works without `esModuleInterop`!

> I'm not sure how jQuery or react works for you. Neither of those set a default property on the export either in the built file.

Is the difference might be that they supply their typings as separate modules: `@types/jquery` and `@types/react`? 

I was able to import them as:

``` typescript
import * as jQuery from 'jquery';
import * as React from 'react';
import * as moment from 'moment';
```

The same syntax for panzoom imported the actual code but not the typings.
