### ISSUE TITLE
Is there any zoomAndPan method?

### ISSUE THREAD

**Issue by harebuus** [timmywil/panzoom#484]
### Describe the bug
Is there any zoomAndPan method? Because focal option not working and zoom after pan looking glitchy.

### Your environment

panzoom: 4.1.0
Mozilla Firefox 75 (64 Bit)

### Expected behavior
When i use panzoom.zoom(6, {focal: {x: 0, y:0}}), zoom center instead of my point.

### Steps to reproduce

[this template](https://jsbin.com/kexejahuqo/1/edit?html,js,output)

**Comment by timmywil** [comment]
Thanks for opening an issue. I'm not sure what would be causing the focal option to be glitchy. The template you linked looks like the default template. Perhaps you just needed to click clone or save a snapshot after you made changes?

Another option is to use both the `pan` and `zoom` methods.

Can reopen with an updated test case.

**Comment by harebuus** [comment]
Sorry, I don't understand how to use jsbin. So I wrote the example [here](https://codepen.io/harebuus/pen/JjYOdjX).

I am trying to zoom in to the point I want. I add focal to the zoom function, but it does not zoom to the point I want.
When the "contain" setting is "outside", the "zoom" and "pan" (with animate) methods zoom into the wrong spot when called consecutively.
The "pan" method looks glitchy when delayed by "setTimeOut".
