### ISSUE TITLE
Is there any way we can restrict particular div avoid zoom?

### ISSUE THREAD

**Issue by Veeramuthur** [timmywil/panzoom#486]
Hi,

Is there any way i need to avoid zoom particular div.
can you have any example for div exclude, please share jsfiddle

Thank you.

**Comment by timmywil** [comment]
Sorry, I'm not sure what you're asking, but if you mean you'd like a child div to not zoom with the rest, I don't think that's possible. You could move the div elsewhere so it's not a child of a panzoom element, but if the element is a child, default browser behavior is that the transform would get applied to it as well.
