### ISSUE TITLE
Feature: Panzoom.isSupported flag

### ISSUE THREAD

**Issue by mherodev** [timmywil/panzoom#487]
**What problem does this feature solve?**
Enabling panzoom on a device where it's not entirely supported can create poor user experiences. 

We'd like to be able to detect whether or not panzoom is supported, and if it's not, fallback to a native zoom behavior and hide any UI regarding custom zooming.

**Describe the solution you'd like**
If there was a `Panzoom.isSupported` flag that was properly populated based on feature-detection or user agent string, that'd be fantastic. 

**Describe alternatives you've considered**
The alternatives are to make these checks ourselves before calling panzoom, e.g. looking at the mobile Safari version, or checking for... well some sort of browser feature I have yet to determine.

**Comment by mherodev** [comment]
Perhaps we should just use the same browserlist query?

https://github.com/browserslist/browserslist-useragent-regexp

**Comment by timmywil** [comment]
Thanks for opening an issue. I generally want to avoid adding anything that the library does not use internally. Browser support is linked in the docs. There are also several things would work in some browsers and not others and would not want to have to create feature tests for all of them. It's up to the user to determine what features to use and where if their browser support differs from Panzoom's.
