### ISSUE TITLE
Where's the panzoom.js?

### ISSUE THREAD

**Issue by jolyonralph** [timmywil/panzoom#488]
I'm probably being a bit dumb/old fashioned here (I don't use package installers, just plain JS and HTML coding), but where exactly is the panzoom.js file?

There's no js folder, and no panzoom.js file anywhere I can see.

**Comment by timmywil** [comment]
Thanks for opening an issue. The panzoom.js file is available in releases only. `npm install @panzoom/panzoom` will have the necessary files in dist. You can also get the built files from the following URLs: 

https://unpkg.com/@panzoom/panzoom@4.1.0/dist/panzoom.js
https://unpkg.com/@panzoom/panzoom@4.1.0/dist/panzoom.min.js

**Comment by timmywil** [comment]
If you're wanting to try out the master version, the following will build it...

1. Fork this repo and clone it, cd into that repo.
2. `npm install`
3. `npm run build`

The file will be in `dist`/
