### ISSUE TITLE
Panning trickles click event down to descendants

### ISSUE THREAD

**Issue by okoetter** [timmywil/panzoom#489]
### Describe the bug

I have some clickable descendants in my zoomable area which are listening on click events.
Every panning action invokes also this click event. 
Can this be prevented?

### Your environment

- Version of panzoom: 4.1.0
- Chrome 83, Firefox 77

### Expected behavior

A click with mouse moving action (=panning) should not let the click event though to the children.
A click without panning movement should be catched by my child elements.

### Actual behavior
Every panning action also invokes click events on children and descendants.

**Comment by timmywil** [comment]
Thanks for opening an issue. It's hard to tell without a test case, but I assume you're adding custom click handlers. If you'd like to prevent the click from bubbling up, you can bind to `pointerdown` and call `event.stopImmediatePropagation()`. Or, an easier solution might be to use the [exclude](https://github.com/timmywil/panzoom#exclude) or [excludeClass](https://github.com/timmywil/panzoom#excludeclass) options.

**Comment by okoetter** [comment]
No, I don't want to prevent the click to my custom click handler from bubbling up (which `event.stopImmediatePropagation()` would fix) but the opposite: I want to prevent the click from the pan event to trickle down to my custom click handler.

**Comment by timmywil** [comment]
Sorry, I'm not sure what you mean. Events don't trickle down by nature. They only bubble up the DOM tree. Do you mean you have a parent of a panzoom element with a click handler? If so, I think you could use [handleStartEvent](https://github.com/timmywil/panzoom#handlestartevent) and call `stopImmediatePropagation()` so that the pointerdown event doesn't bubble up to your element. However, that wouldn't prevent other down events or the click event, so you'd need to add a custom handler as well to the Panzoom element to prevent the click from reaching your custom handler.

Does that help?

**Comment by okoetter** [comment]
Sorry for not making myself clearer :-(
Here's some code:

```html
<div class="zoom_wrapper">
  <div class="product_wrapper">
    <div class="product">
      <img src="xyz">
    </div>
    <div class="product">
      <img src="xyz">
    </div>
    <div class="product">
      <img src="xyz">
    </div>
  </div>
</div>
```

```js
var panzoom = Panzoom(document.querySelector(".zoom_wrapper"), {
  maxScale: 6
});

$(".package img").on("click", showProductDescription);
```

Problem:
- I start panning on an image
- when I release mouse button, `click` is fired on `.package img` and `showProductDescription()` is invoked 

I don't want to call `showProductDescription()` when mouse is moved to pan after clicking on an image.
Hope this is clearer?

**Comment by okoetter** [comment]
I still did not find a solution for my problem. To help to understand it I created a codepen:
[https://codepen.io/okoetter/pen/wvGwgVQ](https://codepen.io/okoetter/pen/wvGwgVQ)

**Comment by timmywil** [comment]
Thanks for the test case. I think this has to do with a misunderstanding of how the events work. You can stop events from trickling up. You can't stop them from trickling down. For instance, I've modified your codepen to add the `"panzoom-exclude"` class to the image (https://codepen.io/timmywil/pen/zYqOwrW). Note that the image gets the event *before* Panzoom and still fires click events, but Panzoom does not drag with the exclude class there.

That said, if you want to prevent the click handler, but don't have control over that code, I see a couple possible solutions. I haven't tested these solutions in all browsers, just Chrome.

Add `pointer-events: none` to the image: https://codepen.io/timmywil/pen/LYNPyZM
Add an overlay to cover the image: https://codepen.io/timmywil/pen/ExKYmgR

**Comment by okoetter** [comment]
Thanks for your answer.
I have complete control over the code and I need the click event on the images. The click event should be invoked if (and only if) there is a click **without** a panning.

- `panzoom-exclude` class is no solution because then I cannot pan anymore
- `pointer-events: none` or overlay is no solution because then I can't click anymore ;-(

**Comment by embeddedt** [comment]
> The click event should be invoked if (and only if) there is a click without a panning.

This is not trivial to solve in a generic manner, because you need some way of distinguishing when the user clicks vs when they drag. On mobile their finger might slide even if their intent is just to click. Usually I've seen this handled by requiring a click+hold to drag.

**Comment by timmywil** [comment]
Sorry my solutions didn't help, but I hope it's clear this is not something that can be solved within the library for you. 

> The click event should be invoked if (and only if) there is a click without a panning.

How about this? https://codepen.io/timmywil/pen/VwaZWQP

**Comment by okoetter** [comment]
I think your solution is exactly what I need. I will add some kind of threshhold as you suggested but this helps me a lot.
Thank you!!!
