### ISSUE TITLE
Feature: Ability to set a pan limit or padding limit

### ISSUE THREAD

**Issue by kylegoines** [timmywil/panzoom#490]
**What problem does this feature solve?**

**Describe the solution you'd like**
The ability to set a panning limit to objects being panned
ie:
boundaryRatioVertical={0.8} 
boundaryRatioHorizontal={0.8} 

**Describe alternatives you've considered**
The `contain: 'inside'` value has a similar style, but i need to be able to toggle between zoom levels while maintaining the padding ratio limit

**Comment by timmywil** [comment]
Thanks for opening an issue. Forgive me if I misunderstand the feature, but couldn't this be accomplished by adding a wrapper element and using `contain: 'inside'`?

**Comment by kylegoines** [comment]
Thanks for getting back to me so quickly.

Maybe I'm not understanding `contain: inside` completely. As far as i understand it's implementation: the panzoom Node will no longer be-able to zoom past its rect box, but i DO want the user to be able to zoom in, contain is not allowing my object to zoom past the viewport.

**Comment by timmywil** [comment]
This sounds like unique behavior and I'm not sure how to build it into the library. I *think* you could bind to the `panzoomzoom` event and change the contain option to 'outside' when a boundary is reached. I used to have an 'auto' option for `contain` that would alternate between `inside` and `outside` depending on the size of the element relative to the container. When smaller than the container, it would be set to `'inside'`, when larger, `'outside'`. This would ensure the image was zoomable but always in view. Either way, I will leave this in the votes label for now.

**Comment by kylegoines** [comment]
@timmywil over the past two days ive auctally come across that idea, to toggle between `inside` and `outside`, but that seems to not work as expected, going from `{contain: outside}` to `{contain: inside}` seems to lock the image in a position and it seems liek the `zoomIn()` and `zoomOut` are tired to the contain, setting so i cant even trigger a `zoomOut` unless triggering it myself. Let me know if theres settings I'm overlooking.

I guess thats alot of words for saying a `contain: auto` seems exactly what I'm looking for hah

if theres a voting for the auto feature, id be happy to support that :)

**Comment by mozzi** [comment]
I got the same issue, initial size of panzoom element is smaller than container, but user need to be able too zoom it in, and have possibility to pan it after this.
