### ISSUE TITLE
touch device panning

### ISSUE THREAD

**Issue by ClintCWC** [timmywil/panzoom#494]
### Describe the bug

when disablePan: true or panOnlyWhenZoomed: true the screen on a phone or device cannot be scrolled up or down when the touch area is inside the map. 

to put that in context, i need to be able to set an option so the user can either 
1. zoom the map then scroll 
2 ignore the map and continue to scroll down the page. if the map takes up all the rest of the available view then the user cannot scroll down below the map.

### Your environment
android

### Expected behavior

when pan is disabled, the user should be able to scroll the page as normal

### Actual behavior

nothing, when pan is disabled you cannot scroll the page if you place finger in map area..

**Comment by timmywil** [comment]
Thanks for opening an issue. I've added an option to deal with this issue.

https://github.com/timmywil/panzoom#touchaction

Note that panning and pinch zooming cannot work when scrolling is enabled on mobile. The native scroll will just take over.

However, you should be able to alternate between touchAction settings to get the desired behavior.

**Comment by ClintCWC** [comment]
thank you.

**Comment by ankurgupta555** [comment]
Dear Sir,
I have used touchAction : "" in the following demo. Can you please tell me why is it not enabling scrolling on mobile devices?
https://demos.abhinavsoftware.com/panzoom/index.html
