### ISSUE TITLE
Feature: Change focal point with scale

### ISSUE THREAD

**Issue by Kazebr** [timmywil/panzoom#497]
**What problem does this feature solve?**
Focal point changes with scale.

**Describe the solution you'd like**
A way to change focal dynamically when image is scaled.

**Describe alternatives you've considered**
I have tried different formulas

I am going to scale the original image based off of user screen size. When the image scale is change, the zoom focal point changes. See Fiddle (might have to run it again after it loads): https://jsfiddle.net/Kazebr/dapn01r6/23/

**Comment by timmywil** [comment]
Thanks for the issue. Sorry, I don't quite understand the request yet. Can you not update the focal option when the user's screen size changes? Also, you can pass the `focal` option directly to the `zoom` method, so you should have full control over that when zooming.

**Comment by Kazebr** [comment]
Thanks for the response. I guess the issue I'm having with applying focal point has to do with the translate that is applied. 

- If my target is `800 x 800`, and the parent element is `400 x 400`, I apply  zoom of `0.5`, it also applies a translate of `-400px`. 
- If my target is `800 x 800`, and the parent element is `300 x 300`, I apply a zoom of `0.375`, it applies a translate of `-666.667px`. 

How is the translate being calculated?

**Comment by timmywil** [comment]
I see. It's because you're also using the `contain: outside` option, which ensures that the element fills the container. That's why the translate is applied. Containment + focal points can get complicated, but things seem to be working as expected. BTW, you might have an easier time with `zoomToPoint` rather than using `focal`.
