### ISSUE TITLE
Feature: ability to use panzoom with SSR

### ISSUE THREAD

**Issue by maximbukanov** [timmywil/panzoom#499]
**What problem does this feature solve?**
This feature solves crashes of next.js (or any other SSR app) on dev & build modes

**Describe the solution you'd like**
Try to check typeof of `window` or use exenv's canUseDom utility

**Additional context**
Here comes the log output of `npm run dev` inside next.js app
[log.txt](https://github.com/timmywil/panzoom/files/4952779/log.txt)

**Comment by timmywil** [comment]
Thanks for opening an issue. It makes sense to be able to load it without having to dynamically load it so I'll add the window checks, but you should still only initialize Panzoom on the front-end, such as in a `componentDidMount`.

**Comment by timmywil** [comment]
By the way, this is how you would include something like panzoom in next.js: https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

But this shouldn't be necessary once I finish the patch.

**Comment by maximbukanov** [comment]
Thanks for the answer! I see that you've just applied the fix for this issue. Have you deployed it to npm?
