### ISSUE TITLE
After Zooming Parent div the child div is not dragging properly

### ISSUE THREAD

**Issue by mushiahmed** [timmywil/panzoom#500]
### Describe the bug

When zooming-in/out the Parent div (using Panzoom) the child div is not dragging properly (using jQuery Draggable). Basically when I click on child div to drag, the div move away from mouse pointer.
Without zooming-in/out, child div is dragging fine.

Code HTML:
```
<div id="MainDiv" class="panzoom panzoom-parent" style="position:relative">
        <img id="img01" class="" src="MyMap.jpg" width="100%" height="auto" />
<div id="hotspot_2219" class="panzoom-exclude ui-widget-content hotspot Medium" style="top:9.836%; left:44.390%;position:absolute;"">
<img src="someImg.jpg" width="100%" height="100%">
</div>
</div>"
```

Code JS:
```
////For Parent Div
var elem = document.getElementById('MainDiv');
const panzoom = Panzoom(elem);
$(".zoom-in").click(function () { panzoom.zoomIn() });
$(".zoom-out").click(function () { panzoom.zoomOut() });
$(".reset").click(function () { panzoom.reset() });

////For Child div dragging
hotspot.draggable
                ({
                    containment: '.MainDiv',
                    stack: '.hotspot',
                    cursor: 'move',
                    revert: false,
                    stop: function (event, ui) {
                        //Some Action
                        
                    },
                    start: function (event, ui) {
                        //Some Action
                    },
                });
```

### Your environment

- Version of panzoom 4.0.0
- Chrome Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by timmywil** [comment]
Thanks for opening an issue. I can't say for sure what the problem is, but you shouldn't need to use jQuery draggable if you're using Panzoom. I suggest using one or the other as the drag events could (and probably do conflict). Note you can nest Panzoom instances and disable zooming.

**Comment by mushiahmed** [comment]
Thanks for your reply. I have multiple child div and each div have an small image which need to be draggable separately. Do I need to use Panzoom class in each child div?

**Comment by timmywil** [comment]
@mushiahmed Sorry for the late reply. Yes, you can add a Panzoom instance to as many elements that need it. The [demo page](https://timmywil.com/panzoom/demo/#Exclude%20elements%20within%20the%20Panzoom%20element%20from%20event%20handling) has an example of a Panzoom element within another.

**Comment by mushiahmed** [comment]
Is there any complete example with code of your demo page link?

**Comment by timmywil** [comment]
All code for the demos is available in this repo: https://github.com/timmywil/panzoom/blob/master/demo/examples/Exclude.tsx

**Comment by mushiahmed** [comment]
Thanks, nested elements are working fine but one issue I am facing that when after zoom-in the child elements (small images on background map image) are not moving along with mouse pointer. Is there any setting I need to set?

**Comment by timmywil** [comment]
Sorry, I'm not able to reproduce that behavior. I've added zooming to the demo above to see if there was any strange behavior on the child element when the parent was zoomed and it seemed okay.

**Comment by mushiahmed** [comment]
Thanks for looking into this. Do you have any demo having both functionality (Panning + Zooming with child elements)? or can you send me the above updated demo?

**Comment by timmywil** [comment]
The [demo](https://timmywil.com/panzoom/demo/#Exclude%20elements%20within%20the%20Panzoom%20element%20from%20event%20handling) is already updated. Click the zoom in button, then drag the parent. The child will move with it.

**Comment by mushiahmed** [comment]
Using your above demo, I have added an id = "Test01" attribute in Panzoom div and  wrote some JS code on browser console:
--------------------------------------------------------------
var elem2 = document.getElementById("Test01");
const panzoom3 = Panzoom(elem2);
panzoom3.zoomIn();
--------------------------------------------------------------
it also reproduce the same issue! (may be I doing some stupid things :(   )

**Comment by timmywil** [comment]
I'm not sure exactly which element you're talking about. Can you reproduce in a [jsbin](https://jsbin.com/dibofogini/1/edit?html,js,output) ?

**Comment by mushiahmed** [comment]
Thanks, but the same issue is still there. I am using Chrome browser. You can see the distance between mouse pointer and child div.

When Start dragging (mouse pointer is on middle of the child div):
![InkedIMG_20200807_200221111_L2](https://user-images.githubusercontent.com/4611912/89659805-d3c36900-d8e9-11ea-8d78-f1150ac3092b.jpg)

After dragging down from top to bottom:
![InkedIMG_20200807_200243252_LI](https://user-images.githubusercontent.com/4611912/89659814-d756f000-d8e9-11ea-9133-bff3af7843e9.jpg)

**Comment by timmywil** [comment]
Sorry, pictures won't help as much as a test case.

**Comment by timmywil** [comment]
Nevermind, I think I see what you mean. The child needs to account for the parent's scale to stay under the mouse.

**Comment by mushiahmed** [comment]
Yes, this is the issue. After Zooming-in when I drag the child div, it start dragging child div but **moving away from mouse pointer**.
Without Zooming-in the child div dragging along with mouse pointer perfectly.

**Comment by timmywil** [comment]
Thanks for your patience. I hadn't tried zooming with the child before. I worked out how to do this in a new example on the [demo page](https://timmywil.com/panzoom/demo/#A%20Panzoom%20instance%20within%20another%20Panzoom%20instance).

The issue is that the child panzoom instance doesn't know about the scale of ancestors. It has to be told. Given the number of possible variables and desired behaviors, I don't think this is something I should work into Panzoom core to do magically. However, it wasn't too difficult to plug this in with existing options. Let me know if this works for you as well.

**Comment by mushiahmed** [comment]
Thanks for your continuous looking into my issue. The demo page link open the same previous page (**without Zooming option**). 
I was looking "**Exclude elements within the Panzoom element from event handling**" example. Do I need to see any other?

**Comment by timmywil** [comment]
Do a refresh. there's a new example at the bottom.

**Comment by mushiahmed** [comment]
Thanks for prompt responses. The example is working perfectly in that way what I need to implement 👍 
Thanks again, will disturb you if anything stop me to implement the logic :)
