### ISSUE TITLE
Cannot import as a regular ES Module

### ISSUE THREAD

**Issue by c-hild** [timmywil/panzoom#502]
### Describe the bug

I'd like to import this as a regular ES Module in a TypeScript project. It doesn't work. Instead I get the error message that panzoom doesn't declare a "default" export.

### Your environment

Current version of panzoom.
Every evergreen browser on every version of Linux, macOS and Windows.

### Expected behavior

1. I type `import Panzoom from '@panzoom/panzoom'` near the top of my my `*.ts` TypeScript source code file.
2. The module gets loaded and is usable.

### Actual behavior

The browser gives an error message saying there's no "default" export in the `panzoom` module.

### Steps to reproduce

See "expected behavior", or visit [unpkg](https://unpkg.com/@panzoom/panzoom@4.3.1?module) in order to see the error message
```
Package @panzoom/panzoom@4.3.1 does not contain an ES module
```

**Comment by timmywil** [comment]
Thanks for opening an issue. I've added a `"source"` field to the package.json that should allow you to import the typescript source directly in future releases. I've also added an extra exported es module file for those that want es without typscript.

That said, I've found this to be a common issue importing many modules in TypeScript and have added `"esModuleInterop": true` to all of my projects (which uses `allowSyntheticDefaultImports: true` under the hood).

**Comment by c-hild** [comment]
Thank you for the swift action 👍 !

Sadly, there has not been another release since your fix, and I have not been able to import the library when `npm install` ing  from the github master branch directly. Do you have any idea how long it will be until your next release?

**Comment by timmywil** [comment]
Sorry, I can do that now.

**Comment by timmywil** [comment]
> Edit: "esModuleInterop": true does not help (and had originally actually been set by me), it still gives the error Uncaught (in promise) SyntaxError: The requested module '../../../node_modules/@panzoom/panzoom/dist/panzoom.js' does not provide an export named 'default'

That doesn't seem possible. `esModuleInterop` means it doesn't need an export named `default`. It's like your setting isn't getting applied.

**Comment by timmywil** [comment]
Also, if that were true, my tests wouldn't work.
