### ISSUE TITLE
Feature: Adding rotate

### ISSUE THREAD

**Issue by Microsomes** [timmywil/panzoom#506]
Wondering how difficult it would be to add a rotate option too, 
if you can explain the maths i could probably attempt this myself or if your feeling generous?

**Comment by timmywil** [comment]
Thanks for the issue. You can set a rotation using the [`setTransform`](https://github.com/timmywil/panzoom#settransform) and do the transform matrix calculations manually, or, and this is likely a better option, set the rotation on a parent. The [demo page](https://timmywil.com/panzoom/demo/#Adding%20on%20matrix%20functions%20to%20the%20transform) has examples of both of these.
