### ISSUE TITLE
Feature: Reimplement automatic contain

### ISSUE THREAD

**Issue by rmatec** [timmywil/panzoom#511]
**What problem does this feature solve?**
The automatic contain that was already implemented in the jQuery version of Panzoom is missing now.

**Describe the solution you'd like**
Reimplement the automatic contain feature in the same fashion as the jQuery Panzoom version.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by timmywil** [comment]
Thanks for opening an issue. I think this is worth considering, but if we were to implement this, I'd also want to incorporate https://github.com/timmywil/panzoom/issues/504 somehow, which would require some thought as it changes the possible values significantly. Just like with #504, I'm going to allow this feature some time to [gain votes](https://github.com/timmywil/panzoom/blob/master/.github/CONTRIBUTING.md#feature-requests), but I may just end up implementing it when I have time.
