### ISSUE TITLE
Problem with contain: 'outside'

### ISSUE THREAD

**Issue by pawelkuptz** [timmywil/panzoom#514]
### Describe the bug

Simply example: I have a world map in png/jpg and I need set coordinates XY to center Europe (on load). I also need to use the 'contain : outside' argument, and since then neither StartX, StartY, or pan works.

### Your environment

- Panzoom 4.3.2
- Chrome 85

### Expected behavior

I need to set the coordinates to the center of the image.

### Actual behavior

I read your note on the async nature of Panzom and I tried:
`setTimeout(() => panzoom.pan(100, 100))`

Not result, I have always default translate(0,0).

### Steps to reproduce

my code: 
`const panzoom = Panzoom(elem, {
	minScale: 1,
	contain: 'outside',
});
setTimeout(() => panzoom.pan(100, 100));`

Any ideas? Maybe I can set the values of X and Y on load in another way?

**Comment by timmywil** [comment]
Thanks for opening an issue. It could be that the image isn't large enough to reach your specified X/Y coordinates and still respect `contain: outside`. That said, if you create a test case on jsbin (here's a [template](https://jsbin.com/dibofogini/1/edit?html,js,output), I may be able to help further. For now, I'll close until we can verify a change needs to be made in Panzoom.

**Comment by cam-stitt** [comment]
I've been able to reproduce this error in a jsbin:

https://jsbin.com/yiyuzoqewe/edit?html,css,js,output

It seems that using `contain: "outside"` causes `startX` and `startY` to be ignored.

**Comment by cam-stitt** [comment]
Ha, it seems the startX and startY need to be negative numbers!
