### ISSUE TITLE
Unable to get zoomToPoint() working

### ISSUE THREAD

**Issue by richgcook** [timmywil/panzoom#516]
### Describe the bug

When firing the method `zoomToPoint()` it doesn't zoom or go to the point.

### Your environment

- Latest version
- Chrome 85.0.4183.102

### Expected behavior

Given the clientX and clientY and the scale it should zoom to the point.

### Actual behavior

Nothing happens.

### Steps to reproduce

```
const elem = document.getElementById('panzoom');
const panzoom = Panzoom(elem, {
	disablePan: true,
	maxScale: 5
});
zoomElement: function(event, scale) {
	let pointerEvent = {
		clientX: event.clientX,
		clientY: event.clientY
	};
	panzoom.zoomToPoint(scale, pointerEvent);
},
```
When console logging `pointerEvent` and `panzoom` it seems to return ok.

![Screenshot 2020-10-01 at 15 17 27](https://user-images.githubusercontent.com/901289/94821798-e47bf100-03f9-11eb-9bed-bae57b3e7737.jpg)

**Comment by timmywil** [comment]
Thanks for opening an issue. Unfortunately, I need more information to help. `zoomToPoint` is used in several demos and works fine, so there must be something special about your case. My first thought is that you're on an older version of Panzoom that disabled the pan change when `disablePan` was true.

That said, I can help further if you make a test case on jsbin. Here's a [template](https://jsbin.com/dibofogini/1/edit?html,js,output).

Closing until a change needs to be made in Panzoom.

**Comment by richgcook** [comment]
> `zoomToPoint` is used in several demos and works fine

Are you able to share this? I can't find any demos.

**Comment by timmywil** [comment]
Sure, the link is in the README, but it's called "Examples". Here it is: https://timmywil.com/panzoom/demo/
