### ISSUE TITLE
Zoom and reset functionality broken when used under a hidden bootstrap tab

### ISSUE THREAD

**Issue by viseshrp** [timmywil/panzoom#518]
### Describe the bug

When panzoom is used in a bootstrap tab layout and if the elements are behind a hidden tab, zoom and reset does not work. 

Example: if I have 2 tabs and 2 panzoom divs, one under each tab, zoom/reset only works for the panzoom element inside the initially visible tab (note that this can be any tab and is controlled by the classes 'active' and 'show'. There can be only one of these at a time i.e., only one visible tab at a time.) 
Zoom/reset works fine when whichever tab the panzoom element is under, is shown initially, regardless of the order of the tab. All other panzoom elements under the other hidden tabs (be it how many ever tabs you got) do not respond to zoom/reset.
Pan has not been tested.

Bootstrap tab docs: https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior

This is what I found on inspecting my example. This is what is actually applied:
```
.tab-content>.active {
    display: block;
}
.tab-content>.tab-pane {
    display: none;
}
```
The layout is initially set to `display: none` and then to  `display: block` when the tab is 'active'.
I have done some debugging to no avail. Could the panzoom element have a problem with being removed initially, and then made available? I'm not sure.

Please check the fiddle below.
http://jsfiddle.net/viseshrp/amexu9z0/22/

### Your environment

- Version of panzoom
4.3.2
- Browser and browser version
Chrome Version 85.0.4183.121 (Official Build) (64-bit)

### Expected behavior

Zoom and reset must work.

### Actual behavior

Zoom and reset doesn't work.

### Steps to reproduce

Fiddle: http://jsfiddle.net/viseshrp/amexu9z0/22/

**Comment by e0** [comment]
@viseshrp You could initiate Panzoom for the hidden tab when it first becomes visible. Check the modified example based on your link: http://jsfiddle.net/ok5ewhj3/ In your specific case the 200ms delay seems needed, probably due to the tab animation.

**Comment by viseshrp** [comment]
@e0 thank you. Didn't think about reinitializing it because Panzoom seemed to be loaded already, but I guess not. This fix seems to work. Appreciate it.
