### ISSUE TITLE
Touch action doesn't work in iOS browers (safari, chrome)

### ISSUE THREAD

**Issue by Lincox** [timmywil/panzoom#519]
### Describe the bug

Relate to this issue: https://github.com/timmywil/panzoom/issues/494/
Option `touchAction: ''` works fine on android browsers but doesn't work on iOS 12.x browser (even safari or others)

### Your environment

- Version of panzoom: 4.3.2
- Browser and browser version: Safari, Chrome in iOS 12.x

### Expected behavior

`touchAction: ''` is able to work on both iOS 12.x and android

### Actual behavior

`touchAction: ''` only works fine on android and iOS >=13

**Comment by timmywil** [comment]
Thanks for opening an issue. It would be very helpful if you could put together a small test case on https://jsfiddle.net or https://codepen.io. Here's a template to get started (https://jsbin.com/dibofogini/1/edit?html,js,output).

Edit: I just noticed that my custom domain stopped working all of a sudden. I'm working on getting that fixed. If you have issues with timmywil.com, please try timmywil.github.io instead.

**Comment by Lincox** [comment]
Thanks for your responding, I make a codepen for my problem
Here is the codepen: https://codepen.io/Lincox/full/eYzVMmJ

In this example, I use 2 options: `panOnlyWhenZoomed: true` and `touchAction: ''`
If you access this codepen by iPhone with iOS version < 13 (I used iOS 12.4.8), you'll see that the option `touchAction: ''` doesn't work at all because the screen on the phone cannot be scrolled up or down when the touch area is inside the map.

But if you access this codepen by iPhone with iOS version >= 13, the option `touchAction: ''` is now working because now I'm able to scroll up or down when the touch area is inside the map.

So my problem is `touchAction: ''` doesn't work on iOS < 13 's browsers when I set `panOnlyWhenZoomed: true`.

I hope you understand my problem that I'm facing, let me know if you're still confused, thank you.

**Comment by timmywil** [comment]
@Lincox I don't have access to an iPhone with iOS < 13. Could you also try overriding the [handleStartEvent](https://github.com/timmywil/panzoom#handlestartevent) to be a noop?

I'll reopen if there's a change I can make in Panzoom. If those two options don't work, it may just be a browser bug that they fixed in 13.
