### ISSUE TITLE
Doesn't work on IE9

### ISSUE THREAD

**Issue by FezVrasta** [timmywil/panzoom#52]
I've tried your plugin on IE9 (no compat mode) and it gives me these errors:

```
should reset styles when disabling ‣
TypeError: Impossible get the value of the property 'indexOf': object null or undefined

should pan with 2 fingers even if disableZoom is true ‣
AssertionError: expected 0 to not equal 0

should pan on the middle point as a focal point ‣
AssertionError: expected 0 to not equal 0

should continue with a touch event if started with a touch event ‣
AssertionError: expected false to be true

should set the starting transform value as an attribute ‣
AssertionError: expected '' to equal 'none'
```

In the readme you say that it's compatible with IE9 so I'm wondering why it doesn't work for me.

Thanks.

**Comment by jdonahue82** [comment]
I also having a problem using IE9 on Vista. The tests fail, the SVG doesn't load for the demo, and my dev code also fails where it is successful in Chrome and Firefox. I can work on a demo for you.
