### ISSUE TITLE
Feature: pan() to coordinate on SVG

### ISSUE THREAD

**Issue by ClintCWC** [timmywil/panzoom#520]
when using pan, its appears to be pixels from the center, but if you have an SVG its coords from top left (i think)

the zoom area might be 500px x 300px but the SVG within might be 4000units by 2700 units and i need to zoom to known places on the SVG

i cant figure out how to pan the view to a coordinate on the SVG. is this doable? i have tried writing code to work it out but, the results are different in chrome to firefox.

**Comment by timmywil** [comment]
Thanks for opening an issue. Yes, this should be possible using `zoomToPoint`. If you put together a test case on https://codepen.io or https://jsfiddle.net, I can help troubleshoot.

**Comment by ClintCWC** [comment]
i have created a jsfiddle
https://jsfiddle.net/clintcwc/v957u8jg/3/

i just wish to be able to zoom for example into the svg scale 3, 100 from top and 100 from left (as measured on the SVG).

any help is much appreciated

**Comment by darkbee101** [comment]
Hi there! I have the same issue and according to the OP's jsfiddle, mine also does not zoom in to the coordinate I am providing. Can you provide some insight?
