### ISSUE TITLE
help with zoomToPoint

### ISSUE THREAD

**Issue by ClintCWC** [timmywil/panzoom#521]
https://jsfiddle.net/wom7xfnL/3/ 

Hi Timmy, thanks for your help with this. (see fiddle above)

basically i wish to figure out how to zoom to a coord on the SVG, (in the case of the fiddle x50 y150 from (top left i think))

the view seems to zoom to different places depending on how wide the view port is to start with. if i make the screen wider and refresh i end up with a different part of the svg in the center of the view.

im using 

  setTimeout(function(){
  	panzoom.zoomToPoint(3, {clientX:50, clientY:150});
  },0);

i did see there is a zoomoption 'focal', but i couldnt figure out if i need it or how to use it.

i hope you don't mind me creating a new issue as im not sure if you get alerts when i added to a already closed issue.

thanks 
Clint.

**Comment by timmywil** [comment]
No problem creating an issue.

`zoomToPoint` allows the user to zoom in on any point in the parent element. In your case, the body. This is so things won't bug out when the Panzoom element is smaller than the parent, as is often the case. `zoomToPoint` uses the `focal` option internally, but is a convenience method to handle some of the complex conversions that often accompany zooming. In this case, converting a mouseover's clientX and clientY to a point inside the parent on which to zoom.

That is, you're not zooming to a point on the SVG, but a point somewhere in the parent, that then gets converted to a point on the SVG. Does that make sense?

Here's your example adjusted to zoom in on the center of the viewport. https://jsfiddle.net/timmywil/y7s92fbx/

You can use the focal option directly, but keep in mind that the focal option x/y values should have scale removed from them.

Let me know if you need more help.

**Comment by ClintCWC** [comment]
Hi Timmy thank you

i still dont get how i can zoom to a specific place on the SVG.
if i knew that i needed to zoom to coord 100 from left 150 from top how would i do that?

it might be a good idea to see the use case. and see how your good work is being put to use
https://dev.fabcomms.co.uk/dynamic_routemap/dist_gtr/#/mapview

so i need to provide a search to zoom to a specific place, i can work out where the place is in the SVG by it is coord but i cant figure out how to use those x and y values within the svg to make the thing zoom with that point in the center.

**Comment by nadafadhila** [comment]
Hi, can you give me the example (https://jsfiddle.net/timmywil/y7s92fbx/) outside jsfiddle? because I can't access it (blocked). I created a hierarchy chart & allow user to search, I need to auto focus to the result. I tried to hardcode like this
`this.panzoom.zoomToPoint(1, { clientX: 76.5565795898437, clientY: -551.0120239257812 });` but nothing happened. What was wrong with that? And what X & Y do panzoom need? Thanks!

<img width="1165" alt="Screen Shot 2025-01-09 at 20 34 00" src="https://github.com/user-attachments/assets/e90f5d49-810f-4c08-b2b7-e7d477fde74d" />
