### ISSUE TITLE
Feature: Add original event in panzoom custom events

### ISSUE THREAD

**Issue by panayotisk** [timmywil/panzoom#522]
**What problem does this feature solve?**
My specific issue is that I cannot check whether any of the shift, ctrl keys are pressed when pan starts. This was not an issue with older version of panzoom I used since the original (mouse) event was passed as a parameter to the panzoomstart event handler. 
I need this info to disable panzoom when shift or ctrl is pressed and do other actions.

**Describe the solution you'd like**
Send the original event along in the custom event data.

**Describe alternatives you've considered**
Maybe I could handle keydown-keyup events and store globally whether shift or control is currently down. It looks a bit of an overkill though.

Thank you for the excellent library! If this feature is not going to be implemented I'd like your opinions on other possible solutions.

**Comment by timmywil** [comment]
Thanks for opening an issue. I think I could add this real quick.

**Comment by timmywil** [comment]
Actually, I just realized I already put something in place for this. You can use the `handleStartEvent` option to access the original start event. That should allow you to handle this case. Let me know if you need more.

**Comment by panayotisk** [comment]
Yes, I managed to make it work with handleStartEvent. Now the same issue is happening with the panzoompan event that no longer receives the mouse x and y. The point is that I disable panning on panzoomstart event handler but I still need to get the mouse x, y coordinates on panzoompan handler.  If you could add this information somehow on panzoompan it would be great.

**Comment by timmywil** [comment]
Ok, this should be fine.

**Comment by timmywil** [comment]
@panayotisk Please try out the master branch. I'll do a release if that looks good.

**Comment by panayotisk** [comment]
@timmywil I got the master branch but could not manage to build the dist folder, so that I can use the library. When I run npm run build I get:

> Error: Could not resolve entry module (rollup.config.js).

Could you tell me what I am missing?
Please excuse my ignorance, I am not experienced on npm and haven't used rollup before.
