### ISSUE TITLE
Help with zoomToPoint part 2

### ISSUE THREAD

**Issue by ClintCWC** [timmywil/panzoom#523]
Hi Timmy thank you

i still dont get how i can zoom to a specific place on the SVG.
I need to zoom to a coord on the SVG like 100 from left 150 (not pixels but on the SVG itself) from top how would i do that?

it might be a good idea to see the use case. and see how your good work is being put to use
https://dev.fabcomms.co.uk/dynamic_routemap/dist_gtr/#/mapview
In this example i know the x,y of a station and i want to then zoom to that station in code.

so i need to provide a search to zoom to a specific place, i can work out where the place is in the SVG by its x/y coords but i cant figure out how to use those x and y values within the svg to make the thing pan to that point and zoom with that point in the center.

Also i have found that if I zoomToPoint and then pan the image and re-fire the zoomToPoint it only ever works the first time, subsequent zoomToPoint's dont seem to do anything unless i reset the view.

**Comment by timmywil** [comment]
So, `zoomToPoint` takes what are usually mouse points (hence the `clientX` and `clientY`). If you were to bind a click handler to the Panzoom element's parent and log `e.clientX` and `e.clientY`, those are the types of values expected to be passed to `zoomToPoint`.

Also try using `zoom` directly with the `focal` option (e.g. `zoom(3, { focal: { x: 100, y: 150 } })`), although this is expected to be in pixels relative to the Panzoom element's dimensions, which sounds like it's different than what you're looking for.

As for `zoomToPoint` not panning on subsequent calls, I think I'd need to see a test case. It *should* be panning even if the zoom has not changed. Thanks.
