### ISSUE TITLE
version 4.3.2 no longer works with React DnD

### ISSUE THREAD

**Issue by adamplabarge** [timmywil/panzoom#524]
### Describe the bug
React DnD with HTML5 backend enabled components were draggable with version 4.0.3 of this package.  Between 4.0.3 and 4.32, HTML5 drag events no longer seem to work.

### Your environment

- Version of panzoom - 4.3.2
- Browser and browser version - Chrome, Version 86.0.4240.193 (Official Build) (64-bit)

### Expected behavior
Ideally, DnD enabled components should work as they did in version 4.0.3.  

Components should work with HTML5 dnd
### Actual behavior
No dnd events seem to be working.

### Steps to reproduce
Probably have to setup a test to show this.  Please LMK if you need me to make sample repo w/ this issue.

**Comment by timmywil** [comment]
Thanks for opening an issue. It's hard to say without looking at the internals of React DnD, but it's likely there are conflicts binding to the same events. You can control this behavior in Panzoom with the [handleStartEvent](https://github.com/timmywil/panzoom#handlestartevent) option. Another likely culprit is [touchAction](https://github.com/timmywil/panzoom#touchaction), which you can also change, but be sure to test on mobile.

These options *should* be enough to restore DnD events. Let me know if it doesn't.

**Comment by adamplabarge** [comment]
Thank you. Will look into those.  I also understand this isn't really a bug, per say, more an FYI.  Once I get some time I'll put together something simple for testing.
