### ISSUE TITLE
Question: Best way to restrict panning to middle mouse button?

### ISSUE THREAD

**Issue by HamishWHC** [timmywil/panzoom#526]
I'm looking to restrict panning to the middle mouse button so I can add drag-to-select functionality to the left mouse button. What's the best method to do so? An earlier issue mention a 'which' option that determines which of the mouse buttons affect panzoom. This would be a very useful feature.

**Comment by timmywil** [comment]
Thanks for opening an issue. There's a native property that provides the same info as the old `which`. You should be able to use the [`button` property](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button), which is also available on Pointer Events on either the `originalEvent` detail property (recently added but only available currently on the master branch) or the `handleStartEvent` option, which passed the original pointer/mouse/touch event.

I will release the `originalEvent` property soon, but I want to test it more first.

**Comment by HamishWHC** [comment]
How would I then prevent the pan event from running? That provides the button used, but I don't think it allows me to block the event.

**Comment by timmywil** [comment]
Yes, but at that point you could set `disablePan` and/or `disableZoom`. The stopping points would be essentially the same, but I can make this slightly less code by giving special meaning to `handleStartEvent` returning `false`.

**Comment by HamishWHC** [comment]
I've just found my favourite ever workaround. I thought there was a method on the Panzoom object called disablePan. I had completely forgotten that it was an option, not a method. So I called it in handleStartEvent whenever event.button wasn't 1. I thought I would need some logic to have panning re-enabled once the mouse button had come back up. Of course this caused an error when it couldn't find the method. Yet it worked flawlessly (it took me a while to realise there was an error, as I didn't think to check console immediately when trying to debug something that was working). It turns out an error in handleStartEvent will perfectly cancel the pan action! You'll probably want to patch this, but please do include the returning false thing if you do.

**Comment by HamishWHC** [comment]
`handleStartEvent: event => {
                if (event.button !== 1) {
                    throw "10/10 best error ever."
                } else {
                    event.stopPropagation()
                    event.preventDefault()
                }
            },`

**Comment by turbopasi** [comment]
☝ +1 ! A way to prevent the panning so we include a key check would be highly appreciated . Just like we can do with the zoom event .
