### ISSUE TITLE
Feature: Ability to pass a function to panzoom options that is used to determine whether or not to pan.

### ISSUE THREAD

**Issue by HamishWHC** [timmywil/panzoom#527]
**What problem does this feature solve?**
This makes it easier to add custom exclusion logic to panzoom that may rely on more than merely which element was clicked on. This includes my earlier question regarding how to limit the mouse buttons that affect panning.

**Describe the solution you'd like**
I'd like to be able to pass a function to the panzoom constructor that will be called for every panzoom start event. The function should be passed the panzoom event. If the returned value is falsy, panzoom should prevent panning.

**Describe alternatives you've considered**
An alternative is the ability to cancel the pan event via preventDefault on the panzoomstart event. I would also want to see the inclusion of the mouse button used in the event.detail object.

**Comment by timmywil** [comment]
> mouse button used in the event.detail object

A `originalEvent` property was recently added to detail to pass on the original mouse event, from which you could get the mouse button pressed. This is also available from the event passed to `handleStartEvent` option.

Theoretically, you could set the disablePan option in the `handleStartEvent` option and then panning would be disabled in the subsequent moves.

That said, I could make this more efficient and perhaps keep everything off if `handleStartEvent` returns `false`.

Closing to put into votes needed.
