### ISSUE TITLE
How do i temporarily get mouse scroll to scroll a window 

### ISSUE THREAD

**Issue by ClintCWC** [timmywil/panzoom#528]
hi Timmy.

i have a div that in some circumstances,sits over top of the panzoom image, when the mouse is in the div i want the mouse wheel action to scroll the div up and down rather than zoom the image in and out.

when the mouse leaves the div i want it it go back to zooming the image on mouse wheel.

i know how to detect if the mouse enters or leaves the div, i just don't know how to 'reset the mouse wheel function back to default and then vice-versa

**Comment by timmywil** [comment]
Thanks for your question. This can all be done in user code.

So, as you know, the README gives example code for binding to the mousewheel.

```js
elem.parentElement.addEventListener('wheel', panzoom.zoomWithWheel)
```

but you can wrap this is in your own listener.

```js
elem.parentElement.addEventListener('wheel', (e) => {
  // This only zooms with wheel if the target is not the mentioned div or one of the div's children
  if (!e.target.closest('#id-of-div').length) {
    panzoom.zoomWithWheel(e)
  }
})
```

Let me know if that gets on you the right path.

**Comment by subham-accuknox** [comment]
Thank you so much! I have been looking for this solution! This works especially when I am using something like React-Select inside the panzoom element and want to scroll over the menu-list options.
