### ISSUE TITLE
PanZoom on SVG with click Event on Mobile

### ISSUE THREAD

**Issue by DonDiegoAA** [timmywil/panzoom#53]
Hello,

I'm using your great plugin with an inline SVG, and I want to handle some click events in the SVG.
It's working like a charm under windows or mac (ie10, firefox, chrome).

But on my Android phone (Galaxy Note 2, Android 4.1.2), it seems that the panzoom and the clicks are interfering. Click events are not handled the most of the time. But sometimes, clicks are here, but then I loose pan and zoom.

You can see an example here: http://codepen.io/DonDiego/pen/GHerI

Is there a way to make them work together ? Maybe shouldn't I use the click event ?

Thank you for your work !

**Comment by dearsina** [comment]
```
panzoom.on('panzoomend', function (e, panzoom, matrix, changed) {
		if (!changed) {
		  var offset = $(this).offset();
		  if(e.changedTouches){
		      //Mobile touches
			  var relativeX = (e.changedTouches[0].pageX - offset.left);
			  var relativeY = (e.changedTouches[0].pageY - offset.top);
		  } else {
		      //Desktop touches
		  var relativeX = (e.pageX - offset.left);
		  var relativeY = (e.pageY - offset.top);
		  }
		  console.log(relativeX + ':' + relativeY);
		  alert(relativeX + ':' + relativeY);
		}
	});
```

This will solve mohzag and Phadrix problem and allow for collection of x:y coordinates from mobile as well as from the desktop. This won't give me back my wasted evening, but will hopefully allow you to get to where you need to go a lot faster.

Background: [https://www.w3.org/TR/touch-events/#changedtouches-of-a-touchevent](url)
