### ISSUE TITLE
Missing a dist folder or the location for panzoom.js file

### ISSUE THREAD

**Issue by rafaeldcastro** [timmywil/panzoom#531]
### Describe the bug

There's no **panzoom.js** or **panzoom.min.js** file to download anywhere.
The [releases ](https://github.com/timmywil/panzoom/releases)page, give us the source code and no **dist** folder (the most common option)

The Panzoom [page ](https://timmywil.com/panzoom/)itself, let us download the source code "again"

I accessed the **demo** page and searching through the _index.html_ file got this link:
https://timmywil.com/panzoom/demo/panzoom.js

Wich leads me to the panzoom.js file, but its not minified, and for the way I "got" it, its not the **ideal**.

I know you do offer installation on npm, yarn etc. But none of them are the final, plain and simple panzoom.min.js that you can download and import on a simple project.

### Your environment

- Any version
- Any Browser

### Expected behavior

Clone or download the repository with a **dist** folder, where the panzoom.js or panzoom.min.js can be found.

### Actual behavior

No simple js file or minified version of the lib found anywhere

### Steps to reproduce

Try get/search for the panzoom.js or panzoom.min.js file

**Comment by timmywil** [comment]
Thanks for opening an issue. The `dist/` folder is only added to tags, which are released to npm, and you can download anything from npm using the cdn unpkg.com.

https://unpkg.com/@panzoom/panzoom@4.3.2/dist/panzoom.min.js

To try out the version on master:

1. Fork this repo and clone it, cd into that repo.
2. `npm install`
3. `npm run build`

The file will be in `dist/`

**Comment by timmywil** [comment]
You're right that the dist folder was not in the git tags, despite being available on npm. I went ahead and changed that part.
