### ISSUE TITLE
Feature use - How to Panzoom an element using another element?

### ISSUE THREAD

**Issue by rafaeldcastro** [timmywil/panzoom#532]
On JqueryPanzoom version I was abe to perform "panzooming" functionalities executing the lib on a Element but targeting the move on another element (not children)

```
$('#el-panzoom').panzoom({
    $set: $('#another-el'), which: -1
});
```
How can achieve this behavior with this new lib?

BTW. Thanks for this amazing job. That lib is one of the most impressive works on internet.

**Comment by timmywil** [comment]
You're very kind 😊 

While the `$set` option is no longer available in the jquery-less version of the library, you should be able to accomplish this behavior by using the [setTransform option](https://github.com/timmywil/panzoom#settransform) instead.

For instance, something like this should do it, but I haven't tested to make sure:

```js
Panzoom(elem, {
  setTransform: (elem, { scale, x, y }) => {
    yourOtherElem.style.transform = `scale(${scale}) translate(${x}px, ${y}px)`
  }
})
```

Let me know if you need more.

**Comment by rafaeldcastro** [comment]
PERFECT FIT! :D
I had still made the mistake of starting the first element's panzoom directly, but it wasn't necessary. Your code served as a glove and had the desired effect!

Thank you!
