### ISSUE TITLE
Feature use: Infinite droppable canvas within a container

### ISSUE THREAD

**Issue by kctpradeep** [timmywil/panzoom#535]
First of all, I thank you for this awesome library. Great work indeed.
	
I have created a codepen that uses jquery ui (for drag/drop), jsPlumb (for flowcharting) and panzoom (panning and zooming) to create a flowchart builder. You could drag the list items from the draggable container (1st column) to the flowchart (2nd column) and then connect the items using the dots to create a flowchart. The #flowchart is a panzoom target with both pan and zoom enabled. This all works fine.

However, I would like to have the #flowchart div always span the whole area of the flowchart-wrapper i.e. the #flowchart should be an infinite canvas that supports panning, zooming and is a droppable container.
		
It should be something similar to https://jsplumbtoolkit.com/demonstration/flowchart-builder. The canvas there is infinitely scalable where you drag and drop items (Questions, Actions, Outputs) from the right column. 
	
Any pointers on how to achieve this (like the relevant events or multiple panzoom elements and/or css changes) would be greatly appreciated. 

Link to codepen: https://codepen.io/kctpradeep/pen/QWKgRRz

**Comment by timmywil** [comment]
Thanks for opening an issue. First, have a look at the [canvas option](https://github.com/timmywil/panzoom#canvas) and see if that works for you. Another idea is to use the [`setTransform` option](https://github.com/timmywil/panzoom#settransform), which would give you more fine-grained control over what is moving. Here's a comment from another recent issue: https://github.com/timmywil/panzoom/issues/532#issuecomment-740209607

The use case there wasn't the same, but I think it's a good example of the power of that option.

Let me know if that doesn't get you on the right path.

**Comment by kctpradeep** [comment]
Thanks for the reply Timmy. As seen in my codepen, I have already set the canvas option to true. I'm afraid I can't use the setTransform option as the droppable surface and the panzoom target element are the same. I have also tried out by creating a wrapper div around but that didn't work either.

**Comment by kctpradeep** [comment]
> Thanks for the reply Timmy. As seen in my codepen, I have already set the canvas option to true. I'm afraid I can't use the setTransform option as the droppable surface and the panzoom target element are the same. I have also tried out by creating a wrapper div around but that didn't work either.

Do you have any updates on this @timmywil?

**Comment by timmywil** [comment]
I haven't had time to look at it again, but I will say that most issues can be solved by adding a wrapper. I will probably be able to work up an example for you using the `canvas` option and a wrapper.

**Comment by kctpradeep** [comment]
> I haven't had time to look at it again, but I will say that most issues can be solved by adding a wrapper. I will probably be able to work up an example for you using the `canvas` option and a wrapper.

It would be absolutely great if I can have a working example. Many thanks.

**Comment by weng7654** [comment]
i have same problem

**Comment by weng7654** [comment]
> > I haven't had time to look at it again, but I will say that most issues can be solved by adding a wrapper. I will probably be able to work up an example for you using the `canvas` option and a wrapper.
> 
> It would be absolutely great if I can have a working example. Many thanks.

I solve this problem,this is codePen link : https://codepen.io/weng765/pen/YzdrdwG

Step 1: Add CSS to the flowchart-wrapper with the property {position: relative}, to ensure that the parent node achieves the effect of an infinite canvas. 
Step 2: Since jsplumb is restricted to the flowchart div, remove the containment: "parent" drag property, to allow it to be positioned outside the parent node (e.g., left: -100px, top: -100px). 
Step 3: Change the draggable droppable functionality to apply to the #flowchart-wrapper div, and calculate the offset using var offsetchart = $('#flowchart').offset();

**Comment by kctpradeep** [comment]
> > > I haven't had time to look at it again, but I will say that most issues can be solved by adding a wrapper. I will probably be able to work up an example for you using the `canvas` option and a wrapper.
> > 
> > 
> > It would be absolutely great if I can have a working example. Many thanks.
> 
> I solve this problem,this is codePen link : https://codepen.io/weng765/pen/YzdrdwG
> 
> Step 1: Add CSS to the flowchart-wrapper with the property {position: relative}, to ensure that the parent node achieves the effect of an infinite canvas. Step 2: Since jsplumb is restricted to the flowchart div, remove the containment: "parent" drag property, to allow it to be positioned outside the parent node (e.g., left: -100px, top: -100px). Step 3: Change the draggable droppable functionality to apply to the #flowchart-wrapper div, and calculate the offset using var offsetchart = $('#flowchart').offset();

Great to see a working solution. Many thanks @weng7654.
