### ISSUE TITLE
How to install 4.x versions?

### ISSUE THREAD

**Issue by jenlampton** [timmywil/panzoom#537]
Hello and thanks for this handy tool! I checked out the demo, and it is exactly what I need for my project. Where/How can I get the javascript files to add to a web page? 

In [Installing](https://github.com/timmywil/panzoom#installing) in the readme there's a section for `With a script tag` that has the following code:
```
<script src="/js/panzoom.js"></script>
```
...but there's no `js` directory in this project, and no file named `panzoom.js` (though it is referenced in a few of the other files). 

I have seen a `src` directory in Java projects before -- so I'm guessing what is in there needs to be compiled? Would you be able to include some instructions on how to do that for those of us who are not front-end devs?

I did google `.ts` files to see if I could figure it out quickly, but I don't think this project is full of video stream files :)

(I also tried the `npm` command provided, but it errored out with the message `npm ERR! Refusing to install @panzoom/panzoom as a dependency of itself`...)

For now I'm using a 2.x.x release that contains the `.js` files, but I can see that these are really out of date.

**Comment by chsami** [comment]
If you want to include it as a script tag, here is the url for the latest version: 

https://cdn.jsdelivr.net/npm/@panzoom/panzoom@4.3.2/dist/panzoom.min.js

As for the npm...

You can't npm install inside the panzoom project. The package.json name property already contains the name @panzoom/panzoom. 

Npm install works for me in any other project not named @panzoom/panzoom

**Comment by jenlampton** [comment]
Thanks so much! 
I appreciate the quick reply :)
