### ISSUE TITLE
Contain and big image seems to break something

### ISSUE THREAD

**Issue by ptheofan** [timmywil/panzoom#539]
Here's an example with an image 5200x3800. The goal was to pan-zoom but always ensure edges of the image are not outside the container area. As an example, imagine it contains a "game-board" and players can zoom in-out and pan but they should not be able to pan away (example, top-left of the image can be below zero but never above zero)

1. When using all the listed options, nothing works.
1. When using only the contain zoom buttons work, panning appears to be broken and contain is not honoured. 

**Code Here**
https://jsbin.com/cerekok/edit?js,output

Am I doing something wrong or is there an issue with large images?

**Comment by brgrz** [comment]
Can confirm this happens in my case too

**Comment by timmywil** [comment]
2bdc5591cca0f29eaa530c92279e9ea9e3fa336c

**Comment by timmywil** [comment]
Thanks for this issue. I think I have this fixed now. brgrz is right that `invert` is not a valid value for `contain`, even though it was in a very old version. The only values now are `inside` and `outside`.

I also think you may have been running into some timing issues, brgrz. Having to set height through the whole DOM tree should not be necessary, but that could affect height values during some race conditions. It probably has something to do with [the async nature of Panzoom](https://github.com/timmywil/panzoom#a-note-on-the-async-nature-of-panzoom).

All that said, please try the latest version if you get the chance and let me know how it goes.
