### ISSUE TITLE
Disabling drag when mouse is over a div that sits above the map.

### ISSUE THREAD

**Issue by ClintCWC** [timmywil/panzoom#540]
Hi Timmy

you recently described how to disable zoom with mouse when the pointer is over a different window that sits in front of the panzoom element. I used this and it works when i am wanting to scroll the target window and not the panzoom element.

i am having an issue when dragging the scroll bar of the target window, it does scroll the window but it also pans the map behind it. Can you help?

many thanks.

**Comment by timmywil** [comment]
Thanks for opening an issue. I think I would need a test case to help you sort this out.

Can you put together something (preferably with as little code as possible) from codepen.io or jsbin.com?

Closing for now.
