### ISSUE TITLE
Disabling drag when mouse is over a div that sits above the zoompan element

### ISSUE THREAD

**Issue by ClintCWC** [timmywil/panzoom#541]
Hi Timmy (duplicate with example)

[https://jsfiddle.net/wxgvqkan/6/](https://jsfiddle.net/wxgvqkan/6/)
on the example i cant scroll the popup window using the scroll bars (i can with the mouse wheel)

you recently described how to disable zoom with mouse when the pointer is over a different window that sits in front of the panzoom element. I used this and it works when i am wanting to scroll the target window and not the panzoom element.

i am having an issue when dragging the scroll bar of the target window, it does scroll the window but it also pans the map behind it. Can you help?

many thanks.

**Comment by timmywil** [comment]
Thanks for opening an issue. Is this the behavior you're looking for?

https://jsfiddle.net/timmywil/5n10Lx2q/1/

**Comment by ClintCWC** [comment]
Hi Timmy, Unfortunately i need the the popup div to be part of the panzoom element so it pans and zooms with the rest of the image.

i just dont want it to pan when the mouse drag is on the popup scroll bar.
