### ISSUE TITLE
 Disabling drag when mouse is over a div that sits above the zoompan element

### ISSUE THREAD

**Issue by ClintCWC** [timmywil/panzoom#542]
Hi Timmy (duplicate with example)
i see you have moved the popup out of the panzoom element as a fix

Unfortunately i need the the popup div to be part of the panzoom element so it pans and zooms with the rest of the image.
i just dont want it to pan when the mouse drag is on the popup scroll bar.

https://jsfiddle.net/wxgvqkan/6/
on the example i cant scroll the popup window using the scroll bars (i can with the mouse wheel)

you recently described how to disable zoom with mouse when the pointer is over a different window that sits in front of the panzoom element. I used this and it works when i am wanting to scroll the target window and not the panzoom element.

i am having an issue when dragging the scroll bar of the target window, it does scroll the window but it also pans the map behind it. Can you help?

many thanks.

**Comment by timmywil** [comment]
Ok, I'm not seeing anything move when dragging the scroll bar. Perhaps the behavior is browser-specific? I'm using Chrome. However, you should be able to disable panning on the scroll event. If it's okay that the popup doesn't initiate panning (but still pans with the panzoom element), you can add it to excluded elements.
