### ISSUE TITLE
How can I make Panzoom work for multiple images featured each in a single modal window.

### ISSUE THREAD

**Issue by akimo13** [timmywil/panzoom#545]
[Here is some code ](https://codepen.io/akimo13/pen/gOLaXyL) where I'm using multiple modal windows each one featuring a single image. I need Panzoom to work for every single image, so far it works only for the first one. Any suggestions on how I should modify my code?

**Comment by timmywil** [comment]
Thanks for opening an issue. I modified your codepen. Hope this works for you too. https://codepen.io/timmywil/pen/qBqOoRQ

**Comment by akimo13** [comment]
Oh my! Thank you so much for helping me out! I guess I have to do some studying.
