### ISSUE TITLE
Feature: Use a different cursor while panning is active

### ISSUE THREAD

**Issue by m-ober** [timmywil/panzoom#546]
**What problem does this feature solve?**
Using the `cursor` option, a custom cursor can be set for panable elements. When pressing the mouse button to start panning, no feedback to the user is given.

**Describe the solution you'd like**
I would like an additional `panCursor` (or similar) option, so I can set `{ cursor: "grab", panCursor: "grabbing" }` to give more feedback to the user.

**Describe alternatives you've considered**
I guess this could also be solved using the provided events, although it would be a lot of boilerplate for such a "small" feature.

**Additional context**
None.

**Comment by timmywil** [comment]
Thanks for opening an issue. The feature you're describing is more common with drag & drop libraries. That said, we can consider this given enough interest.
