### ISSUE TITLE
Blurry svg when zoomed in on Safari and iOS devices using pinch.

### ISSUE THREAD

**Issue by Madvatar** [timmywil/panzoom#548]
### Describe the bug

Hi! I'm trying to use the version 4.3.2 of panZoom in a setup where I zoom an SVG image. However when using Safari on a Mac or iOS Safari browser, the svg becomes blurry when zooming in using pinch gestures. I have googled around and found related issues reported here, but most of those refer to the old panZoom library, and most of them were solved by using various hacks.

In an earlier version of the library I know people used things like:
			// This part 'nudges' the browser so the svg is sharpened in Chrome(mobile).
			onEnd: function (e, instance, matrix, changed) {
				var sel = this;
				sel.style.display = 'none';
				sel.offsetHeight;
				sel.style.display = '';
			}
But is that an option still? And if so, how would you add that to the new implementation?

Is there a robust solution to this in the rewritten version of the library or is my setup bad in some way?

I'd appreciate some advice :)

### Your environment

- Version of panzoom: PanZoom 4.3.2
- Browser and browser version: Safari on Mac and Safari on iOS device

### Expected behavior

The svg should not become blurry when zoomed.

### Actual behavior

The svg gets blurry when zooming in using pinch gestures.

**Comment by timmywil** [comment]
Thanks for opening an issue. This is more a Safari bug then an issue with Panzoom. There were several solutions, including disabling (and enabling) hardware acceleration. Accessing `offsetHeight` isn't the most performant thing, but does trigger a reflow, which may force Safari to sharpen it up. `onEnd` would be equivalent to the "panzoomend" event in the current version. Let me know if you find a hack that works for you and I will consider adding it to Panzoom, but I can't guarantee a particular solution will work for all cases. The ultimate solution would be for Safari to fix it.

**Comment by jasperf** [comment]
Looking into this as well now. Have an svg to create a grid with lines

```html
<svg v-if="showGrid" id="grid-svg" :width="gridWidth" :height="gridHeight" xmlns="http://www.w3.org/2000/svg">
                <defs>
                    <pattern id="grid-pattern" :width="cellSize" :height="cellSize" patternUnits="userSpaceOnUse" viewBox="0 0 45 45">
                        <path d="M 80 0 L 0 0 0 80" fill="none" stroke="#CCC" stroke-width="1"/>
                    </pattern>
                    <pattern id="grid-line" :width="cellSize * 20" :height="cellSize * 20" patternUnits="userSpaceOnUse" viewBox="0 0 45 45">
                    <path stroke-dasharray="1" d="M 0 0 L 0 125" stoke-width="1" stroke="rgba(204, 204, 204, 0.6)"/>
                    <path stroke-dasharray="1" d="M 0 0 L 125 0" stoke-width="1" stroke="rgba(204, 204, 204, 0.6)"/>
                    </pattern>
                </defs>
                <rect width="100%" height="100%" fill="url(#grid-pattern)" />
                <rect width="100%" height="100%" fill="url(#grid-line)" />
            </svg>
```

 and zooming in the lines become blurry on Safari and Safari only. Using `shape-rendering="geometricPrecision "` on the `path or `pattern` does not really seem to help. So looking into ways to make Safari play ball here and display lines as clear as Chrome and Firefox do. Would love to hear if @Madvatar found a solution for this issue.

**Comment by jasperf** [comment]
Seems using a MBP 2015 lines do display well on Safari and with attached 4K screen using 3200 resolution also. On the older Mac Mini 2012 zoom causes blurry SVG lines. So perhaps Safari applies other rules based on hardware somehow. Either that or the hardware causes display issues that the above hack may remedy. Issues that are not present on Chrome and Firefox.
