### ISSUE TITLE
Better zoom animations

### ISSUE THREAD

**Issue by Ninili** [timmywil/panzoom#550]
**What problem does this feature solve?**

The zoom animation looks very jerky. That may be because the transform of the element is defined as "scale" and "transform" and not as matrices.

**Describe the solution you'd like**

Using matrix transforms would make the animations smooth and not go astray inbetween.
I've seen this code actually exists for SVG elements already. And in the demo, they zoom as expected.
Would be cool that matrices would be enabled when animation is set to true

**Describe alternatives you've considered**

Until then I will use a custom "setTransform" function

**Additional context**

**Comment by timmywil** [comment]
Thanks for opening an issue. However, using `matrix()` directly will not affect performance. `scale` and `translate` are simple shortcut functions that get translated to a 3d matrix. `matrix()` itself is a shortcut function that gets translated by the browser to its own representation of a 3d matrix. If the animations are jerky, there would be another reason. I haven't seen jerky animations myself, but there are many things that can affect performance. Using transition and transform ensures that the animation takes advantage of hardware-acceleration and improves performance for the majority of users, but slow devices, overloaded CPUs, blocked threads, and other issues not controlled by Panzoom could make an animation appear janky.

**Comment by Ninili** [comment]
Sorry for not being clear about the issue. Maybe I choose the wrong words, because I'm not a native speaker. Maybe "quirky" would fit it better than "jerky", because it has nothing to do with CPU or performance, but rather with the way the object gets transitioned. I made a Pen for that to illustrate it:
https://codepen.io/ninili/pen/6d88950fd658c370aae5c38470197e8c
There are two squares, transitioning from the exact starting and ending transitions relative to their container.
On the left, "scale() translate()" gets transitioned (like when using HTML-Elements in Panzoom), on the right matrices are used instead.

And don't get me wrong, your library has saved me a lot of time but this also has been a real issue to me when zooming faster into bigger objects with animations enabled, it always felt quite "wobbly".

**Comment by timmywil** [comment]
I see what you're getting at. Using matrix will change the animation because `matrix()` is setting more than the scale and translate parts of the matrix. I prefer to leave those alone and let the browser decide what to set during transitions. That said, you can override this using the [setTransform option](https://github.com/timmywil/panzoom#settransform).
