### ISSUE TITLE
Download screenshot of a zoomed video element or draggable video stream image. I am using panzoom library for zoom and dragFeature: 

### ISSUE THREAD

**Issue by Avinash-2020** [timmywil/panzoom#551]
I need to download the screenshot of the video element after I am zooming or after dragged. I am using below code for downloading screenshot but not getting exact zoomed image

Code I am using: 
const video = this.videoPlayer.nativeElement;
   let w: number, h: number, ratio: number;
   ratio = video.videoWidth / video.videoHeight;
   w = video.videoWidth - 100;
   h = w / ratio;
   canvasElement.width = video.videoWidth;
   canvasElement.height = video.videoHeight;
     const context = canvasElement.getContext('2d');
     context.scale(this.scaleZoom, this.scaleZoom);
     context.translate(this.xAxis, this.yAxis);
     const context = canvasElement.getContext('2d');
     context.drawImage(video, 0, 0, video.videoWidth, video.videoHeight);
   const link = document.createElement('a');
   this.snapshotName = 'PatientScreenImage';
   this.userImageType = 'PNG';
   link.setAttribute('download', this.snapshotName + '.' + this.userImageType);
   const dataURL = canvasElement.toDataURL();
   link.href = dataURL;
   document.body.appendChild(link);
   link.click();

**Comment by timmywil** [comment]
Thanks for opening an issue. I believe screenshots are out of scope for this library. I would expect there are libraries out there that are dedicated to helping capture screenshots in the browser.
