### ISSUE TITLE
Feature use - Interactive map with fixed positioned elements

### ISSUE THREAD

**Issue by alastair-freestone** [timmywil/panzoom#552]
We are currently in the process of developing an interactive map for a local museum.

Is it possible to use panzoom to create an interactive map, where some elements like markers are positioned but then don't scale when the rest is zoomed, but still remain in the exact location?

Some elements will appear on rollover and some bits will have animated characters.

Something similar to https://rio2016interactivemap.com/

Any suggestions would be appreciated.

**Comment by timmywil** [comment]
Thanks for opening an issue. The tooltips could be placed outside the panzoom element and absolutely positioned on hover. While this is an advanced case that may require some trial and error, I think all of the tools are there.

**Comment by alexryans** [comment]
@alastair-freestone I was wondering if you managed to solve this using Panzoom and, if so, how you achieved it? We currently have the exact same request for our client - interactive map for a local museum! - and are trying to create something with "hotspots"which a user can click to show an off-canvas container w/ more information, or hover over to show a tooltip with a summary of information. Ideally, we'd like a user to be able to pan and zoom the map w/o the scale of the tooltips increasing, and remaining in the same location.

Thanks!

**Comment by alastair-freestone** [comment]
@alexryans In the end we went with a different library as the project developed into a much larger project. We used imgViewer2 >> https://github.com/waynegm/imgViewer2

**Comment by alexryans** [comment]
Great, thanks for your quick reply!
