### ISSUE TITLE
Feature: set origin (put image in upper left corner) without breaking focal point zooming

### ISSUE THREAD

**Issue by dermoritz** [timmywil/panzoom#555]
**What problem does this feature solve?**
My use case is to display big images up to 100MP on 100% of the available screen. The default origin 50%, 50% moves the picture away and thus creates big white border. Setting origin to '0 0' solves this but breaks focal zoom (as documented).

**Describe the solution you'd like**
A way to set origin '0 0' or another way to put the image in the upper left corner with focal zoom feature.

**Describe alternatives you've considered**
I tried to play around with "contain". Contain inside seem to do nothing in regards of image position but panning stops working (i guess due to container size + transform origin 50). "outside" seem to have a very odd behaviour making the image jump on any interaction (initially loaded half split in the upper left corner and it jumps away on pan or zoom)

**Additional context**
I am relatively new to javascript development so their might be an easy way i didn't saw. My first step would just be to render the image as the browser would do (upper left corner, zoomed out to fit screen), from there i want focal zoom on mouse down to cursor position to 100% and pan as long mouse down. on mouse button release back to fit screen.

**Comment by dermoritz** [comment]
I found a way:

`  imageContainerElement = document.getElementById("image");
  imageElement = imageContainerElement.getElementsByTagName("img")[0];
    panzoom = Panzoom(imageContainerElement,{
      startScale:zoomFactorToFit(),
      startX:-imageElement.clientWidth * 0.5,
      startY:-imageElement.clientHeight * 0.5
  });

`
My request would be to be able to set default of origin to be 0 0 as for svg.

**Comment by timmywil** [comment]
Thanks for opening an issue. It should be unnecessary to change the transform origin to do this. The initial position of the image is determined by good old CSS. That said, if you can make a small example on https://codepen.io or https://jsbin.com or https://jsfiddle.net, I can help with the code.

Closing as we should be able to figure it out without adding a feature.

**Comment by dermoritz** [comment]
i put the code here:
https://jsbin.com/cukamavaja/edit?output
it is really your default code - my problem is: how to put the image in the upper left corner (the same position as it would have without Panzoom).
I achieved this now by setting startX and startY but this is really ugly:

```
function calculateXYstart(){
  let result = {x: null, y:null};
  if(imageElement.clientHeight>imageElement.clientWidth){
    result.x = -imageElement.clientWidth * 0.5;
    result.y = imageContainerElement.clientHeight-imageElement.clientHeight * 0.5;
  } else {
    result.x = imageContainerElement.clientWidth-imageElement.clientWidth * 0.5;
    result.y = -imageElement.clientHeight * 0.5;
  }
  return result;
}
```
This puts the image where i want to have it. Without the if either it is cut left (if landscape) or cut top (if portrait). I am sure there must be an easier way.
My code also did some other stuff (every thing works):
- initially zoom to fit screen / container
- pan is disabled
- pointer down zoom to pointer with scale factor 1 (my images are always much bigger than screen)
- pointer down also enable pan and lets you pan, here i need to calculate the pan my self - with default panning let the picture jump - i guess due some wrong offset?
- pointer up: panzoom.reset() (really helpful function here)

This is how i implemented pan (global pan is disabled):
```
function pan(event) {
  if (zoomedIn) {
    let currentPan = panzoom.getPan();
    panzoom.pan(
      currentPan.x - (pointerPosition.x - event.x),
      currentPan.y - (pointerPosition.y - event.y),
      { force: true }
    );
  }
  pointerPosition.x = event.x;
  pointerPosition.y = event.y;
}
```
here i put everything together: https://jsbin.com/duquraj/edit?html,js,output

i just noticed that in jsbin the picture is cut on top :-(. it looks as expected in Firefox but has still a bigger white border in chrome. So help to make it fit in upper left corner or on to with center align woul be appreciated much.
