### ISSUE TITLE
jquery integration, a need for old options - please shed some light

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [timmywil/panzoom#556]
_initial question is no longer valid, please read my comment below_ :P

**Comment by Melmoth-the-Wanderer** [comment]
I just realized that version 4 brought us totally new and different panzoom, jQuery free. This is both great and scary news to me.

It is greate since I'll need to migrate my legacy feature to angular, and I'm hoping I could use panzoom there with no need for jQuery.

On the other hand, before the migration happend, I need to maintain my legacy feature. In the notes of 4.0.0 release it says that the new package "can still be integrated as a jQuery plugin". Did you happen to have an example of this kind of integration? More specifically, do you know is it still possible to develop old $set functionality on top of this new panzoom library? Where do I start? Any help would be appreciated.

**Comment by timmywil** [comment]
Thanks for opening an issue. Dropping jQuery had several advantages, but ultimately the features that were possible without jQuery were still possible with jQuery. That said, rewriting the library from the ground up allowed me to address some longstanding issues from the beginning, which had some implications on the new architecture. It was still possible to address those issues in the old plugin, but the code probably wouldn't have been as clean. I also wanted a version of Panzoom with zero dependencies and a small footprint.

Anyway, to answer the main question here. If you'd like to continue using the new library with jQuery, it should relatively easy. Here's how you might add a plugin to call Panzoom on an existing jQuery collection:

```js
$.fn.panzoom = function(options) {
  return this.each(function() { Panzoom(this, options); });
}
```

Or, just call Panzoom on an element from a jQuery collection:

```js
const panzoom = Panzoom($collection[0])
```

To replicate the `$set` option, you should be able to use the [`setTransform` option](https://github.com/timmywil/panzoom#settransform) instead to manipulate the elements on which the transform is set. Here's another issue with an example that had a similar question: https://github.com/timmywil/panzoom/issues/532
