### ISSUE TITLE
[Question] How postion image automatically after zooming

### ISSUE THREAD

**Issue by dermoritz** [timmywil/panzoom#557]
Sorry to bother again. I added answer to closed https://github.com/timmywil/panzoom/issues/555 but now i could make or more precise question i guess.
It is regarding this code: https://jsbin.com/muhokoh/edit?html,js,output

My main idea is to zoom out to fit the screen using pan zoom. Because of usage of tranform it is zoomed out around origin at "50% 50%" and thus the image centre didn't moved but it "moves" also away from top left corner as you see in the example.

The question is: how to compensate this.

I tried:
 In my real code the zoom factor is calculated based on available screen. In the jsbin example i used 0.1 and calculated x offset, y offset this way:
startX = -(imageElement.naturalWidth - imageElement.naturalWidth*zoomfactor)/2
for image in jsbin it is: - (6786 - 6786*0.1)/2 = -3053.7
startY = -(imageElement.naturalHeight - imageElement.naturalHeight*zoomfactor)/2;
-(4524 - 4524 * 0.1)/2 = -2035.8

As you see in jsbin the numbers are not correctly applied or not correct at all.

Is there a better way? I am currently zooming to factor 1 on pointer down to pointer position with paning in zoomed in state (works great with Panzoom). On pointer up i am doing Panzoom.reset() - to get back to initial state regarding zoom and position.

I am also not sure if my structure is good. I noticed that the image container is of course shrinked with same factor as image. But on the other hand i need a container with visible size to calculate the zoom factor.

Thanks in advance

**Comment by timmywil** [comment]
Thanks for opening an issue. I noticed your answer, but haven't had time to reply.

I put together a small example to show you you can rely on CSS to center things without needing to alter the transform in Panzoom. https://jsbin.com/pexidit/edit?html,css,js,output

I don't know if this exactly what you were looking for, but hopefully it will at least point you in the right direction. :)

**Comment by dermoritz** [comment]
i don't see the image in you jsbin - i only see the border:
![grafik](https://user-images.githubusercontent.com/1814196/115668677-b2a38b00-a347-11eb-879c-d64c7791c6aa.png)

The main point is: fill the available space as best as possible with the image as long as zoom * size is bigger than available screen.

**Comment by timmywil** [comment]
yea, the image was loading slowly for me sometimes as well. but the functionality should be there. The panzoom element stays centered as you zoom.
