### ISSUE TITLE
Raphael drag events are disabled if disablePan is true.

### ISSUE THREAD

**Issue by bangoo** [timmywil/panzoom#559]
If I **setdisablePan** to **true** it also disables raphael dragging events. 
On elem.drag() nothing happens.
Is it possible to disable panning in the library and allow raphael dragging events?

**Comment by timmywil** [comment]
Thanks for opening an issue. It can get complicated sharing pointer events with other libraries, but have a look at the [touchAction option](https://github.com/timmywil/panzoom#touchaction) and the [handleStartEvent option](https://github.com/timmywil/panzoom#handlestartevent). That said, it's hard to say exactly what is the issue without a test case.

**Comment by bangoo** [comment]
[The codepen example: ](https://codepen.io/bangoo/pen/yLgbzPq)
If you enable the panzoom code dragging (mat.drag(dragmove, dragstart, dragend);
) stops.
Is it possible to disable pan and use Raphael dragging with panzoom?
