### ISSUE TITLE
Feature: Setting for contain, so that panzoom object pans/stays inside of its container at all times

### ISSUE THREAD

**Issue by PrinceOfAbyss** [timmywil/panzoom#562]
I want to combine Panzoom with [Slick](https://github.com/kenwheeler/slick/) slider. I've created this [JSFiddle](https://jsfiddle.net/princeofabyss/0ydjcge2/) so that you get right away what I want to achieve. Basically if I have to say two words about it:

1. When the page loads, Panzoom will be turned off (top-right corner indication).
2. Upon clicking on the top-right corner, where you set up the zoom factor (1.1x, 1.8x, etc) Panzoom will need to zoom the active slide to the factor selected.
3. Once you press the top-middle "refresh-like" button, the next slide will load, set to its natural dimensions (not zoomed at all).

Up to here, I've achieved everything I've described (though I'm a bit confused about the - maybe indirect - way I used, having to set the panOnlyWhenZoomed setting to true. According to the readme, the .destroy() method should have sufficed, but this wasn't the case - unless I understood something wrong...

What I haven't been able to achieve is to prohibit the zoomed slide to move outside of its container boundaries. I mean, at any time the zoomed slide should be able to pan within its container. Afterall the image, when zoomed, grows bigger than its container, while the container stays the same, so panning is reasonable to happen, but it should happen in a way that no red container background ever gets visible (I painted it red exactly so that you get what I mean)... Any idea how this could be achieved? Thanks in advance.

**Comment by PrinceOfAbyss** [comment]
Basically what I need is included in the [Demo](https://timmywil.com/panzoom/demo) page, It's titled as [Containment within the parent](https://timmywil.com/panzoom/demo/#Containment%20within%20the%20parent), but I think it should actually be titled as Containment outside the parent. Even the anchor is wrong (both examples have the same anchor, while the first example uses _contain: 'inside'_ and the second _contain: 'outside'_)...

Anyway, I followed the second example's code, but I don't get the presented functionality. As soon as I choose a zooming factor the slider disappears (probably goes outside the canvas)... Am I doing something wrong, or is the example wrong? I'm totally lost...

**Comment by PrinceOfAbyss** [comment]
Additionally, I want to totally disable pinch zoom in/out (through a mobile I mean), but I can't achieve that either. Is this a bug maybe?

**Comment by timmywil** [comment]
Thanks for opening an issue. Is this what you're after? https://jsfiddle.net/timmywil/50pve89k/1/

Containment works relative to parent elements, so I called Panzoom on the img rather than the div. That seems to fix the containment issue. Also, rather than making a new Panzoom instance every time you press zoom, it's better to cache that instance and reuse it. You could initialize them all up front, but this example initializes Panzoom lazily (i.e. on zoom if not initialized already) and saves Panzoom on the element as a property. You could also use jQuery.data, but this works fine.

Finally, while pinch zooming cannot be turned off separately from other zooming, you can disable all zooming and use the [force option](https://github.com/timmywil/panzoom#force) to zoom on click.

Even if this fiddle isn't exactly what you want, hopefully that at least gets you on the right track.

**Comment by PrinceOfAbyss** [comment]
OMG! The "feature request" question turned out to be a setup support/assistance topic... What's more, with your reply you achieved 99% of what I wanted to achieve! The initial problem was indeed that, out of carelessness, I set my elem to the container rather than the image. Then, as you said, I could reuse panzoom object instead of creating a new one...

One thing I don't understand between your setup and mine, is that you didn't use the _panOnlyWhenZoomed_ propery set to true, and still the image doesn't pan when magnification factor is set to OFF. I suppose that it doesn't move because its container is the same size as the image, so there is no room for the image to move around? Or is it something else that keeps it from moving? I noticed that in the CSS tab you added the _display: block_ property to the image. What was that for?

Finally, if you have the kindness to help me on achieving that remaining 1% I'd honestly be grateful. That is, I noticed, especially in mobile, that when you move the zoomed image inside its container, the rest of the page also "consumes" some of the movement, and moves up and down a bit... Ideally I'd like to prevent the outside movement of the whole page when you touch inside the container, and then if you need to browse on the outside page you'd have to touch outside the container. Please take a look at the following short video I recorded with my cell phone to better understand what I mean: https://www.youtube.com/watch?v=0SDXkTfS6bc Thank you **so much** for everything!

**Comment by PrinceOfAbyss** [comment]
Can you please help me with this [JSfiddle](https://jsfiddle.net/princeofabyss/92necaps/4/) a bit? I noticed that it does a small "hiccup" between the first and second zoom in, like a small back and forth in its pan... It's even noticeable in the CSS, in the translate property. First zoomin it's set to some floats, then both x and y are set to 0, and they stay 0 for any zoom-in after that...

I tried to use the setTransform property that you use for more complex transformations (rotations etc), but it kept producing errors...

The JSfiddle I mentioned at the beginning of thisnpost is ready to expect yoyr magic touch, I've set up most of it... Thanks in advance!
