### ISSUE TITLE
Feature: Zoom on trackpad pinch

### ISSUE THREAD

**Issue by fabiofidanza** [timmywil/panzoom#563]
Thanks for this great library.
Is there a way to enable zooming on a multitouch trackpad? (e.g. Macbook Pro / Magic Trackpad).

Thanks.

**Comment by timmywil** [comment]
Thanks for opening an issue. But, if it's not working already it means the trackpad is not sending multiple pointer events. That's not necessarily a bad thing. Trackpads have several gestures that can have special meaning and don't necessarily correlate with the number of touches. For instance, you scroll with 2 fingers, but that doesn't trigger 2 touch events. It triggers a scroll. I don't have a trackpad to test myself, but I imagine the pinch gesture is doing something similar, in that it doesn't necessarily translate to the events you may expect. I would have thought it was sending a `wheel` event and that [zoomWithWheel](https://github.com/timmywil/panzoom#zoomwithwheel) would just work. But again, I don't have a way to test myself.

I'd first check what event it is sending and we can discuss further, but the tools to support this may already exist in Panzoom without changes.

**Comment by fabiofidanza** [comment]
Thanks @timmywil, this points to a good direction — I'll investigate which events are triggered by Apple Trackpads that might be chained to the behavior that panzoom already offers.
Will report back any finding here.

**Comment by jdjoshuadavison** [comment]
Most browsers except Safari send a pinch gesture as a wheel event **with the ctrl key set to true**.
As such, enabling zoomWithWheel will enable users to pinch to zoom.
But what if you only want to zoom with pinch and not with the wheel? You can do this by checking the state of the ctrl key when the wheel event is triggered.

Simply:
```
    parent.addEventListener('wheel', function(e) {
        if (!e.ctrlKey) return;
        panzoom.zoomWithWheel(e);
    });
```

To support pinch to zoom in Safari, you would have to use Apple's own Gesture Event API. But beware, the Safari browser already has actions tied to the pinch gesture (when you pinch to zoom out it shows you an overview of all of your tabs). As such, it may be a bad idea to implement your own actions on the pinch event as there is likely to be conflicts and inconsistent behaviour.

**Comment by jdjoshuadavison** [comment]
Following my previous comment, I made an attempt at adding trackpad pinch to zoom support to Safari using Apple's Gesture Event API. I got it working, but as I suspected, it conflicts with the browsers own pinch actions and is unreliable. I really don't recommend doing this, but thought I'd share what I tried in case anyone wants to give it a go themselves or knows of a way to resolve the conflict.

```
    var oldScale = 1;
    if (typeof GestureEvent !== 'undefined' && typeof TouchEvent === 'undefined') {
        parent.addEventListener('gesturechange', function(e) {
            e.deltaX = 0;
            e.deltaY = e.scale - oldScale;
            panzoom.zoomWithWheel(e);
            oldScale = e.scale;
        });
    }
```
