### ISSUE TITLE
startScale and startX ignored when disableZoom and disablePan set to true

### ISSUE THREAD

**Issue by jdjoshuadavison** [timmywil/panzoom#573]
### Describe the bug

When initiating panzoom, I have set a startScale and startX. These work fine. Until you also want to disable panning and zooming. If you set disablePan and disableZoom when you call the `Panzoom()` method, `startScale` and `startX` are ignored. I've also tried using `setOptions` to set disablePan and disableZoom _after_ calling `Panzoom()` with `startScale` and `startX` - this fixes the problem with scaling, but not with panning.

### Your environment

- Version of panzoom: 4.4.0
- Browser and browser version: Chrome 91.0.4472.114 (Official Build) (x86_64)

### Expected behaviour

Panzoom objects should start at scale and translation specified by startScale and startX even if disablePan and disableZoom are set to true.

### Actual behaviour

Panzoom objects ignore startScale and startX when disablePan and disableZoom are set to true.

### Steps to reproduce

As described. Demo: https://jsbin.com/joquhey/2/edit?js,output

**Comment by timmywil** [comment]
It does make sense that the start options should disregard the disable options. I can go ahead and fix that. However, one of the examples in the demo is a bit misleading. In the last one, the proper `startX` does get set, but it doesn't look like it because the margin in the CSS only applies to the first image.

**Comment by timmywil** [comment]
Please try the latest commit on `main`.

```shell
$ git clone git@github.com:timmywil/panzoom.git
$ cd panzoom
$ npm install
$ npm run build
```

panzoom.js will then be available in `dist/`

**Comment by jdjoshuadavison** [comment]
> It does make sense that the start options should disregard the disable options. I can go ahead and fix that. However, one of the examples in the demo is a bit misleading. In the last one, the proper `startX` does get set, but it doesn't look like it because the margin in the CSS only applies to the first image.

The final example (example 4) does work, it's the workaround I have been using - I just made a mistake in the paragraph explaining the results of example 4. I've updated the jsbin and the link in the initial report.


> Please try the latest commit on `main`.
> 
> ```shell
> $ git clone git@github.com:timmywil/panzoom.git
> $ cd panzoom
> $ npm install
> $ npm run build
> ```
> 
> panzoom.js will then be available in `dist/`

I will try, thanks.

**Comment by timmywil** [comment]
I tried it in your jsbin just now and it all works. Only thing was the last example needed to wait for the scale to paint before calling pan. See [the note on async](https://github.com/timmywil/panzoom#a-note-on-the-async-nature-of-panzoom).

**Comment by jdjoshuadavison** [comment]
> I tried it in your jsbin just now and it all works. Only thing was the last example needed to wait for the scale to paint before calling pan. See [the note on async](https://github.com/timmywil/panzoom#a-note-on-the-async-nature-of-panzoom).

Can confirm this is now working as expected. Many thanks.
