### ISSUE TITLE
Center image

### ISSUE THREAD

**Issue by rudolphreti** [timmywil/panzoom#574]
Hi,
thank you for this library. It is really great :) Could you take a look at it?
https://stackoverflow.com/questions/68115021/panzoom-library-and-filling-a-div-with-a-centered-image
I've been struggling with this for a few days. It would be useful to have a feature in the library that would allow you to center elements easily. 
Best regards,
Reti

**Comment by timmywil** [comment]
Thanks for opening an issue. However, centering can be done with CSS or with the [startX and startY options](https://github.com/timmywil/panzoom#startx) for more advanced use cases. It can be almost impossible to predict the best way to center Panzoom content for every use case.

In your case, the "zoom-area" elements have the same width as their containers, but the images inside those area elements are left-aligned and have much more width than their parents. That means that the default behavior for a `center` option would likely center the area elements and the images would still look off-center. So, I think you can accomplish what you're looking for with CSS.

Hope this helps: https://codepen.io/timmywil/pen/NWjWjNp

**Comment by rudolphreti** [comment]
Thank you so much and I wish you all the best!

**Comment by a4992214** [comment]
is it startX/startY - or is it initialX/initialY - I'm looking at https://unpkg.com/panzoom@9.4.0/dist/panzoom.min.js and I see initialX/Y... am I using the wrong version?
