### ISSUE TITLE
Transform Updates

### ISSUE THREAD

**Issue by moklick** [timmywil/panzoom#575]
Hey! Thanks for this great lib :) I would like to use it for our React Flow project. Everything seems fine but I don't understand the transform updates. In this [codesandbox](https://codesandbox.io/s/youthful-ride-wnehb?file=/src/index.js:383-420) you can check the logs of the custom `setTransform` function. When I do these function calls:

```js
panzoom.pan(10, 10);
panzoom.zoom(2);
```

I get these transform updates:

```
{scale: 1, x: 0, y: 0}
{scale: 1, x: 10, y: 10}
{scale: 2, x: 10, y: 10}
{scale: 2, x: 0, y: 0}
```

I have two questions:

1. Why do I get an additional transform update with `x:0` and `y:0`
2. Is there a way to combine the pan and zoom updates so that I only get one transform update?

Thanks in advance!

### Environment

- Version of panzoom: 4.4.1
- Browser and browser version: Chrome  91.0.4472.114

**Comment by timmywil** [comment]
Thanks for opening an issue. This has to do with the async nature of Panzoom.

First of all, there are 2 settings when Panzoom is first initialized. That is, Panzoom uses the `startX`, `startY`, and `startScale` options to set the initial transform. Usually, if you need to immediately set a pan or zoom when initialized, those start options are the way to do it to avoid these async issues. But here's what's happening:

```js
{scale: 1, x: 0, y: 0} // When Panzoom is initialized, the zoom is set first. x and y are unchanged and the startScale is 1. `startX` and `startY` are not yet set because any zoom needs to be painted to properly constrain x and y values. So, those are set in a `setTimeout()` (see last log).
{scale: 1, x: 10, y: 10} // Your pan call
{scale: 2, x: 10, y: 10} // Your zoom call
{scale: 2, x: 0, y: 0} // The async pan call from initialize setting the startX and startY values that was pushed to the end of the stack.
```

So, there are a couple solutions.

Either this:

```js
Panzoom(elem, {
  startX: 10,
  startY: 10,
  startScale: 2,
  setTransform: (elem, { x, y, scale }) => {
    console.log("update", { scale, x, y });

    elem.style.transform = `scale(${scale}) translate(${x}px, ${y}px)`;
  }
});
```

which will still produce 2 logs. One to paint the scale, then one to set the pan at the end of the stack.

Or this

```js
const panzoom = Panzoom(elem, {
  setTransform: (elem, { x, y, scale }) => {
    console.log("update", { scale, x, y });

    elem.style.transform = `scale(${scale}) translate(${x}px, ${y}px)`;
  }
});

setTimeout(() => {
  panzoom.pan(10, 10);
  panzoom.zoom(2);
});
```

which will log this instead:

```
// Panzoom initializing
{scale: 1, x: 0, y: 0}
{scale: 1, x: 0, y: 0}

// manual pan and zoom calls
{scale: 1, x: 10, y: 10}
{scale: 2, x: 10, y: 10}
```

**Comment by moklick** [comment]
Thanks for your help here :)
