### ISSUE TITLE
How can I init panzoom globally?

### ISSUE THREAD

**Issue by YOBA1112** [timmywil/panzoom#576]
Hello, how can I init panzoom globally? I'm trying to implement this plugin to work with flickity.js, so I've forked [this plugin](https://github.com/metafizzy/flickity-fullscreen/blob/master/fullscreen.js) a bit. I have 2 different events on 2 different buttons, and it will work bad(e.g. animations doesn't work, can't destroy panzoom on zoomout event, etc) if I init panzoom twice, like I did for now:
```
proto.inZoom = function() { // This is forked line from flickity-fullscreen.js, line 64
  this._changeZoom( true );
  this.focus();

  const elem = document.querySelector('.is-selected')
  const panzoom = Panzoom(elem, {
    maxScale: 3,
    minScale: 1,
    panOnlyWhenZoomed: true,
    overflow: 'visible',
    contain: 'outside',
  })
  panzoom.pan(0, 0)
  panzoom.zoom(3, { animate: true})

  this.element.addEventListener('click', panzoom.zoomIn)
};

proto.outZoom = function() {
  this._changeZoom( false );

  const elem = document.querySelector('.is-selected')

  const panzoom = Panzoom(elem, {
    maxScale: 3,
    minScale: 1,
    panOnlyWhenZoomed: true,
    overflow: 'visible',
  })
  panzoom.pan(0, 0)

  this.element.addEventListener('click', panzoom.zoomOut)
};
```
  Related issue:
  #480

**Comment by timmywil** [comment]
Thanks for opening an issue. Panzoom uses  I don't know the details of your environment, but Panzoom does already export a global in non-module environments (through UMD). Add Panzoom via a script tag. Also, native import is now available in modern browsers. That makes global Panzoom less and less necessary as time goes on. You can also use the [demo version](https://github.com/timmywil/panzoom/blob/main/demo/global-panzoom.ts) that exposes a global without the UMD wrapper.

Also, it's best not to remake Panzoom every time and instead save the Panzoom instance on the element for re-use.

```js
const elem = document.querySelector('.is-selected')
const panzoom = elem.panzoom || (elem.panzoom = Panzoom(elem))
```

Hope that helps.

**Comment by YOBA1112** [comment]
Thanks for quick response! I use pure JS, Panzoom is added via script tag from CDN, like so
`<script src="https://cdn.jsdelivr.net/npm/@panzoom/panzoom@4.4.1/dist/panzoom.min.js"></script>`
When I,m trying to add this outside of function scope:
```
  const elem = document.querySelector('.is-selected')
  const panzoom = Panzoom(elem, {
    maxScale: 3,
    minScale: 1,
    panOnlyWhenZoomed: true,
    overflow: 'visible',
    contain: 'outside',
  })
```
I get this error:
`Uncaught ReferenceError: Panzoom is not defined`

**Comment by timmywil** [comment]
I would need more context to help debug, but I can confirm Panzoom is adding the global in environments where `define` and `module` are not present, which should be true when adding Panzoom via a script tag, unless you are using webpack or some equivalent bundler on html, which might bundle the scripts and replace the script tags. Aside from that, you might just need to make sure Panzoom has loaded before flickity. Could be a race condition of some kind.

**Comment by YOBA1112** [comment]
I've made [this fiddle](https://jsfiddle.net/th8b5upL/3/), which is copy of my current code, hope this can make a better perception of my problem.

**Comment by timmywil** [comment]
Panzoom seemed to already be available globally in your fiddle. However, since you are using UMD, I suggest adding Panzoom as one of your dependencies.

https://jsfiddle.net/timmywil/1jxgak02/9/

I went ahead and edited your zoom functions as well to fit what I think you're going for.

**Comment by YOBA1112** [comment]
Thanks for the help! I managed to fix this problem by creating function which initializes panzoom. See [this fiddle](https://jsfiddle.net/t6am5ver/). I will update this comment with new fiddle that got all functions that I want(like destroying panzoom after slide changed), once I will do it.
