### ISSUE TITLE
Feature: contain: 'outside', but allow the image to fit the container?

### ISSUE THREAD

**Issue by hillin** [timmywil/panzoom#577]
It's a little bit difficult to describe, so I got no luck while looking for an existing issue. Sorry if this is a duplicate.

Basically, I'd like to have the `outside` contain mode, but allow the image to be zoomed out to fit in the container (like css `object-fit: contain`). The image is not allowed to be further zoomed out. When the image is smaller than the container, it should be center aligned both horizontally and vertically.

E.g. if the container is 100x100 px, the image is 400x200px, it can be zoomed out by a factor of 0.25, which makes its visual size 100x50 px. It will be as wide as the container, and vertically center-aligned.

**Comment by timmywil** [comment]
Thanks for opening an issue. This is sort of like `contain: outside` until the element reaches it's minimum amount, then turning off the contain option and just setting a maxScale that sizes the image equivalent to 100x50. It can be accomplished now, tho admittedly not as simply if there were some option that could accomplish this. That said, I'm not sure exactly what that option would look like. Maybe some kind of compliment to `contain: outside` that only enforces the contain for one axis.

Regardless, thank you for the suggestion and I'll go ahead and put this in the [feature request pipeline](https://github.com/timmywil/panzoom/blob/main/.github/CONTRIBUTING.md#feature-requests).

**Comment by hillin** [comment]
Thanks. This is actually the default (and maybe the only) behavior of many image viewer apps, like the one integrated in Windows 10. 

I'm thinking of adding a new contain mode `contain: outside-fit`, although I can imagine that the implementation will extend the scope of the `contain` option.

**Comment by mythjuha** [comment]
Sounds the same as #504
