### ISSUE TITLE
Contain: "outside" wrong transformation

### ISSUE THREAD

**Issue by YOBA1112** [timmywil/panzoom#579]
Hello, I'm trying to zoom inside [flickity-fullscreen.js](https://github.com/metafizzy/flickity-fullscreen/blob/28b48093ea0a671dee7a0c629b987452ebac672f/fullscreen.js), but when I'm using contain: "outside" option - it returns wrong transformation when in fullscreen mode.

Steps to reproduce:
1. Maximize the viewport
2. Open fullscreen
3. Zoom in, then zoom out
4. You can see that transformation is wrong(it's either scale(1._some value_) instead of 1, either translate is (0, _some value_) instead of (0,0) )
5. Comment the line with contain: "outside"(line 72) and reproduce the steps above
6. Transformation is correct now, but I can't use "contain" option, obviously

Test case: [fiddle](https://jsfiddle.net/Ls6p2r4w/)

**Comment by timmywil** [comment]
Thanks for opening an issue. This is because you're calling `pan(0, 0)` before zooming out so the contain calculations are based on the larger scale. See https://jsfiddle.net/timmywil/t6zcmn23/2/
