### ISSUE TITLE
Feature: Promise based API

### ISSUE THREAD

**Issue by viseshrp** [timmywil/panzoom#587]
Firstly, thanks for this amazing library. We use this a lot at work for our day-to-day pan/zoom needs. Excellent work!

**What problem does this feature solve?**
To solve the async problems associated with Panzoom, we have to do this:
```
panzoom.zoom(2)
setTimeout(() => panzoom.pan(100, 100))
```
which is not ideal. I cannot do `n` things in sequence.

**Describe the solution you'd like**
```
panzoom.zoom(2).then(() => panzoom.pan(100, 100))
```
Much cleaner and predictable.

**Comment by benjamincburns** [comment]
@timmywil doesn't the [transitioncancel event](https://developer.mozilla.org/en-US/docs/Web/API/Element/transitioncancel_event) address the concern you raised?
