### ISSUE TITLE
"panzoompan" fires when not zoomed and panOnlyWhenZoomed is true

### ISSUE THREAD

**Issue by viseshrp** [timmywil/panzoom#588]
### Describe the bug

Set panOnlyWhenZoomed to true. Don't zoom but try to pan and drag over image. "panzoompan" will be fired even if not actually panning.

### Your environment

- Version of panzoom: 4.4.2
- Browser and browser version: Chrome Version 94.0.4606.71 (Official Build) (64-bit)

### Expected behavior

Don't fire event if not actually panning.

### Steps to reproduce

https://jsfiddle.net/viseshrp/zjwuLfy8/5/

**Comment by timmywil** [comment]
Thanks for opening an issue. Looks like a bug.
