### ISSUE TITLE
startX, startY ignored when panOnlyWhenZoomed or disablePan set to true and startScale > 1

### ISSUE THREAD

**Issue by viseshrp** [timmywil/panzoom#589]
### Describe the bug

This is similar to issue #573. 
startX, startY are ignored when panOnlyWhenZoomed or disablePan set to true, even when the startScale > 1.

### Your environment

- Version of panzoom  
  4.4.3
- Browser and browser version 
  Chrome Version 94.0.4606.71 (Official Build) (64-bit)

### Expected behavior

startX, startY must be respected as initialization options even though panOnlyWhenZoomed or disablePan is true and startScale is not the default value (is > 1).

### Steps to reproduce

https://jsfiddle.net/viseshrp/zjwuLfy8/16/

**Comment by viseshrp** [comment]
Another note on the fiddle: If you remove panOnlyWhenZoomed in the initialization options, you will see that startX and startY are set properly.

**Comment by viseshrp** [comment]
Oh, I just noticed that this is the case if disablePan is set as well so updated the issue.

**Comment by timmywil** [comment]
Thanks for opening an issue. This was fixed in version 4.4.2. Your fiddle is using version 4.3.2. I switched it to 4.4.3 and it seems to be working.
