### ISSUE TITLE
Background image disappearing on zoom

### ISSUE THREAD

**Issue by carljustineoyales** [timmywil/panzoom#590]
### Describe the bug

JPG background image of a child element of panzoom will disappear when zooming in and will not reappear when reloading the page .. it will only appear again when the page is hot reloads. It works perfectly in Mozilla but in chrome it disappears.

### Your environment

- Version of panzoom: 4.4.3
- Browser and browser version: Chrome Version 95.0.4638.69 (Official Build) (64-bit)

### Expected behavior

Background image should not disappear when zooming in

### Actual behavior

Background image disappears when zooming in and will not reappear until the page hot reloads

### Steps to reproduce

html
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
		<link rel="stylesheet" href="style.css" />
		<script src="https://unpkg.com/@panzoom/panzoom@4.4.3/dist/panzoom.min.js"></script>
	</head>
	<body>
		<div id="panzoom">
			<div id="app"></div>
		</div>
		<script type="text/javascript">
			// iphone X starting scale 0.067
			// 1920x1080 starting scale 0.3365
			const elem = document.getElementById("app");

			const panzoom = Panzoom(elem, {
				maxScale: 1.8,
				minScale: 0.325347,
				contain: "outside",
				startScale: 0.325347,
				panOnlyWhenZoomed: true,
				cursor: "default",
				startX: -6066.86,
				startY: -2839.35,
			});

			elem.parentElement.addEventListener("wheel", panzoom.zoomWithWheel);
			// you might find that the things start breaking when the contain option is set.
			// This is due to the fact that in order for Panzoom to retrieve proper dimensions, the scale needs to be painted.
			// If you find that things aren't looking quite right, try the following instead...

			panzoom.zoom(0.325347);
			setTimeout(() => {
				panzoom.pan(-6066.86, -2839.35);
			});
		</script>
	</body>
</html>
```

css
```
#panzoom {
  width: 100vw;
  height: 100vh;
  background-color: #000000;

}


#app {
  
  background-image: url('../img/bg.jpg'); //any bg image as long as it is jpg
  background-position: center center;
  background-repeat: no-repeat;
  background-size: contain;
 width: 100vw;
  height: 100vh;



}
```

**Comment by timmywil** [comment]
Thanks for opening an issue. It's hard to say exactly, but it sounds like there's a lot going on. It would be helpful if you put together a small working example on https://jsfiddle.net, https://jsbin.com,  or https://codepen.io. I can help debug, but I don't suspect this will require a change to Panzoom. Will reopen if I'm wrong.
