### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by paopre** [timmywil/panzoom#591]
Hello,

thanks for your very useful library!

Regarding the "Panzoom instance within another Panzoom instance" demo, is it possible to preserve the original size (--> no zooming) of the contained element while zooming the parent element?

**Comment by timmywil** [comment]
Thanks for opening an issue. If the element is within the main Panzoom element, then it will be zoomed along with the Panzoom element's other children. You could offset that and whenever the Panzoom element is zoomed, set a scale on the contained element that would negate the Panzoom scale (i.e. scale it down by the same amount everything else is scaled up or vice versa). If you also don't want the child to pan, you could move the child outside the Panzoom element and position it absolutely. Either way, I think the options available should be enough to accomplish this (probably using `setTransform`). I see a special option for this being just as complicated.

**Comment by paopre** [comment]
> Thanks for opening an issue. If the element is within the main Panzoom element, then it will be zoomed along with the Panzoom element's other children. You could offset that and whenever the Panzoom element is zoomed, set a scale on the contained element that would negate the Panzoom scale (i.e. scale it down by the same amount everything else is scaled up or vice versa). If you also don't want the child to pan, you could move the child outside the Panzoom element and position it absolutely. Either way, I think the options available should be enough to accomplish this (probably using `setTransform`). I see a special option for this being just as complicated.

I tried your tip but could not obtain the wanted result. Here is a fiddle of my attempt:

https://jsfiddle.net/Ld967asj/1/

thanks!

**Comment by timmywil** [comment]
Hopefully this gets you a little closer: https://jsfiddle.net/timmywil/85Lqe9wu/

**Comment by paopre** [comment]
> Hopefully this gets you a little closer: https://jsfiddle.net/timmywil/85Lqe9wu/

thanks very much
