### ISSUE TITLE
Weird text resizing of SVG texts on Chrome

### ISSUE THREAD

**Issue by paopre** [timmywil/panzoom#593]
Hello,

I don't know if this is a Chrome issue or a Panzoom issue but, in any case, it would be important to fix it.
On Chrome (tested on Version 96.0.4664.45 (Official Build) (64-bit), Linux (Lubuntu)) I see weird resizing of SVG texts after panzooming, on mouse over the text.
I don't have the previous bug on Firefox (94.0 (64-bit)), nor on Chromium (Version 96.0.4664.45 (Official Build) snap (64-bit))

Please see this very short example:

https://jsfiddle.net/2stekjvm/9/

Steps to reproduce:

1) panzoom with the mouse wheel the svg image
2) move the mouse over the element, after panzooming. You will see the text resized as soon as the mouse pointer touches it.

Thanks for your help/feedback!

**Comment by paopre** [comment]
As a further information, I just verified that the bug doesn't happen if I add a text-rendering attribute to the <text> node. See:

https://jsfiddle.net/s68zcd3b/

**Comment by P82maarj** [comment]
I had the same issue. I've been 3 days crazy until I have found that the issue was with Chrome 96 (in 95 from 1st of Nov and below there is no problem) and thanks @paopre for your workaround! it works!

**Comment by timmywil** [comment]
Thanks for opening an issue! I've added this workaround to the README.
