### ISSUE TITLE
Panzoom stops working when target's height or width is 0

### ISSUE THREAD

**Issue by Foshkey** [timmywil/panzoom#594]
### Describe the bug

👋🏻 I'm back with another odd case we stumbled across, and we were really scratching our heads over this because it was one of those fun bugs that we could not consistently recreate. But I think we figured it out.

Specifically, we sometimes call `panzoom.zoomToPoint` when our target element's width & height is 0. This causes panzoom to enter an irrecoverable bad state, even when the target element resizes to a valid size. We can't zoom or pan anymore.

I think it has something to do with [this line](https://github.com/timmywil/panzoom/blob/23911148813604f8d4fafa7f7b2abaa7033179d3/src/panzoom.ts#L189); divides by 0 and NaN gets stored, though I haven't fleshed out entirely why this causes such a bad state.

Nothing critical, but just wanted to bring to your attention in case you want to safe-guard against this.

### Your environment

- Version of panzoom 
  - 4.4.3
- Browser and browser version
  - Edge 95.0.1020.53

Options:
```js
      Panzoom(zoomTarget, {
        minScale: minScale,
        maxScale: maxScale,
        panOnlyWhenZoomed: true,
        contain: 'outside',
        noBind: true,
        step: step,
      }),
```

### Expected behavior

Even when `zoomToPoint` is called while the target element has width/height of 0, `zoomToPoint` still works afterwards when the target element has a non-zero width/height.

### Actual behavior

After `zoomToPoint` is called while the target element has width/height of 0, `panzoom` no longer functions, even when the element resizes to proper dimensions.

**Comment by timmywil** [comment]
Thanks for opening an issue! You're right. I should protect against a possible `NaN` there.

**Comment by timmywil** [comment]
I just submitted a fix for this to the `main` branch. If you get a chance, please have a look and let me know if that works for you.
