### ISSUE TITLE
Stop Drag at the containers corner

### ISSUE THREAD

**Issue by cvalues** [timmywil/panzoom#596]
When dragging, you want to prevent the panzoom element from being moved beyond the edges of the container.

How could that possible? Contain: 'inside' seems not to do the trick.

KR

**Comment by timmywil** [comment]
Thanks for opening an issue. `contain: 'inside'` is how you would accomplish that. The [demo](https://timmywil.com/panzoom/demo/#Containment%20within%20the%20parent) has an example. If you encounter a bug, please provide a test case from https://codepen.io or https://jsbin.com and we can revisit.

**Comment by cvalues** [comment]
Thanks for the very fast answer. Our problem is that the element inside the container ist much bigger than the container. Is that also possible?
