### ISSUE TITLE
Feature: panzooming a PDF document

### ISSUE THREAD

**Issue by paopre** [timmywil/panzoom#599]
Hello,

it would be GREAT if we can properly panzoom a PDF document. Currently, if a PDF doc is panzoomed, it is not re-rendered, then its image gets blurry. However, there's a solution for this: from what I can see, panzoom lib is well compatible with PDF.js, thanks to the setTransform option.
Here is a very little snippet for this:

https://jsfiddle.net/s36vetug/8/

I think that the procedure is correct, but unfortunately I'm stuck into two issues that I think can be easily fixed (then I ask for your help):

1) I don't know how to pan correctly the PDF after (or before?) the renderPage() function is called.
2) consecutive renderings have to be queued in order to make this work properly

Any fix for 1+2 is really welcome: I could not find any tool for doing that on a PDF, apart the panzoom lib.

Thanks!

**Comment by timmywil** [comment]
Thanks for opening an issue. There's a lot going on here. Because you want to pan and zoom the container rather than the pdf itself, the scale set by panzoom is not necessarily the same as the scale that the pdf should be at that given time. Also, if when it's correct, you still see a flash every time the pdf re-renders. I'm not sure what to suggest except to say that pdf.js does have options to set transforms directly on the pdf document and perhaps you'd have better luck with that, rather than re-rendering every time.

Sorry I couldn't be more help. You might find more suggestions on stackoverflow.com.

**Comment by paopre** [comment]
After some days of attempts, I solved this.
Here is the proposed solution:

https://stackoverflow.com/questions/70428922/pan-zoom-a-pdf-javascript/70501465#70501465

https://jsfiddle.net/7tmk0z42/

Please, consider to add this to the documentation of the library. I could not find any other example, on the www, of a PDF that can be panzoomed, and therefore I think it is useful. 


> Thanks for opening an issue. There's a lot going on here. Because you want to pan and zoom the container rather than the pdf itself, the scale set by panzoom is not necessarily the same as the scale that the pdf should be at that given time. Also, if when it's correct, you still see a flash every time the pdf re-renders. I'm not sure what to suggest except to say that pdf.js does have options to set transforms directly on the pdf document and perhaps you'd have better luck with that, rather than re-rendering every time.
> 
> Sorry I couldn't be more help. You might find more suggestions on stackoverflow.com.


After some days of attempts, I solved this.
Here is the proposed solution:

https://stackoverflow.com/questions/70428922/pan-zoom-a-pdf-javascript/70501465#70501465

https://jsfiddle.net/7tmk0z42/

Please, consider to add this to the documentation of the library. I could not find any other example, on the www, of a PDF that can be panzoomed, and therefore I think it is useful.

**Comment by timmywil** [comment]
Glad you figured it out! I will add this example to the docs.
