### ISSUE TITLE
Safari svg and zoom issue

### ISSUE THREAD

**Issue by jasperf** [timmywil/panzoom#602]
### Describe the bug

We are currently have issues with an svg line grid which we use to position modules on. The svg is now 2 times smaller than on Chrome/ Safari. The other issue is that zoom in for some reason sometimes zooms out and when we use reset it does not work anymore at all. No errors shown. Later on zoom does work, but svg grid stays much smaller than in other browsers and zooming in starts showing the lines but very blurry

### Your environment

- Version of panzoom 4.4.3
- Browser and browser version Safari Version 15.2 (15612.3.6.1.8, 15612)

### Expected behavior

SVG grid should display the same as on Chrome/Safari. Zoom in should also zoom in and reset should reset as expected.

### Actual behavior

For reasons unknown Zoom in or our plus button zoom out to 134% and then reset fails to go back to 100%. Then on second load zoom does work but things become rather blurry. 

![Screen Shot 2021-12-24 at 4 03 33 PM](https://user-images.githubusercontent.com/344138/147337969-f3f664e1-6d71-4c40-930d-001047ee15bd.png)

NB Thicker lines at 100% should cover 100px and now they barely at 182% in Safari.

Other main point that remains is that neutral state or no zoom called 100% seems to be a zoomed out state in Safari.

### Thoughts

Perhaps to Safari 100% settings is not 100% or none like for Chrome/Firefox. If so we need to understand why and how to add a fix for Safari.

**Comment by timmywil** [comment]
Thanks for opening an issue. However, I can't reproduce this behavior. If you have time, please provide a reduced test case from https://jsbin.com or https://codepen.io.

**Comment by jasperf** [comment]
We found a bug in our own svg grid lines setup where Safari picked up the second set of values to show the svg dashed line which were at 50px instead of at 100px. This caused it all to look smaller. This also caused a blurry look on zoom. So seems the bug was all on our side.  Enjoy the holidays!
