### ISSUE TITLE
Release 4.4.4 in Github.

### ISSUE THREAD

**Issue by jcnventura** [timmywil/panzoom#608]
Looking at the commit log, you created a 4.4.4 release a few weeks ago (https://github.com/timmywil/panzoom/releases/tag/4.4.4), but the list of releases still doesn't show it (https://github.com/timmywil/panzoom/releases).

Would it be possible to add 4.4.4 to the list of releases?

**Comment by timmywil** [comment]
hmm, that's supposed to happen automatically. Something must have went wrong. Thanks

**Comment by timmywil** [comment]
Done
