### ISSUE TITLE
Feature: Custom options for mouse down events

### ISSUE THREAD

**Issue by EgoistDeveloper** [timmywil/panzoom#609]
**What problem does this feature solve?**
Current pan options are enough for simple solutions but I am building a board app and there are many elements. I want to make some elements selectable but panzoom working with left and right mouse down.

**Describe the solution you'd like**
If there is a custom action for the left or right mouse down I can figure this out. I am planning to use [viselect](https://github.com/Simonwep/selection) package.

**Additional context**

https://user-images.githubusercontent.com/17010054/152632524-50e3122d-e82e-4d26-ba09-5ed781baee3f.mp4

**Comment by timmywil** [comment]
Thanks for opening an issue. I should be possible to add a hook to the down handler where if it returns false, the handler would stop. This would allow you to check for things like right click and modifiers like shift & alt. But everything about binding is centered around pointer events with fallbacks, so if something more custom is needed, it would still be best to pass `noBind: true` and bind events yourself.

That said, while something like this is possible, I'd like to [gauge interest](https://github.com/timmywil/panzoom/blob/main/.github/CONTRIBUTING.md#feature-requests) first.

**Comment by yourfriendoss** [comment]
I'd like this too! My app needs to only be movable via the middle click, and I don't want to redo all of the event binding that panzoom has already done.

**Comment by veudal** [comment]
A workaround for me was to set disable pan competly whenever on mouse down if a certain mouse button was pressed/not pressed like this:

```
onMouseDown() {
   // e.g. for only allowing right click:
    if(e.button !== 2)
        panzoom.setOptions({ disablePan: true })
}
```

Additionally, a mouse up event listener is also needed in order to restore the changes again:

```
onMouseUp() {
   panzoom.setOptions({ disablePan: false })
}
```
