### ISSUE TITLE
Centering element to parent container

### ISSUE THREAD

**Issue by TiagoSLoureiro** [timmywil/panzoom#614]
Hey there!

I can't seem to find a way to center the panzoom element to it's parent, specially in a responsive way.
I am using contain outside.

Usin startX and startY options are not very responsive. Or am I missing something?
Thanks

**Comment by timmywil** [comment]
Thanks for opening an issue. The panzoom element, or sometimes better yet an element within the panzoom element, can be centered with regular CSS before initializing Panzoom. If you make an example on codepen.io, we might be able to work through it.

**Comment by TiagoSLoureiro** [comment]
Thanks for answering.

So, when I use Flex vertical, center and justify, the image get's cut, as you can see in this codepen
https://codepen.io/tiago-loureiro-the-looper/pen/MWrrVOW

When I don't use flex, the image appears completely, but I need it to be centered.

Any solution?

Thanks mate!
