### ISSUE TITLE
Feature:  set initial scale of the Panzoom element to always fit viewport

### ISSUE THREAD

**Issue by karthikeyanrajmohan** [timmywil/panzoom#616]
Before submitting a feature request, please check [existing feature requests](https://github.com/timmywil/panzoom/issues?q=label%3A%22votes+needed%22+sort%3Areactions-%2B1-desc) and add your :+1: reaction if your feature exists.

**What problem does this feature solve?**
Unable to display default the Image in Center, Because SVG is widht:1600 and height:700. In some cases, the Height is more. 
So the user to Click Zoom-out a couple of times manually to see the full SVG. 

**Describe the solution you'd like**
Option to define as **align: 'center'** and **viewport: 'fit'**

**Describe alternatives you've considered**
NA

**Additional context**
Is there any quick solution?

**Comment by timmywil** [comment]
Thanks for opening an issue. Generally, the position of the image is based on the CSS before Panzoom is initialized. That said, making sure the whole element is visible might be a possible feature addition. Adding it to the list.
