### ISSUE TITLE
Feature: panTo() or centerOn()

### ISSUE THREAD

**Issue by chuckntaylor** [timmywil/panzoom#617]
FIRST: Thank you for sharing this project. It is a great package, and fairly straight-forward to use.

**What problem does this feature solve?**
The `zoomTo()` method is great! I have been trying to come up with a calculation for a `panTo()` or `centerOn()`, in order to automatically center an area of the scene.

**Describe the solution you'd like**
In my particular case, I have been trying to center the view on an area of the scene based on a percentage value. For example, 36% from the left 80% from the top. I have been able to get this to work, but it comes apart for me when the scale is anything but 1.
`function centerOn(xPercent: number, yPercent: number): void {}`

**Additional context**
I am still working on this, but having a hard time wrapping my head around the formula regarding the visible area and the scale. I will post again if I come up with something.

**Comment by timmywil** [comment]
Thanks for opening an issue. When the scale is in play, I think you'll probably just need to divide your calculations somewhere by the scale and set the pan as if there weren't any scale applied. Then you can use the regular `pan` method. I'd rather not add another method that only pertains to viewport percentages as that seems little too niche. That said, if you make a working example, I'll take a look.

**Comment by chuckntaylor** [comment]
Thanks for the feedback! I ended up writing the following, and it seems to do the trick. The y-axis calculation seemed a lot easier. If I am not mistaken, `0` on the y-axis is always the center of the scene?
Anyway, I hope this is of use.

```ts
// The percent values for x and y are expected in the range of 0 - 1. ie 50% = 0.5
function centerOn(xPercent: number, yPercent: number, panOptions?: PanOptions) {
  if (!scene || ! scene.parent) return
  const scale = panzoom.getScale()
  const realWidth = scene.clientWidth
  const realHeight = scene.clientHeight

  const scaledWidth = realWidth * scale

  const diffHorizontal = (scaledWidth - realWidth) / 2
  
  const viewableAreaWidth = scene.parent.clientWidth
  const viewableAreaHeight = scene.parent.clientHeight
 
 // x axis calculations
  const maxX = diffHorizontal / scale
  // how many pixels from the left the target is
  const xPos = realWidth * xPercent
  // maxX is on the left and the value gets lower moving left to right
  // this finds the position where the viewable area's left edge would run through the target's center
  const xLeftEdge = maxX - xPos
  // amount to shift the scene to compensate for the scale and the viewable area width
  const viewableHorizontalShift = viewableAreaWidth / 2 / scale
  // again the x-axis values get larger to the left so we need to add the viewableHorizontalShift so that it is centered
  const newX = viewableHorizontalShift + xLeftEdge

  // y axis calculation
  const newY = viewableAreaHeight / 2 - realHeight * yPercent

  panzoom.pan(newX, newY, { ...panOptions })
}
```

**Comment by timmywil** [comment]
Thanks for that! I think this could be useful in another upcoming feature.
