### ISSUE TITLE
animate does not change zoom or drag transitions

### ISSUE THREAD

**Issue by christopherwalkerml** [timmywil/panzoom#619]
### Describe the bug

setting `animate: true` does not change anything. neither dragging or scrolling changed at all.

### Your environment

- Version of panzoom 4.4.4
- firefox 99

### Expected behavior

maybe dragging should carry it's momentum after letting go while moving the cursor?
zooming should be smooth / have a transition

### Actual behavior

dragging is jittery / instant
dragging stops when on mouseup

### Steps to reproduce

https://jsbin.com/tiwomoqafi/1/edit?html,js,output

**Comment by timmywil** [comment]
Thanks for opening an issue. However, `animate` is intentionally ignored when dragging and zooming with the wheel. To allow for transitions would cause all sorts of issues as the transition tries to catch up and paints the properposition/dimensions. The browser can also become unresponsive in those situations as you can easily queue changes long before they are finished painting.  Besides, supporting it would require duplicating browser calculations that are no longer in Panzoom, to save a lot of size. You can, however, animate to specific points and scales by calling `pan` and `zoom` directly.
