### ISSUE TITLE
startX, startY and startScale don't work with contain

### ISSUE THREAD

**Issue by christopherwalkerml** [timmywil/panzoom#620]
### Describe the bug

setting `contain: 'outside'` breaks the starting position of the panzoom object.
oftentimes the object even starting outside of the viewport.

### Your environment

- panzoom 4.4.4
- Firefox 99

### Expected behavior

the object shouldnt start outside the viewport, and startX,startY,startScale should have an effect on the object.

### Actual behavior

the object starts in a weird location, and then upon starting to panzoom it, it snaps back into it's constraints.
the startX and startY values seem to have zero effect, and the startScale value seems to put the object in a weird spot.

### Steps to reproduce

https://jsbin.com/putunekuna/2/edit?html,js,output

**Comment by timmywil** [comment]
Thanks for opening an issue. However, this is documented behavior. The panzoom element must remain larger than it's parent when using contain: 'outside'. It doesn't sounds like `"outside"` is exactly what you want, but there will likely be a forthcoming option that will automatically switch the contain option if the panzoom element becomes too small.
