### ISSUE TITLE
Can't set initial point (origin point)

### ISSUE THREAD

**Issue by 0xgainz** [timmywil/panzoom#621]
### Describe the bug

I am trying to make an interactive map. I am using an image as background and on top of it I am overlaying icons. However, I can't seem to be able to set the starting point. The image is 16:9 so on a normal 16:9 screen, it fills the scree and it looks centered. However, on a small viewport like a phone for example, the starting point of the panning is in the top left corner.

### Your environment

- Version of panzoom: 4.4.4
- Browser and browser version: Brave browser

### Expected behavior

I am expecting the origin/starting point to be dead in the center of the image.

### Actual behavior

The origin/starting point is in the top left corner of the image

### Steps to reproduce

You can see this behaviour in the demo below. If you change to a smaller viewport, the origin point will not be the center.

https://map.tranquilitycity.one/

Here is my code:

https://pastebin.com/cxDfC6a6

**Comment by timmywil** [comment]
Thanks for opening an issue. A working, reduced test case is needed, not just a pastebin. But, most of the time, the initial position of the Panzoom element should just be done with CSS. I see you're using `contain: 'outside'` and the Panzoom element is larger than the viewport, so you're probably looking at positioning with negative margins or top/left. If you put together an example, we can go further.

**Comment by 0xgainz** [comment]
Hi @timmywil ! I did give you a functional example: https://map.tranquilitycity.one/ of what we were building. I also gave you a pastebin of the Vue component. Does that suffice?

**Comment by timmywil** [comment]
@0xgainz No, sorry, Full sites and pastebins are not test cases. Ideally, it would have the least amount of code possible to show a specific problem, using codepen.io or jsbin.com. The bug template has a link to a starter: https://jsbin.com/dibofogini/1/edit?html,js,output
