### ISSUE TITLE
Merging PRs?

### ISSUE THREAD

**Issue by spacecowgoesmoo** [timmywil/panzoom#622]
https://github.com/timmywil/panzoom/pull/452
https://github.com/timmywil/panzoom/pull/607

Are there any upcoming plans for merging in these two PRs? They fix some worthwhile UI issues for us and we're probably going to create a fork in the meantime.

(Sorry if the Issues tab isn't the right place to ask, github could use a discussion forum sometimes)

**Comment by timmywil** [comment]
I sometimes get very busy with other things. One of those is my PRs. I feel good about merging that. The min pan distance one still needs some work.

#607 has been merged, but I won't release immediately.
