### ISSUE TITLE
(Question) - Binding panning to a different button

### ISSUE THREAD

**Issue by SveinEven** [timmywil/panzoom#624]
Hello!

I'm trying to implement this library in a project, but I have one issue. I would like the panning to be either with middle mouse button.
I dont know if I have overlooked something, but I've been unable to find anything to help me.

What are the correct functions to bind to a different button? 
I have found "noBind" option to stop the default binding, but I have not been able to rebind them to something else.

Thanks!

**Comment by timmywil** [comment]
Thanks for opening an issue. If I understand correctly, you want to begin the pan with the middle mouse button, drag using move events as usually and end the pan with middle button again? That does mean that it wouldn't work on mobile devices or any device that doesn't use a mouse. Panzoom uses pointer events, which covers all devices whether they use touch or mouse events. That said, maybe you don't need to support such devices. I think the easiest way to do this would be for me to expose the event handlers that you could then bind to anything, but I can't guarantee they would work in all cases.

**Comment by timmywil** [comment]
Event handlers are now on the Panzoom object returned from `Panzoom()`. Hope that helps. See https://github.com/timmywil/panzoom/blob/main/README.md#handledown
