### ISSUE TITLE
Feature: Inertia panning and zooming

### ISSUE THREAD

**Issue by Rinyuu** [timmywil/panzoom#625]
I want to use panzoom with a huge SVG/div, so needing to drag without inertia will take a long time to navigate over the whole div...
It would be a lot faster and easier if I could just throw my viewport a certain direction, slowly easing out instead of coming to a stop immediately.

So....Is there an option to make panzoom do panning with inertia?

For example, if I pan using mouse or touch and release while dragging, it will keep sliding for a while until the panning slowly comes to a stop. 

It would be really nice if that could be done with zooming too!

**Comment by timmywil** [comment]
This has been requested before so I'll add it to the votes queue. However, I think this feature might require significant changes and a good bit of size. That said, it might be possible to implement this as a plugin without any changes required to the core library. Theoretically, I think we could hook into existing events and continue the drag or zoom based on accumulated velocity. I don't mind doing this, but I'd have to set aside some time.

**Comment by veudal** [comment]
Hello @timmywil,

I noticed that this issue/feature request has received 9 votes so far. I was wondering if this would be enough to consider implementing the feature or if more votes are needed to prioritize it.

Looking forward for a response. Additionally, I would like to thank you for this awesome library either way.

**Comment by timmywil** [comment]
I'm fine with the idea, but I don't currently have the time. If anyone would like to work on a PR, I can review it.
