### ISSUE TITLE
getPrefixedName - error TS7030: Not all code paths return a value.

### ISSUE THREAD

**Issue by krstns** [timmywil/panzoom#626]
### Describe the bug

Function has a path which does not return any values.

### Your environment

Angular 14.
Panzoom 4.5.0
noImplicitReturns set to true

### Expected behavior

Function should always return a value.

### Actual behavior

Code has a path where no value is returned and triggers a typescript build error.

### Steps to reproduce
Build project with `noImplicitReturns` set to true.

**Comment by timmywil** [comment]
Thanks for opening an issue. However, the function is working as intended. I have `noImplicitReturns` set to false and making the library code pass everyone else's TypeScript rules would be chaos. Also, I prefer to allow implicit returns. I suggest ignoring dependencies when running type checks.
