### ISSUE TITLE
[Help] Is it possible to prevent links from navigating to a new page when dragged but still allow them to work when clicked?

### ISSUE THREAD

**Issue by ryanmortier** [timmywil/panzoom#632]
Hello,

I was looking at your example page here: https://timmywil.com/panzoom/demo/#Exclude%20elements%20within%20the%20Panzoom%20element%20from%20event%20handling

The third link, the one that allows dragging. Is it possible to make it so that you can drag a link without triggering its on click event but also still have it work like normal when not dragging, just clicking?

Thanks.

**Comment by timmywil** [comment]
Thanks for opening an issue. Yes, I think this should be possible by adding listeners to panzoomend to check if the element moved. Then add a click event to the anchor to check that `moved` variable to decide whether to prevent default. Let me know if you need an example.

**Comment by ryanmortier** [comment]
Ah, good idea. No, I should be able to figure it out from here. Thanks!

**Comment by walpita-dev** [comment]
Hi, I'm not sure to understand how I can check if the element moved with the panzoomend event, is it possible to have an example ? :)

**Comment by jenswittmann** [comment]
@walpita-dev maybe this helps: https://github.com/timmywil/panzoom/issues/663#issuecomment-2717326921
