### ISSUE TITLE
how to zoom to precise id

### ISSUE THREAD

**Issue by github88vil** [timmywil/panzoom#636]
Would it be possible to zoom the opening page on a precise id, perhaps specified in the $GET or $POST variable of the url link?
I hope I was clear...

**Comment by timmywil** [comment]
Thanks for opening an issue. It would be possible to work out, but it depends on several factors that would vary depending on the page (the layout, structure of the HTML, etc). I don't think a feature could be built into Panzoom that would cover all use cases. Thank  you for the suggestion, though.

**Comment by github88vil** [comment]
I'll explain ... I built my family tree with panzoom. I would have
needed to point the page to the box with the requested ancestor 🤔


Il Lun 19 Dic 2022, 16:46 Timmy Willison ***@***.***> ha
scritto:
