### ISSUE TITLE
Image not always centred on load, using `contain: 'outside'`

### ISSUE THREAD

**Issue by theRealPadster** [timmywil/panzoom#637]
### Describe the bug

I'm not sure why, but sometimes when Panzoom initializes, the image is not always centred. I have a single image in my wrapper, and I want it to fill the wrapper, like `cover` in css, and allow you to pan to the edges. But sometimes when I load the page, it's filling properly, and sometimes it's shifted down like 100 pixels, then jumps back to the right spot when I trigger a pan. 

### Your environment

- Version of panzoom: 4.5.1
- Browser and browser version: MS Edge version 109.0.1518.70 (Official build) (arm64 - on macOS). It does the same thing on Chrome. 

### Expected behavior

When the page loads, the image should be centred, with the top of the image at the top of the container and zoomed to cover the rest of the wrapper. 
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/1565883/215533963-aab5ca58-10ff-4f54-82f1-cd76fc12de9d.png">

### Actual behavior

It seems to randomly work, and randomly load with the image down 100 or so pixels. It jumps back to the right spot when I pan. 
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/1565883/215533866-1ff33523-f426-4723-96b0-451d8bb91eff.png">

### Steps to reproduce
I'm using Parcel as a build process. Developing using `parcel` to start a server at localhost:1234, and `parcel watch` so it reloads when I save. I don't think this matters, as it was doing the same thing with a built version of the project. 

```html
<div class="waldo-game__pan-area">
  <div class="waldo-img__wrapper">
    <img src="../public/img/waldo/scenes/scene1.jpg" alt="Waldo" class="waldo-img">
    <!-- Viewbox is the native image dimensions, to preserve the aspect ratio -->
    <svg class="waldo-svg" viewBox="0 0 2160 1449">
      <!-- Circles etc are drawn via js when the user clicks on the image -->
    </svg>
  </div>
</div>
```

The rest of the markup and css is on the jsbin I tried making, but it doesn't really show what I'm seeing. 
https://jsbin.com/ravurinere/edit?html,css,js,output

It works when the transform is `transform: scale(1.60003) translate(0px, 70.3135px);` but then it'll randomly have `transform: scale(1.60003) translate(65.5087px, 184.572px);`

Sorry if this is a bit of a messy bug report. I'm not sure why the initial state isn't consistent on page load.

**Comment by theRealPadster** [comment]
I made a [codesandbox](https://codesandbox.io/s/billowing-currying-luv8d2?file=/src/index.js), which is more true to my project, but it doesn't look like pnazoom is even running on it for some reason.

**Comment by timmywil** [comment]
Thanks for opening an issue. I suspect some sort of race condition. For instance, if an image hasn't loaded before Panzoom reads the dimensions of elements. If you could rule that out, that would be helpful. You can do that by waiting to initialize Panzoom for a long timeout (like 5sec) and see if you still have the same issue. If it does seem related, you may be able to fix it by binding to load events. Let me know if that helps.

**Comment by theRealPadster** [comment]
@timmywil Thanks for the suggestions. I had it inside an image load event listener, but I tried adding a delay inside, and it still seems to randomly initialize shifted down. I can see if move down when the 5s is up. Is there some other load event or Panzoom event I should try? 

This is the code I have:
```js
img.addEventListener('load', () => {
    console.log('img loaded');
    if (pz) {
      console.log('resetting pz');
      pz.reset({ animate: false });
    } else {
      console.log('starting pz 5s timeout...');
      setTimeout(() => {
        console.log('starting pz now');
        pz = Panzoom(wrapper, {
          contain: 'outside',
          panOnlyWhenZoomed: true,
        });
      }, 5000);
    }
```

**Comment by theRealPadster** [comment]
Here's a screen recording. It works the first time and then the second time it fails. 
https://user-images.githubusercontent.com/1565883/216081369-f318c99a-739e-45dd-9e7f-ceb9964ec788.mov
