### ISSUE TITLE
Issues with handleDown fn when there's a need to select text on elements

### ISSUE THREAD

**Issue by sauriio** [timmywil/panzoom#641]
### Describe the bug

Before all, great work on this library, is working really well and the doc is clear and clean, I have an issue when I am using panzoom with fabricJS, there's is some missing functionality used here select the text when clicking or double clicking on the text, I have a jsFiddle to demonstrate this.

https://jsfiddle.net/r9mwat0x/
any ideas of what could be happening on the handleDown that is triggering this issue?

### Your environment

- Version of panzoom: 4.5.1
- Browser and browser version: chromium 113.0.5630.0

### Expected behavior

the text is selected with double or triple click

### Actual behavior

clicking on any of the textboxes has no effect on selection of the text.

### Steps to reproduce
https://jsfiddle.net/r9mwat0x/

**Comment by sauriio** [comment]
My bad, adding the handleStartEvent: () => {}, fixed this issue, closing this issue

**Comment by InfiniteCoder01** [comment]
This didn't help me, but adding `excludeClass` + resetting `user-select` to `text` in children worked.
