### ISSUE TITLE
Feature: adjust the zoom rate to increase with element size

### ISSUE THREAD

**Issue by folsze** [timmywil/panzoom#643]
Hi,

I am not sure whether this is the correct way to do this (I wanted to ask in Discussion Tab but there was none for this github repo). 

I am not sure whether this is a bug or just a trait of this library. 

**What problem does this feature solve?**
basically with my svgs the pinch-zooming gets really slow when I get like 50% zoomed in.

Here is a GIF:
![ezgif-3-12717332c1](https://user-images.githubusercontent.com/81622754/226464959-64cc16bd-e863-4d57-8c19-884383ff1565.gif)

**Describe the solution you'd like**

Here is a GIF:
![ezgif-3-9e091e3756](https://user-images.githubusercontent.com/81622754/226464984-20573b5d-3bf9-4de6-bb32-49d561cd1de8.gif)
It's from https://apps.apple.com/us/app/what-is-there/id660164295 and uses React Native

As you can see the zoom is really constantly fast (same speed) on this app, there is no "progressively slowing down more" like @panzoom/panzoom does it

I can provide a minimal reproducible example if this would be helpful. Let me know and I will upload it right away. But I thought I'd wait first since maybe this is just a known trait of this library? I can somewhat see it when testing https://timmywil.com/panzoom/ but not as much as in my video I guess

I just wanted to report this as I did not find any hints on this in the docs. So maybe it could be helpful for other people who have the same problem too.

**Comment by timmywil** [comment]
Thanks for opening an issue. This has been debated a lot and I don't think any library gets it perfect for all cases. That said, I'm open to adjustments.

Before I make another change to zoom rate, though, I'd like to send this through [voting](https://github.com/timmywil/panzoom/blob/main/.github/CONTRIBUTING.md#feature-requests).

Also, if you haven't already tried it, play with the `step` option.

**Comment by folsze** [comment]
Hey I don't know why I didn't try the step option. It really helps my app. 

But there's still kind of an awkward slow zoom-out-speed now still when zoomed in, but users will just have to deal with this. Increasing the step already greatly helps zoom in to click those small circles in my video faster, which was the initial problem.

At some point I might try the other panzoom library for this slowness, but only once they fix their mobile-size-performance-bug with disabling click-event-prevent-default (https://github.com/anvaka/panzoom/issues/299). For now this library is superior.

**Comment by folsze** [comment]
So I think you can close the 'Votes needed' as your library already provides a solution to the mentioned problem :)

**Comment by folsze** [comment]
I might try to implement this in a fork this month or so, if it's not too hard. Do you think it would be very hard? 

Maybe you could give me some pointers just on where in this repository to start working on this? And what I should look into first? Only if it's not a lot of work for you. Thanks for creating this amazing library

**Comment by folsze** [comment]
I might try to implement this in a fork this month or so, if it's not too hard. Do you think it would be very hard?

Maybe you could give me some pointers just on where in this repository to start working on this? And what I should look into first? Only if it's not a lot of work for you. Thanks for creating this amazing library
@timmywil

**Comment by folsze** [comment]
@timmywil gonna actually do a spike in a fork this April or May still. Do you have any advice or pointers right now already? Would be much appreciated :)

**Comment by otaviogaiao** [comment]
> @timmywil gonna actually do a spike in a fork this April or May still. Do you have any advice or pointers right now already? Would be much appreciated :)
> 
> Basically I just wanna have this be the case: "Feature: adjust the zoom rate to increase with element size"

Do you have any update on this? I'm facing the same issue right now.
