### ISSUE TITLE
Feature: touchpad to pan

### ISSUE THREAD

**Issue by folsze** [timmywil/panzoom#644]
**What problem does this feature solve?**
Make panning with laptop touchpad possible. Just like in for example figma.com this is possible in the canvas.

**Describe the solution you'd like**
go on figma.com and pan with a laptop touchpad - that's the solution.
However: Figma has this extra-feature where the pan follows an axis if it almost matches. 
I wouldn't include that feature in the first version and never by default.

**Describe alternatives you've considered**
I've read here: 
https://github.com/anvaka/panzoom/issues/160
that there are certain workarounds for this other famous panzoom library.

Now do such workarounds exist in this library too?
If they do then it would be nice to know how to do it, for other users too you could include it below or into the Readme API reference.

But even if workarounds do exist (which would be great): it would still be nice to have this as a native feature

**Comment by timmywil** [comment]
Thanks for opening an issue. You can do this by binding to the wheel event and adjusting the pan based on the delta, much the same way as that other library. However, I think the right solution is for this not to be built in without significant demand given that it doesn't require much code.

**Comment by CaptinKraken** [comment]
+1 for this feature, we will be adding this to our application as well. Would be nice if there was a similar option to `zoomWithWheel`. 

`panWithWheel(direction: 'x', 'y', 'both?')`
