### ISSUE TITLE
Jitter on touch devices when zooming out 'beyond the limit'.

### ISSUE THREAD

**Issue by chuckntaylor** [timmywil/panzoom#649]
### Describe the bug
On touch devices, I am experiencing some shaking of the 'scene' when I pinch zoom-out and hit the 'zoom out' limit (scale of 1.0000). I have set `contain : 'outside'`

Attached is a [video](https://github.com/timmywil/panzoom/assets/17050325/e21bda25-4185-4a12-ad88-e27706218905)

This does not happen when I hit the limit of zooming ***in*** on a touch device, and does not happen when using a mouse on desktop. It is really when I zoom in a bit, and then zoom out 'beyond the limit'.

in the `panzoomzoom` event, I do see that `event.detail.scale` and `event.detail.x` / `event.detail.y` jump around a lot during this glitch. Once it has settled at zoomed out all the way, and I have stopped touching the device, If I then go to zoom out more, no jitter happens. I really need to zoom in a bit first, then zoom out beyond the limit in order to make this jitter show. 

Perhaps I can address this in one of the event listeners?

### Your environment

- Version of panzoom - `^4.5.1`
- Browser and browser version `iOS 16.5`

### Expected behavior
Not shake.

### Actual behavior
See the video.

**Comment by chuckntaylor** [comment]
I seemed to have solved this by setting `minScale: 1`

**Comment by BierDav** [comment]
`minScale: 1` doesn't always work, in addition it may be required to wrap the `img` you passed in an empty `div`. I don't know why, but it solves the issue, maybe there is an underlying bug that can be fixed there
