### ISSUE TITLE
Panning and Zooming to centre of a selected element

### ISSUE THREAD

**Issue by simonmellows** [timmywil/panzoom#653]
Hi Timmy, 

I have been banging my head against the wall trying to figure this one out and I'm sure it's just something silly I am missing. When a use selects an element within the SVG, I am trying to use the panzoom.zoom function and pass the focal object to zoom into the centre of the element. I want the selected element to fill the viewbox and be centered. I'm struggling to work out an algorithm to get the correct x and y coordinate to pass to the focal object. I have tried a lot of different variations and can't seem to land on a consistent calculation. Maybe I am misunderstanding the coordinate system?

I have successfully managed to zoom, then do a setTimeout and pan to the element, however I want a smooth transition straight to the centre of the element (which focal seems to offer). I just can't work out the calculation - is this something you can help me with? In my head this should be a relatively straight forward algorithm but haven't had any luck.

Look forward to hearing your thoughts,

Thanks,
Simon

**Comment by czz20220104** [comment]
> Hi Timmy,
> 
> I have been banging my head against the wall trying to figure this one out and I'm sure it's just something silly I am missing. When a use selects an element within the SVG, I am trying to use the panzoom.zoom function and pass the focal object to zoom into the centre of the element. I want the selected element to fill the viewbox and be centered. I'm struggling to work out an algorithm to get the correct x and y coordinate to pass to the focal object. I have tried a lot of different variations and can't seem to land on a consistent calculation. Maybe I am misunderstanding the coordinate system?
> 
> I have successfully managed to zoom, then do a setTimeout and pan to the element, however I want a smooth transition straight to the centre of the element (which focal seems to offer). I just can't work out the calculation - is this something you can help me with? In my head this should be a relatively straight forward algorithm but haven't had any luck.
> 
> Look forward to hearing your thoughts,
> 
> Thanks, Simon

**Comment by czz20220104** [comment]
where is ths answer ? where is the code?
