### ISSUE TITLE
 disablePan not working?

### ISSUE THREAD

**Issue by Jonnas123** [timmywil/panzoom#658]
### Describe the bug

Not sure if it's a bug

### Your environment

- 4.5.1
- Chrome Version 118.0.5993.120 (Official Build) (64-bit)

### Expected behavior

Enable/Disable pan

### Actual behavior

After I click the enable button and drag the div, then click the disable button, the div comes back to its default position and I'm still able to pan it. How to stop pan?

### Steps to reproduce
Sorry, I'm ok with this. I use draggable.

**Comment by stoora** [comment]
Hi, I have the same issue.
how were you able to achieve disabling pan? 
I have tried this code but it is not working.
`<button style="z-index:999;position:absolute" class="panzoom-exclude" 
onclick="(() => {alert(`locking view`);panzoom = null;elem.parentElement.onwheel = null; 
panzoom.setOptions({disablePan: true,disableZoom: true,disableXAxis: true,disableYAxis: true});})();">lock view</button>`

**Comment by Jonnas123** [comment]
[stoora](https://github.com/stoora) Acutually I need only drag feauture, not zoom. Look at the topics many people ask questions about this pan. But basically I've tested it and it doesn't work for me. So I don't use it. For my case, I use draggable jquery here https://jqueryui.com/draggable/ for dragging and for zooming I use built-in zoom feature  of Fabricjs.

**Comment by stoora** [comment]
panzoom.destroy(); on the panzoom div element did the trick.
