### ISSUE TITLE
Was something like a smart option added?

### ISSUE THREAD

**Issue by eric-g-97477** [timmywil/panzoom#660]
https://github.com/timmywil/panzoom/pull/583

Just before this PR was closed because it was incomplete, it was indicated that the feature idea would be coming to pan zoom?

The idea from the PR was:

> Adds 'smart' to contain option, to add intelligent sensing to use 'outside' or 'inside' per x and y.

Has it made it in yet or is it still in progress? Is there a ticket tracking the progress?

**Comment by timmywil** [comment]
Yes, the issue was closed in favor of https://github.com/timmywil/panzoom/issues/598, which should cover more use cases.
