### ISSUE TITLE
Logitech smooth scrolling causes wheel to zoom into full min and full max

### ISSUE THREAD

**Issue by liskou** [timmywil/panzoom#661]
### Describe the bug

When Loigitech Smooth scrolling is enabled for a mouse on LogiOptions, then scrolling seems to move from min to max and does not allow going in smaller steps.

This bug might be related to this one: https://github.com/timmywil/panzoom/issues/623

### Your environment

- Version of panzoom: 4.5.1
- Browser and browser version: Firefox 120 and Chrome 120 (yes the same version number on both)
- Windows 11
- LogiOptions+ v. 1.60.496306
- Mouse Logitech M185 and Logitech M720 

### Expected behavior

Scrolling should happen in small steps.

### Actual behavior

Scrolling goes from minimum to maximum.
Note that this bug happens only when the focus is on the browser window.

### Steps to reproduce

Enable Smooth scrolling on LogiOptions+ for your Logitech mouse scroll wheel. 

Go to this page and do the scrolling: 
https://jsbin.com/guzugeleni/1/edit?html,js,output

**Comment by timmywil** [comment]
Thanks for opening an issue. I haven't seen this before and I can't reproduce with my mouse. I don't have a Logitech mouse to test with, but if I had to guess, I would imagine it has less to do with the brand of mouse and more to do with your mouse sensitivity settings. But, if you like the settings where they're at, you can adjust the zoom increment with the [step option](https://github.com/timmywil/panzoom?tab=readme-ov-file#step), or you can get full control over the zoom. The [`zoomWithWheel` function](https://github.com/timmywil/panzoom/blob/main/src/panzoom.ts#L409) is just a convenience function that uses `zoomToPoint` and determines the zoom delta. You can override this with your own `zoomWithWheel` function, determine the delta however you see fit, and pass it to `zoomToPoint`. If you find that you are better able to account for a wider array of zoom sensitivity settings, I'd be willing to look at a PR. As it is, there's not much I can do.
