### ISSUE TITLE
How to avoid triggering the click event of a child element while moving?

### ISSUE THREAD

**Issue by kuangxianfeng** [timmywil/panzoom#663]
### Describe the bug

```html
<div id="box1"><div id="child"></div></div>
```

### Your environment

"@panzoom/panzoom": "^4.5.1",
Chore Version 122.0.6261.94 (official) (arm64)

**Comment by timmywil** [comment]
Thanks for opening an issue. I'm not exactly sure what you're asking. The `exclude` and `excludeClass` options will prevent panning if the child should handle the click event. To only fire the click event if the element has not moved, you could bind a handler to `panzoomend`, check the event target, and only fire the click if there was no panning. If that doesn't help, I think a test case will be needed from codepen.io.

**Comment by jenswittmann** [comment]
@timmywil thanks for the tip. This is my solution for handling panning on a clickable button:

```
var panning = false;

panzoom.addEventListener('panzoomchange', (e) => {
    panning = true;
});

panzoom.addEventListener('panzoomend', (e) => {
    setTimeout(() => {
        panning = false;
    }, 100);
});

document.querySelectorAll('a').forEach((el) => {
    el.addEventListener('click', (e) => {
        if (panning) {
            e.preventDefault();
        }
    });
});
```

Is this a good way forward or do you have another solution in mind?

**Comment by x528491x** [comment]
@jenswittmann how about:
```

let recentlyPanned = false;
elem.addEventListener("panzoompan", () => recentlyPanned = true);
elem.addEventListener("panzoomend", () => requestAnimationFrame(() => recentlyPanned = false));
```

removing a fixed duration timeout
