### ISSUE TITLE
Saving zoom/translate state to apply to a sequence of images on load defaults to translate 0.

### ISSUE THREAD

**Issue by Helipil0t** [timmywil/panzoom#666]
I'm trying to allow zoom and pan on a series of images (Weather Radar).  Clicking next to view the next radar slide or pressing play to animate the radar should preserve the zoom and pan reference through the each image load.  Zoom is preserved correctly but pan always resets to 0.  

`function saveTransformState() {
        if (panzoomInstance) {
            currentTransformState = {
                scale: panzoomInstance.getScale(),
                x: panzoomInstance.getPan().x,
                y: panzoomInstance.getPan().y
            };
            logDebug('Saved Transform State:', currentTransformState);
        }
    }

    function restoreTransformState() {
        if (currentTransformState && panzoomInstance) {
            panzoomInstance.zoom(currentTransformState.scale, { animate: false });
            panzoomInstance.pan(currentTransformState.x, currentTransformState.y, { animate: false });
            logDebug('Restored Transform State:', currentTransformState);
        }
    }

    function updateImageDisplay() {
        if (images.length === 0) return;

        const imgSrc = images[currentIndex] || '/images/default-image.jpg';
        logDebug(`Displaying image at index ${currentIndex}: ${imgSrc}`);

        // Ensure pane is visible before setting image source
        pane.style.display = 'block';
        imgElement.src = imgSrc;

        if (panzoomInstance) {
            panzoomInstance.destroy();
        }

        imgElement.onload = function() {
            logDebug(`Image loaded: ${imgSrc}`);
            const naturalWidth = imgElement.naturalWidth;
            const naturalHeight = imgElement.naturalHeight;

            if (!aspectRatio) {
                aspectRatio = naturalHeight / naturalWidth;
            }

            const { isMobile } = detectDevice();

            if (isMobile) {
                if (!initialHeight) {
                    pane.style.width = '100%';
                    initialHeight = pane.offsetWidth * aspectRatio;
                    pane.style.height = `${initialHeight}px`;
                } else {
                    pane.style.height = `${initialHeight}px`;
                    pane.style.width = `${initialHeight / aspectRatio}px`;
                }
            } else {
                pane.style.width = `${naturalWidth}px`;
                pane.style.height = `${naturalHeight}px`;
            }

            panzoomInstance = Panzoom(imgElement, {
                maxScale: 4,
                minScale: isMobile ? 0.5 : 1,
                contain: 'outside',
                step: isMobile ? 2.0 : 0.3,
            });

            restoreTransformState();

            imgElement.parentElement.addEventListener('wheel', function(event) {
                event.preventDefault();
                panzoomInstance.zoomWithWheel(event);
            });

            imgElement.addEventListener('dblclick', () => {
                panzoomInstance.reset();
            });

            pane.offsetHeight; // Force reflow
        };

        if (imgElement.complete) {
            imgElement.onload(); // Manually trigger onload if already complete
        }
    }

    function navigate(direction) {
        if (images.length === 0) return;

        saveTransformState();

        if (direction === 'next') {
            currentIndex = (currentIndex + 1) % images.length;
        } else {
            currentIndex = (currentIndex - 1 + images.length) % images.length;
        }

        updateImageDisplay();
    }

    function togglePlay() {
        isPlaying = !isPlaying;
        const playButton = document.getElementById('playButton');
        if (isPlaying) {
            playButton.textContent = 'Pause';
            playInterval = setInterval(() => {
                navigate('next');
            }, 1000);
        } else {
            playButton.textContent = 'Play';
            clearInterval(playInterval);
        }
    }`

I've tried to isolate as much as possible.  No styles or containers seem to be the cause.  inputting logs to detect state before and after loading images show that the restoreTransformState seems to execute and set the values correct but as soon as the function completes the translate gets reset to 0.   So not 100% sure this is a bug, but I've spent about a week on this and still can't figure it out.

**Comment by timmywil** [comment]
Thanks for opening an issue. It's hard to say what's happening without a test case. Please provide a [reduced test case](https://jsbin.com/dibofogini/1/edit?html,js,output) to help assess any issues. Closing for now.
