### ISSUE TITLE
Add Pointer Event gesture support for pinch zooming

### ISSUE THREAD

**Issue by tommyxd** [timmywil/panzoom#68]
Hello,

Currently I am unable to zoom using pinch gestures on a Surface RT tablet with IE11, neither in metro interface, nor in desktop. Everything seems to be working well on Android and iOS, so I guess it has something to do with pointer events, which seem to be supported in the current version.

I have disabled the default touch interaction for the container which is used for zooming, using the `-ms-touch-action: none;` css style so that such events are handled in javascript, but to no avail.

Any idea what I might be doing wrong?

Thanks!

**Comment by joergsteinhauer** [comment]
thanx @ljani , works for me on Windows Phone Nokia Lumia 630 (Microsoft Edge 25)

**Comment by timmywil** [comment]
Pointer events will be added back. I'll address this issue in the next version.

**Comment by daverodal** [comment]
I have a Lenovo All in one with touch screen. I cannot get this to work with the touch screen either.
I even tried above demo and pinch zoom did not zoom. 
mouse wheel works fine.
