### ISSUE TITLE
stop the panzoom on demand

### ISSUE THREAD

**Issue by oceatoon** [timmywil/panzoom#7]
Hi 
Thanks for the great plug , works great 
I have it set on a div 
but in the panzoom div , I have elements that are draggable and resizable 
so I'd like to stop the panzooming when these events start and turn it back on on end 
I tried destroy and reinitialising panzooming
but the result isn't good 
is there a right way to do this ?
Thanks for the help
Tibor

**Comment by LonerganOnline** [comment]
@oceatoon @timmywil is this feature available or possible
