### ISSUE TITLE
Problems with setMatrix method?

### ISSUE THREAD

**Issue by nalin1017** [timmywil/panzoom#77]
I'm trying to implement a simple horizontal flip function using panzoom.  Here's my code:
var currMatrix = $('.panzoom').panzoom("getMatrix");
alert(currMatrix);
currMatrix[0] = currMatrix[0] \* -1;
alert(currMatrix);
var newMatrix = $('.panzoom').panzoom("setMatrix",currMatrix);
alert(newMatrix);

The 3 alerts output this respectively:

1,0,0,1,0,-17.913710450623
-1,0,0,1,0,-17.913710450623
-1,0,0,1,360,504

Why is setMatrix in this case not setting the new matrix exactly?  The last two matrix numbers, 360 and 504, are the dimensions of my element.  

If I do a vertical flip with  currMatrix[3] = currMatrix[3] \* -1 it works fine.

Am I doing something wrong or is this a bug in setMatrix?

**Comment by LukeM12** [comment]
is it possible to do a binding from setMatrix to setViewBox in Raphaeljs?
